package net.mcreator.thedeepvoid.configuration;

import net.minecraftforge.common.ForgeConfigSpec;

public class DeepVoidConfigConfiguration {
	public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
	public static final ForgeConfigSpec SPEC;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PLACECULTTEMPLE;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PLAYERSTELEPORTINVOID;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PLAYERSTELEPORTINEND;
	public static final ForgeConfigSpec.ConfigValue<Double> TELEPORTHEIGHT;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DEEPVOIDFOG;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STOPACTIVEBLOCKGENERATION;
	public static final ForgeConfigSpec.ConfigValue<Boolean> OLDHOLESTRUCTURE;
	public static final ForgeConfigSpec.ConfigValue<Double> HOLESTRUCTUREY;
	public static final ForgeConfigSpec.ConfigValue<Boolean> CRUMBLINGBEDROCKGENERATE;
	public static final ForgeConfigSpec.ConfigValue<Boolean> GENERATECABIN;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SPAWNABDUCTORS;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SPAWNFALLINGCORPSE;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PLACECORPSEONIMPACT;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STALKERSPAWNS;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STALKINGSTALKERSPAWNS;
	public static final ForgeConfigSpec.ConfigValue<Double> STALKERSPAWNTIMER;
	public static final ForgeConfigSpec.ConfigValue<Double> STALKERDESPAWNTIMER;
	public static final ForgeConfigSpec.ConfigValue<Double> VOIDBORNSPAWNTIMER;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SUMMONBOSSRESPAWN;
	public static final ForgeConfigSpec.ConfigValue<Double> LIGHTREDUCESTALKERTIMER;
	public static final ForgeConfigSpec.ConfigValue<Double> STALKERLIGHTLEVEL;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SEEKLIGHTWARNING;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DESTROYLIGHTSOURCES;
	public static final ForgeConfigSpec.ConfigValue<Double> VOIDBLESSINGTIMER;
	public static final ForgeConfigSpec.ConfigValue<Boolean> ALLOWOTHERWORLDTP;
	public static final ForgeConfigSpec.ConfigValue<Boolean> ALLOWSOULLIGHT;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PLAYERHALLUCINATES;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STALKERBREAKSBLOCKS;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DARKNESS;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DEEPVOIDTP;
	public static final ForgeConfigSpec.ConfigValue<Boolean> ALLOWMININGPRIMORDIALSTONE;
	public static final ForgeConfigSpec.ConfigValue<Boolean> WANDERERCENTERPATHING;
	public static final ForgeConfigSpec.ConfigValue<Boolean> CURSEDISALLOWMININGPLACING;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PREVENTSLEEPING;
	public static final ForgeConfigSpec.ConfigValue<Boolean> BOSSESBREAKARMOR;
	public static final ForgeConfigSpec.ConfigValue<Double> DAMAGECAPPERCENTAGE;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DODAMAGECAP;
	public static final ForgeConfigSpec.ConfigValue<Double> BROKENARMORAMPLIFIER;
	public static final ForgeConfigSpec.ConfigValue<Boolean> GIVEWIKIBOOK;
	public static final ForgeConfigSpec.ConfigValue<Boolean> DOBOSSHPSCALING;
	public static final ForgeConfigSpec.ConfigValue<Double> VOIDBORNHEALTH;
	public static final ForgeConfigSpec.ConfigValue<Double> VOIDBORNHITCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Boolean> BOSSIDLES;
	public static final ForgeConfigSpec.ConfigValue<Boolean> ENDLESSABYSS;
	public static final ForgeConfigSpec.ConfigValue<Boolean> PURGATORY;
	public static final ForgeConfigSpec.ConfigValue<Boolean> GIVETORCHES;
	public static final ForgeConfigSpec.ConfigValue<Boolean> BOSSESDONOTKILL;
	public static final ForgeConfigSpec.ConfigValue<Boolean> STALKED;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEKNIVES;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEBIGSLASH;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEJUMPSHOOT;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLESPIN;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEGRAB;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLESECONDPHASE;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEPIERCEHEART;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEDELAY;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEDELAYSECONDPHASE;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLETELEPORTCOUNT;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLETELEPORTCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLESLASH;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLEANGERTIMER;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLECHAINDISTANCE;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTLECHAINYDISTANCE;
	public static final ForgeConfigSpec.ConfigValue<Double> THROWERBONESAW;
	public static final ForgeConfigSpec.ConfigValue<Double> THROWERSPIN;
	public static final ForgeConfigSpec.ConfigValue<Double> SMASHERSLASH;
	public static final ForgeConfigSpec.ConfigValue<Double> SMASHEROVERHEAD;
	public static final ForgeConfigSpec.ConfigValue<Double> THROWERCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Double> SMASHERCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEMINDTENTACLESCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEMINDHEAL;
	public static final ForgeConfigSpec.ConfigValue<Double> PRIMORDIALCRAWLERSLAM;
	public static final ForgeConfigSpec.ConfigValue<Double> PRIMORDIALCRAWLERSPIT;
	public static final ForgeConfigSpec.ConfigValue<Double> PRIMORDIALCRAWLERDIGPLAYERCLOSE;
	public static final ForgeConfigSpec.ConfigValue<Double> PRIMORDIALCRAWLERDASH;
	public static final ForgeConfigSpec.ConfigValue<Double> PRIMORDIALCRAWLERGOOBLOCK;
	public static final ForgeConfigSpec.ConfigValue<Double> FORBIDDENTOME;
	public static final ForgeConfigSpec.ConfigValue<Double> CRUELSTILETTO;
	public static final ForgeConfigSpec.ConfigValue<Double> SHADESTORMSHADEARROW;
	public static final ForgeConfigSpec.ConfigValue<Double> SHADESTORMBIGARROW;
	public static final ForgeConfigSpec.ConfigValue<Double> SOULREAPERLIFESTEAL;
	public static final ForgeConfigSpec.ConfigValue<Double> VOODOODOLL;
	public static final ForgeConfigSpec.ConfigValue<Double> THEHARVEST;
	public static final ForgeConfigSpec.ConfigValue<Double> THEHARVESTSLASH;
	public static final ForgeConfigSpec.ConfigValue<Double> HERESYBLOODSHOT;
	public static final ForgeConfigSpec.ConfigValue<Double> HERESYGOLDENBLOODSHOT;
	public static final ForgeConfigSpec.ConfigValue<Double> HERESYBLOODSHOTSHOTGUN;
	public static final ForgeConfigSpec.ConfigValue<Double> HERESYGOLDENBLOODSHOTSHOTGUN;
	public static final ForgeConfigSpec.ConfigValue<Double> APOSTASYSOULFUSEDSHOT;
	public static final ForgeConfigSpec.ConfigValue<Double> KNIFEGLOVE;
	public static final ForgeConfigSpec.ConfigValue<Double> ICHORSWORDSPIT;
	public static final ForgeConfigSpec.ConfigValue<Double> ARROWOFSPITE;
	public static final ForgeConfigSpec.ConfigValue<Double> ARROWOFICHORPELLETS;
	public static final ForgeConfigSpec.ConfigValue<Double> MISANTHROPY;
	public static final ForgeConfigSpec.ConfigValue<Double> NERVESOFSTEELCRIT;
	public static final ForgeConfigSpec.ConfigValue<Double> FLESHPARASITETP;
	public static final ForgeConfigSpec.ConfigValue<Boolean> FLESHPARASITEENABLEENTITY;
	public static final ForgeConfigSpec.ConfigValue<Double> ROTTENTONGUEDAMAGE;
	public static final ForgeConfigSpec.ConfigValue<Double> BLOODBOWSPIKE;
	public static final ForgeConfigSpec.ConfigValue<Double> ONYXNAGINATAREACHADDITION;
	public static final ForgeConfigSpec.ConfigValue<Double> NEEDLEFISH;
	public static final ForgeConfigSpec.ConfigValue<Double> TOMBSTONEDOOM;
	public static final ForgeConfigSpec.ConfigValue<Double> KNIFEBANDOLIERFULLCHARGEHIT;
	public static final ForgeConfigSpec.ConfigValue<Double> KNIFEBANDOLIERTIMEBEFORECHARGE;
	public static final ForgeConfigSpec.ConfigValue<Double> KNIFEBANDOLIERKNIFE;
	public static final ForgeConfigSpec.ConfigValue<Double> KNIFEBANDOLIERAOE;
	public static final ForgeConfigSpec.ConfigValue<Double> NECRONOMICONRANGE;
	public static final ForgeConfigSpec.ConfigValue<Double> THECATCHERINITIALDAMAGE;
	public static final ForgeConfigSpec.ConfigValue<Double> THECATCHEREXTRADAMAGE;
	public static final ForgeConfigSpec.ConfigValue<Double> FLYWINGSDURATION;
	public static final ForgeConfigSpec.ConfigValue<Double> PENITENTCROSSREACHADDITION;
	public static final ForgeConfigSpec.ConfigValue<Double> ELDRITCHMAW;
	public static final ForgeConfigSpec.ConfigValue<Double> ABYSSALMARKBURST;
	public static final ForgeConfigSpec.ConfigValue<Double> SHARPSHOOTER;
	public static final ForgeConfigSpec.ConfigValue<Double> PERILSELFDAMAGE;
	public static final ForgeConfigSpec.ConfigValue<Double> PERILDAMAGEMULTIPLIER;
	public static final ForgeConfigSpec.ConfigValue<Double> PERIL;
	public static final ForgeConfigSpec.ConfigValue<Double> BLOODSTONEARMORBONUS;
	public static final ForgeConfigSpec.ConfigValue<Double> VOIDBOW;
	public static final ForgeConfigSpec.ConfigValue<Double> SCYTHESREACH;
	public static final ForgeConfigSpec.ConfigValue<Double> PLAGUEARMORBONUS;
	public static final ForgeConfigSpec.ConfigValue<Double> BLACKHOLEDAMAGE;
	public static final ForgeConfigSpec.ConfigValue<Double> BLACKHOLESTORELIMIT;
	public static final ForgeConfigSpec.ConfigValue<Double> GRIMROTTENARMORBONUS;
	public static final ForgeConfigSpec.ConfigValue<Double> HUNTERARMORBONUS;
	public static final ForgeConfigSpec.ConfigValue<Double> BLOODYCHAINSAW;
	public static final ForgeConfigSpec.ConfigValue<Double> DOUBLEBARRELSHOTGUN;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERWHILEMOVING;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSPIT;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSPIKESPAWN;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERFANGSSPAWN;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSPIKEDURATION;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSPIKEFREQUENCY;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSECONDPHASE;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERSPIKE;
	public static final ForgeConfigSpec.ConfigValue<Double> HIVEWATCHERATTACKRADIUS;
	public static final ForgeConfigSpec.ConfigValue<Double> MASKEDHUNTERCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SPAWNBONECAGES;
	public static final ForgeConfigSpec.ConfigValue<Boolean> SPAWNMASKEDHUNTERS;
	public static final ForgeConfigSpec.ConfigValue<Double> MASKEDHUNTERSCREAMDISTANCE;
	public static final ForgeConfigSpec.ConfigValue<Double> MASKEDHUNTERSCREAMCOOLDOWN;
	public static final ForgeConfigSpec.ConfigValue<Double> MASKEDHUNTERSCREAMCHANCE;
	public static final ForgeConfigSpec.ConfigValue<Double> MASKEDHUNTERSPAWNRADIUS;
	static {
		BUILDER.push("Generation&World");
		PLACECULTTEMPLE = BUILDER.comment("Whether the Cult Temple will be place at 0,0 or not").define("PlaceCultTemple", true);
		PLAYERSTELEPORTINVOID = BUILDER.comment("Whether Players will teleport to the Deep Void when jumping in the Void or not").define("PlayersTeleportInVoid", true);
		PLAYERSTELEPORTINEND = BUILDER.comment("Whether Players will teleport to the Deep Void when falling in the Void in the End or not (If PlayersTeleportInVoid is false, this will automatically be false)").define("PlayersTeleportInEnd", true);
		TELEPORTHEIGHT = BUILDER.comment("At which depth does the Player teleport to the dimension (Default -70)").define("TeleportHeight", (double) -70);
		DEEPVOIDFOG = BUILDER.comment("If the Deep Void should have fog or not").define("DeepVoidFog", true);
		STOPACTIVEBLOCKGENERATION = BUILDER.comment("If blocks under specific biomes should generate plants on top of them to make the cave biome (this depends on random tick speed). If the server lags a lot, set this to true")
				.define("StopActiveBlockGeneration", false);
		OLDHOLESTRUCTURE = BUILDER.comment("If the old structure with the hole to the void should generate in the overworld instead of the new version").define("OldHoleStructure", false);
		HOLESTRUCTUREY = BUILDER.comment("At which Y level should the structure in the Overworld generate (this needs to be at the deepest layer where bedrock generates)").define("HoleStructureY", (double) -64);
		CRUMBLINGBEDROCKGENERATE = BUILDER.comment("If crumbling bedrock should generate in the overworld").define("CrumblingBedrockGenerate", false);
		GENERATECABIN = BUILDER.define("GenerateCabin", true);
		BUILDER.pop();
		BUILDER.push("Spawns");
		SPAWNABDUCTORS = BUILDER.comment("Whether Abductors will spawn in the Overworld or not").define("SpawnAbductors", true);
		SPAWNFALLINGCORPSE = BUILDER.comment("If corpses should fall from the sky in the Deep Void").define("SpawnFallingCorpse", true);
		PLACECORPSEONIMPACT = BUILDER.comment("If falling corpses should place a corpse on impact").define("PlaceCorpseOnImpact", false);
		STALKERSPAWNS = BUILDER.comment("If the Stalker should spawn or not").define("StalkerSpawns", true);
		STALKINGSTALKERSPAWNS = BUILDER.comment("If Stalking Stalkers should spawn or not").define("StalkingStalkerSpawns", true);
		STALKERSPAWNTIMER = BUILDER.comment("The time it takes for the Stalker to spawn in ticks (Default = 1,200 ticks)").define("StalkerSpawnTimer", (double) 1200);
		STALKERDESPAWNTIMER = BUILDER.define("StalkerDespawnTimer", (double) 6000);
		VOIDBORNSPAWNTIMER = BUILDER.comment("How long before a Voidborn spawns when in total darkness (in ticks)").define("VoidbornSpawnTimer", (double) 600);
		SUMMONBOSSRESPAWN = BUILDER.comment("If a respawn entity should be summoned when a boss dies").define("SummonBossRespawn", true);
		LIGHTREDUCESTALKERTIMER = BUILDER.comment("By how much the Stalker Timer is reduced when the player is in light").define("LightReduceStalkerTimer", (double) 4);
		STALKERLIGHTLEVEL = BUILDER.comment("The light level (and under) at which the Stalker can spawn if the Player is in that light level range for long enough").define("StalkerLightLevel", (double) 1);
		BUILDER.pop();
		BUILDER.push("Misc");
		SEEKLIGHTWARNING = BUILDER.comment("Whether the ''Seek Light'' warning should appear when the Stalker is close or not (Happens only one time)").define("SeekLightWarning", true);
		DESTROYLIGHTSOURCES = BUILDER.comment("Whether light sources should be destroyed in the Deep Void or not (disable Light entities)").define("DestroyLightSources", true);
		VOIDBLESSINGTIMER = BUILDER.comment("How long the Void Blessing effect should last when entering the Deep Void (In ticks)").define("VoidBlessingTimer", (double) 600);
		ALLOWOTHERWORLDTP = BUILDER.comment("Should players teleport to the Deep Void when falling in the void in any dimension").define("AllowOtherWorldTp", false);
		ALLOWSOULLIGHT = BUILDER.comment("Should Soul light sources not get destroyed").define("AllowSoulLight", false);
		PLAYERHALLUCINATES = BUILDER.comment("If players should hallucinate below y=1 or not").define("PlayerHallucinates", true);
		STALKERBREAKSBLOCKS = BUILDER.comment("Should the Stalker be able to break certain blocks").define("StalkerBreaksBlocks", true);
		DARKNESS = BUILDER.comment("If Darkness should attack the Player below y=0 while still keeping Hallucinate").define("Darkness", true);
		DEEPVOIDTP = BUILDER.comment("Should players be teleported to the top of the dimension when falling in the void in the Deep Void").define("DeepVoidTp", true);
		ALLOWMININGPRIMORDIALSTONE = BUILDER.comment("Should players be able to mine Primordial Stone with the Shatterbone Pickaxe").define("AllowMiningPrimordialStone", false);
		WANDERERCENTERPATHING = BUILDER.comment("If the Wanderer should pathfind to x=0 z=0 (may affect performance)").define("WandererCenterPathing", false);
		CURSEDISALLOWMININGPLACING = BUILDER.comment("If the Curse Of The Cult should block mining and placing blocks").define("CurseDisallowMiningPlacing", true);
		PREVENTSLEEPING = BUILDER.comment("If sleeping should be prevented when a Masked Hunter is nearby").define("PreventSleeping", true);
		BOSSESBREAKARMOR = BUILDER.comment("If bosses should apply Broken Armor when attacking").define("BossesBreakArmor", true);
		DAMAGECAPPERCENTAGE = BUILDER.comment("At what percentage of the boss's health should the cap activate").define("DamageCapPercentage", (double) 0.15);
		DODAMAGECAP = BUILDER.comment("If bosses should have damage caps").define("DoDamageCap", false);
		BROKENARMORAMPLIFIER = BUILDER.comment("How much armor should the broken armor effect remove (percentage removed)").define("BrokenArmorAmplifier", (double) 0.65);
		GIVEWIKIBOOK = BUILDER.define("GiveWikiBook", true);
		DOBOSSHPSCALING = BUILDER.comment("If the bosses' health should scale based on the number of players").define("DoBossHpScaling", true);
		VOIDBORNHEALTH = BUILDER.comment("How many hits it takes before the Voidborn disappears (damage is irrelevant)").define("VoidbornHealth", (double) 10);
		VOIDBORNHITCOOLDOWN = BUILDER.comment("How long before the Voidborn can get hit again (in ticks)").define("VoidbornHitCooldown", (double) 60);
		BOSSIDLES = BUILDER.comment("If bosses should go back to idling when there are no players nearby").define("BossIdles", true);
		BUILDER.pop();
		BUILDER.push("Gameplay Changes");
		ENDLESSABYSS = BUILDER.comment("The player spawns in the Deep Void").define("EndlessAbyss", false);
		PURGATORY = BUILDER.comment("When the player dies, they get sent to the Deep Void").define("Purgatory", false);
		GIVETORCHES = BUILDER.comment("If torches should be given to players that respawn in the Deep Void (through Purgatory)").define("GiveTorches", true);
		BOSSESDONOTKILL = BUILDER.comment("Bosses can no longer kill you, instead they will bring you down to 1 health and then idle (Does not apply to the Weaver Of Souls)").define("BossesDoNotKill", false);
		STALKED = BUILDER.comment("Allows the Stalker to spawn in the Overworld").define("Stalked", false);
		BUILDER.pop();
		BUILDER.push("Apostle Of Catastrophe");
		APOSTLEKNIVES = BUILDER.comment("Damage of each knife (velocity increases that number)").define("ApostleThreeKnives", (double) 4);
		APOSTLEBIGSLASH = BUILDER.define("ApostleBigSlash", (double) 16);
		APOSTLEJUMPSHOOT = BUILDER.comment("Damage of each knife (velocity increases that number)").define("ApostleJumpShoot", (double) 7);
		APOSTLESPIN = BUILDER.comment("Damage (ignores i-frames)").define("ApostleSpin", (double) 1);
		APOSTLEGRAB = BUILDER.comment("Damage upon landing").define("ApostleGrab", (double) 21);
		APOSTLESECONDPHASE = BUILDER.comment("When under Max Health/Config Number, second phase is active").define("ApostleSecondPhase", (double) 2);
		APOSTLEPIERCEHEART = BUILDER.comment("Damage repeated 4 times").define("ApostlePierceHeart", (double) 6);
		APOSTLEDELAY = BUILDER.comment("Delay between attacks (in ticks)").define("ApostleDelay", (double) 70);
		APOSTLEDELAYSECONDPHASE = BUILDER.comment("Delay between attacks during the second phase (in ticks)").define("ApostleDelaySecondPhase", (double) 50);
		APOSTLETELEPORTCOUNT = BUILDER.comment("How many times can the apostle teleport").define("ApostleTeleportCount", (double) 4);
		APOSTLETELEPORTCOOLDOWN = BUILDER.comment("Cooldown between teleports (in ticks)").define("ApostleTeleportCooldown", (double) 100);
		APOSTLESLASH = BUILDER.define("ApostleSlash", (double) 10);
		APOSTLEANGERTIMER = BUILDER.comment("How long does the player need to keep using a shield before angering the apostle (in ticks)").define("ApostleAngerTimer", (double) 200);
		APOSTLECHAINDISTANCE = BUILDER.comment("How far the player has to be for the apostle to use his chain attack").define("ApostleChainDistance", (double) 28);
		APOSTLECHAINYDISTANCE = BUILDER.comment("How far the player has to be (y position) for the apostle to use his chain attack").define("ApostleChainYDistance", (double) 4);
		BUILDER.pop();
		BUILDER.push("Misanthropic Hivemind");
		THROWERBONESAW = BUILDER.comment("Damage each tick").define("ThrowerBoneSaw", (double) 6);
		THROWERSPIN = BUILDER.comment("Damage each tick").define("ThrowerSpin", (double) 8);
		SMASHERSLASH = BUILDER.comment("Damage").define("SmasherSlash", (double) 10);
		SMASHEROVERHEAD = BUILDER.comment("Damage").define("SmasherOverhead", (double) 14);
		THROWERCOOLDOWN = BUILDER.comment("Cooldown before another can spawn (in ticks)").define("ThrowerCooldown", (double) 200);
		SMASHERCOOLDOWN = BUILDER.comment("Cooldown before another can spawn (in ticks)").define("SmasherCooldown", (double) 200);
		HIVEMINDTENTACLESCOOLDOWN = BUILDER.comment("Cooldown before another can spawn (in ticks)").define("HivemindTentaclesCooldown", (double) 100);
		HIVEMINDHEAL = BUILDER.comment("Amount healed (per summon in the area)").define("HivemindHeal", (double) 30);
		BUILDER.pop();
		BUILDER.push("Primordial Bone Crawler");
		PRIMORDIALCRAWLERSLAM = BUILDER.comment("Damage").define("PrimordialCrawlerSlam", (double) 16);
		PRIMORDIALCRAWLERSPIT = BUILDER.comment("Damage per spit (velocity increases that number)").define("PrimordialCrawlerSpit", (double) 6);
		PRIMORDIALCRAWLERDIGPLAYERCLOSE = BUILDER.comment("Damage").define("PrimordialCrawlerDigPlayerClose", (double) 17);
		PRIMORDIALCRAWLERDASH = BUILDER.comment("Damage (on contact)").define("PrimordialCrawlerDash", (double) 20);
		PRIMORDIALCRAWLERGOOBLOCK = BUILDER.comment("Damage in an AOE").define("PrimordialCrawlerGooBlock", (double) 10);
		BUILDER.pop();
		BUILDER.push("Weapons");
		FORBIDDENTOME = BUILDER.comment("Initial damage & damage dealt by the daggers").define("ForbiddenTome", (double) 6);
		CRUELSTILETTO = BUILDER.comment("Damage dealt in an AOE").define("CruelStiletto", (double) 5);
		SHADESTORMSHADEARROW = BUILDER.comment("Damage dealt by the small arrows").define("ShadestormShadeArrow", (double) 2);
		SHADESTORMBIGARROW = BUILDER.comment("Damage dealt by the big arrow in an AOE (+ original damage)").define("ShadestormBigArrow", (double) 5);
		SOULREAPERLIFESTEAL = BUILDER.comment("The amount healed when using the dark slash (per entity in the AOE)").define("SoulReaperLifesteal", (double) 0.8);
		VOODOODOLL = BUILDER.comment("Damage dealt in an AOE each tick").define("VoodooDoll", (double) 2);
		THEHARVEST = BUILDER.comment("Damage dealt in an AOE").define("TheHarvest", (double) 5);
		THEHARVESTSLASH = BUILDER.comment("Damage dealt in an AOE each tick (ignores armor)").define("TheHarvestSlash", (double) 8);
		HERESYBLOODSHOT = BUILDER.comment("Damage (velocity increases that number)").define("HeresyBloodShot", (double) 4);
		HERESYGOLDENBLOODSHOT = BUILDER.comment("Damage (velocity increases that number)").define("HeresyGoldenBloodShot", (double) 2.5);
		HERESYBLOODSHOTSHOTGUN = BUILDER.comment("Damage (velocity increases that number)").define("HeresyBloodShotShotgun", (double) 25);
		HERESYGOLDENBLOODSHOTSHOTGUN = BUILDER.comment("Damage (velocity increases that number)").define("HeresyGoldenBloodShotShotgun", (double) 20);
		APOSTASYSOULFUSEDSHOT = BUILDER.comment("Damage (velocity increases that number)").define("ApostasySoulFusedShot", (double) 3);
		KNIFEGLOVE = BUILDER.comment("Damage (velocity increases that number)").define("KnifeGlove", (double) 4.5);
		ICHORSWORDSPIT = BUILDER.comment("Damage per projectile").define("IchorSwordSpit", (double) 5);
		ARROWOFSPITE = BUILDER.comment("Damage per projectile").define("ArrowOfSpite", (double) 4);
		ARROWOFICHORPELLETS = BUILDER.comment("Damage per projectile").define("ArrowOfIchorPellets", (double) 2.5);
		MISANTHROPY = BUILDER.comment("Damage (velocity increases that number)").define("Misanthropy", (double) 3.2);
		NERVESOFSTEELCRIT = BUILDER.define("NervesOfSteelCrit", (double) 34);
		FLESHPARASITETP = BUILDER.comment("Damage upon teleporting to the target").define("FleshParasiteTp", (double) 15);
		FLESHPARASITEENABLEENTITY = BUILDER.comment("If the flesh parasite should work on mobs other than players (for servers: may cause extreme lag if used repeatedly)").define("FleshParasiteEnableEntity", true);
		ROTTENTONGUEDAMAGE = BUILDER.comment("Extra damage when on low health").define("RottenTongueDamage", (double) 5);
		BLOODBOWSPIKE = BUILDER.define("BloodBowSpike", (double) 2);
		ONYXNAGINATAREACHADDITION = BUILDER.define("OnyxNaginataReachAddition", (double) 1.5);
		NEEDLEFISH = BUILDER.define("Needlefish", (double) 4);
		TOMBSTONEDOOM = BUILDER.comment("Ignores armor").define("TombstoneDoom", (double) 16);
		KNIFEBANDOLIERFULLCHARGEHIT = BUILDER.define("KnifeBandolierFullChargeHit", (double) 6);
		KNIFEBANDOLIERTIMEBEFORECHARGE = BUILDER.comment("How long it takes before the knife bandolier is fully charged (in ticks)").define("KnifeBandolierTimeBeforeCharge", (double) 90);
		KNIFEBANDOLIERKNIFE = BUILDER.comment("Damage per knife").define("KnifeBandolierKnife", (double) 4);
		KNIFEBANDOLIERAOE = BUILDER.comment("Damage in an AOE each tick").define("KnifeBandolierAoe", (double) 6);
		NECRONOMICONRANGE = BUILDER.define("NecronomiconRange", (double) 16);
		THECATCHERINITIALDAMAGE = BUILDER.comment("Damage upon successfully catching an entity").define("TheCatcherInitialDamage", (double) 2);
		THECATCHEREXTRADAMAGE = BUILDER.comment("Damage added to the weapon's base damage upon catching an entity").define("TheCatcherExtraDamage", (double) 4);
		FLYWINGSDURATION = BUILDER.comment("For how long can the player fly (in ticks)").define("FlyWingsDuration", (double) 100);
		PENITENTCROSSREACHADDITION = BUILDER.define("PenitentCrossReachAddition", (double) 1);
		ELDRITCHMAW = BUILDER.comment("Damage (velocity increases that number)").define("EldritchMaw", (double) 0.7);
		ABYSSALMARKBURST = BUILDER.comment("Damage dealt when the effect expires. The damage is equal to the level of the effect * value (ignores armor)").define("AbyssalMarkBurst", (double) 2.15);
		SHARPSHOOTER = BUILDER.comment("Distance is multiplied by this value. The result multiplies the initial damage").define("Sharpshooter", (double) 0.085);
		PERILSELFDAMAGE = BUILDER.comment("The damage dealt to the player upon shooting themselves (ignores armor)").define("PerilSelfDamage", (double) 18);
		PERILDAMAGEMULTIPLIER = BUILDER.comment("Adrenaline is multiplied by that value, which is then used to multiply the projectile's damage").define("PerilDamageMultiplier", (double) 4);
		PERIL = BUILDER.comment("Damage (velocity increases that number)").define("Peril", (double) 2.8);
		BLOODSTONEARMORBONUS = BUILDER.comment("The attack damage bonus").define("BloodstoneArmorBonus", (double) 2);
		VOIDBOW = BUILDER.comment("Void bow damage (ignores armor and i-frames)").define("VoidBow", (double) 8);
		SCYTHESREACH = BUILDER.define("ScythesReach", (double) 0.5);
		PLAGUEARMORBONUS = BUILDER.comment("The attack damage bonus").define("PlagueArmorBonus", (double) 2);
		BLACKHOLEDAMAGE = BUILDER.define("BlackHoleDamage", (double) 4);
		BLACKHOLESTORELIMIT = BUILDER.comment("The arrow storing limit of Black Hole when enchanted with Dimensional Burst").define("BlackHoleStoreLimit", (double) 60);
		GRIMROTTENARMORBONUS = BUILDER.comment("The attack damage bonus").define("GrimRottenArmorBonus", (double) 1);
		HUNTERARMORBONUS = BUILDER.comment("The attack damage bonus").define("HunterArmorBonus", (double) 1);
		BLOODYCHAINSAW = BUILDER.comment("Base damage multiplier (ignores i-frames)").define("BloodyChainsaw", (double) 0.05);
		DOUBLEBARRELSHOTGUN = BUILDER.comment("Damage (ignores i-frames)").define("DoubleBarrelShotgun", (double) 0.7);
		BUILDER.pop();
		BUILDER.push("Hive's Watcher");
		HIVEWATCHERWHILEMOVING = BUILDER.comment("Damage each tick").define("HiveWatcherWhileMoving", (double) 10);
		HIVEWATCHERSPIT = BUILDER.comment("Damage per projectile").define("HiveWatcherSpit", (double) 12);
		HIVEWATCHERSPIKESPAWN = BUILDER.comment("Percentage change of spawning bone spikes").define("HiveWatcherSpikeSpawn", (double) 0.3);
		HIVEWATCHERFANGSSPAWN = BUILDER.comment("Percentage change of spawning fangs").define("HiveWatcherFangsSpawn", (double) 0.3);
		HIVEWATCHERSPIKEDURATION = BUILDER.comment("How long the bone spike attack lasts (in ticks)").define("HiveWatcherSpikeDuration", (double) 80);
		HIVEWATCHERSPIKEFREQUENCY = BUILDER.comment("The frequency at which the bone spikes spawn (in ticks)").define("HiveWatcherSpikeFrequency", (double) 5);
		HIVEWATCHERSECONDPHASE = BUILDER.comment("When under Max Health/Config Number, second phase is active").define("HiveWatcherSecondPhase", (double) 1.7);
		HIVEWATCHERSPIKE = BUILDER.comment("Damage when the player is near the spike").define("HiveWatcherSpike", (double) 10);
		HIVEWATCHERATTACKRADIUS = BUILDER.comment("Size of the damaging zone around the boss while it's moving").define("HiveWatcherAttackRadius", (double) 7);
		BUILDER.pop();
		BUILDER.push("Masked Hunter");
		MASKEDHUNTERCOOLDOWN = BUILDER.comment("The cooldown before a Masked Hunter can spawn naturally (In ticks, 24,000 ticks is one day)").define("MaskedHunterCooldown", (double) 72000);
		SPAWNBONECAGES = BUILDER.comment("If Bone Cages should be placed by Masked Hunters").define("SpawnBoneCages", true);
		SPAWNMASKEDHUNTERS = BUILDER.comment("Whether Masked Hunters will spawn in the Overworld or not").define("SpawnMaskedHunters", true);
		MASKEDHUNTERSCREAMDISTANCE = BUILDER.comment("From how far away the hunter's screams can be heard (in chunks)").define("MaskedHunterScreamDistance", (double) 16);
		MASKEDHUNTERSCREAMCOOLDOWN = BUILDER.comment("How long before the hunter screams (in ticks, 24,000 ticks is one day)").define("MaskedHunterScreamCooldown", (double) 72000);
		MASKEDHUNTERSCREAMCHANCE = BUILDER.comment("The chance of the masked hunter screaming (percentage divided by 100)").define("MaskedHunterScreamChance", (double) 0.7);
		MASKEDHUNTERSPAWNRADIUS = BUILDER.comment("The radius around the player in which the masked hunter cannot spawn (in blocks * 2)").define("MaskedHunterSpawnRadius", (double) 200);
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}
