
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedeepvoid.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.effect.MobEffect;

import net.mcreator.thedeepvoid.potion.WeaverCurseMobEffect;
import net.mcreator.thedeepvoid.potion.VoidriumMarkMobEffect;
import net.mcreator.thedeepvoid.potion.VoidBlessingMobEffect;
import net.mcreator.thedeepvoid.potion.VanishMobEffect;
import net.mcreator.thedeepvoid.potion.TributeToTheVoidMobEffect;
import net.mcreator.thedeepvoid.potion.TrembleMobEffect;
import net.mcreator.thedeepvoid.potion.TerrorMobEffect;
import net.mcreator.thedeepvoid.potion.StickyMobEffect;
import net.mcreator.thedeepvoid.potion.StareMobEffect;
import net.mcreator.thedeepvoid.potion.RottenHeartMobEffect;
import net.mcreator.thedeepvoid.potion.RotMobEffect;
import net.mcreator.thedeepvoid.potion.RootBlindMobEffect;
import net.mcreator.thedeepvoid.potion.PowerfulShotMobEffect;
import net.mcreator.thedeepvoid.potion.PlagueMobEffect;
import net.mcreator.thedeepvoid.potion.ParasitizedMobEffect;
import net.mcreator.thedeepvoid.potion.ParanoiaMobEffect;
import net.mcreator.thedeepvoid.potion.PainfulMobEffect;
import net.mcreator.thedeepvoid.potion.PainKillerMobEffect;
import net.mcreator.thedeepvoid.potion.MotherlyCallMobEffect;
import net.mcreator.thedeepvoid.potion.MadnessMobEffect;
import net.mcreator.thedeepvoid.potion.LurkerHeadNearMobEffect;
import net.mcreator.thedeepvoid.potion.LookingMobEffect;
import net.mcreator.thedeepvoid.potion.LacerationMobEffect;
import net.mcreator.thedeepvoid.potion.IchorBurnMobEffect;
import net.mcreator.thedeepvoid.potion.HexedMobEffect;
import net.mcreator.thedeepvoid.potion.HeavyMobEffect;
import net.mcreator.thedeepvoid.potion.HandsOfTheAberrationMobEffect;
import net.mcreator.thedeepvoid.potion.HallucinateMobEffect;
import net.mcreator.thedeepvoid.potion.GoldenBloodMobEffect;
import net.mcreator.thedeepvoid.potion.GluttonyMobEffect;
import net.mcreator.thedeepvoid.potion.FixationMobEffect;
import net.mcreator.thedeepvoid.potion.ExperiencedMobEffect;
import net.mcreator.thedeepvoid.potion.DoomMobEffect;
import net.mcreator.thedeepvoid.potion.DominateMobEffect;
import net.mcreator.thedeepvoid.potion.DistractedMobEffect;
import net.mcreator.thedeepvoid.potion.DecompositionMobEffect;
import net.mcreator.thedeepvoid.potion.DebilitatedMobEffect;
import net.mcreator.thedeepvoid.potion.DeadInsideMobEffect;
import net.mcreator.thedeepvoid.potion.CreatureRepellentMobEffect;
import net.mcreator.thedeepvoid.potion.CrateMagnetMobEffect;
import net.mcreator.thedeepvoid.potion.ComboMobEffect;
import net.mcreator.thedeepvoid.potion.ChainedMobEffect;
import net.mcreator.thedeepvoid.potion.CallOfTheVoidMobEffect;
import net.mcreator.thedeepvoid.potion.BullseyeMobEffect;
import net.mcreator.thedeepvoid.potion.BrokenArmorMobEffect;
import net.mcreator.thedeepvoid.potion.BrainFogMobEffect;
import net.mcreator.thedeepvoid.potion.BlossomMobEffect;
import net.mcreator.thedeepvoid.potion.BloodBoilMobEffect;
import net.mcreator.thedeepvoid.potion.AmbrosiaWithdrawalMobEffect;
import net.mcreator.thedeepvoid.potion.AdaptiveMobEffect;
import net.mcreator.thedeepvoid.potion.AdaptedMobEffect;
import net.mcreator.thedeepvoid.potion.AbyssalMarkMobEffect;
import net.mcreator.thedeepvoid.TheDeepVoidMod;

public class TheDeepVoidModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, TheDeepVoidMod.MODID);
	public static final RegistryObject<MobEffect> DECOMPOSITION = REGISTRY.register("decomposition", () -> new DecompositionMobEffect());
	public static final RegistryObject<MobEffect> DEAD_INSIDE = REGISTRY.register("dead_inside", () -> new DeadInsideMobEffect());
	public static final RegistryObject<MobEffect> CALL_OF_THE_VOID = REGISTRY.register("call_of_the_void", () -> new CallOfTheVoidMobEffect());
	public static final RegistryObject<MobEffect> ROTTEN_HEART = REGISTRY.register("rotten_heart", () -> new RottenHeartMobEffect());
	public static final RegistryObject<MobEffect> HALLUCINATE = REGISTRY.register("hallucinate", () -> new HallucinateMobEffect());
	public static final RegistryObject<MobEffect> COMBO = REGISTRY.register("combo", () -> new ComboMobEffect());
	public static final RegistryObject<MobEffect> MADNESS = REGISTRY.register("madness", () -> new MadnessMobEffect());
	public static final RegistryObject<MobEffect> FIXATION = REGISTRY.register("fixation", () -> new FixationMobEffect());
	public static final RegistryObject<MobEffect> VOID_BLESSING = REGISTRY.register("void_blessing", () -> new VoidBlessingMobEffect());
	public static final RegistryObject<MobEffect> ROT = REGISTRY.register("rot", () -> new RotMobEffect());
	public static final RegistryObject<MobEffect> PAIN_KILLER = REGISTRY.register("pain_killer", () -> new PainKillerMobEffect());
	public static final RegistryObject<MobEffect> STARE = REGISTRY.register("stare", () -> new StareMobEffect());
	public static final RegistryObject<MobEffect> TREMBLE = REGISTRY.register("tremble", () -> new TrembleMobEffect());
	public static final RegistryObject<MobEffect> PARANOIA = REGISTRY.register("paranoia", () -> new ParanoiaMobEffect());
	public static final RegistryObject<MobEffect> GOLDEN_BLOOD = REGISTRY.register("golden_blood", () -> new GoldenBloodMobEffect());
	public static final RegistryObject<MobEffect> LOOKING = REGISTRY.register("looking", () -> new LookingMobEffect());
	public static final RegistryObject<MobEffect> PAINFUL = REGISTRY.register("painful", () -> new PainfulMobEffect());
	public static final RegistryObject<MobEffect> ROOT_BLIND = REGISTRY.register("root_blind", () -> new RootBlindMobEffect());
	public static final RegistryObject<MobEffect> LURKER_HEAD_NEAR = REGISTRY.register("lurker_head_near", () -> new LurkerHeadNearMobEffect());
	public static final RegistryObject<MobEffect> VOIDRIUM_MARK = REGISTRY.register("voidrium_mark", () -> new VoidriumMarkMobEffect());
	public static final RegistryObject<MobEffect> MOTHERLY_CALL = REGISTRY.register("motherly_call", () -> new MotherlyCallMobEffect());
	public static final RegistryObject<MobEffect> DISTRACTED = REGISTRY.register("distracted", () -> new DistractedMobEffect());
	public static final RegistryObject<MobEffect> WEAVER_CURSE = REGISTRY.register("weaver_curse", () -> new WeaverCurseMobEffect());
	public static final RegistryObject<MobEffect> HEXED = REGISTRY.register("hexed", () -> new HexedMobEffect());
	public static final RegistryObject<MobEffect> DOOM = REGISTRY.register("doom", () -> new DoomMobEffect());
	public static final RegistryObject<MobEffect> LACERATION = REGISTRY.register("laceration", () -> new LacerationMobEffect());
	public static final RegistryObject<MobEffect> BLOOD_BOIL = REGISTRY.register("blood_boil", () -> new BloodBoilMobEffect());
	public static final RegistryObject<MobEffect> VANISH = REGISTRY.register("vanish", () -> new VanishMobEffect());
	public static final RegistryObject<MobEffect> BLOSSOM = REGISTRY.register("blossom", () -> new BlossomMobEffect());
	public static final RegistryObject<MobEffect> DEBILITATED = REGISTRY.register("debilitated", () -> new DebilitatedMobEffect());
	public static final RegistryObject<MobEffect> BROKEN_ARMOR = REGISTRY.register("broken_armor", () -> new BrokenArmorMobEffect());
	public static final RegistryObject<MobEffect> HEAVY = REGISTRY.register("heavy", () -> new HeavyMobEffect());
	public static final RegistryObject<MobEffect> AMBROSIA_WITHDRAWAL = REGISTRY.register("ambrosia_withdrawal", () -> new AmbrosiaWithdrawalMobEffect());
	public static final RegistryObject<MobEffect> PLAGUE = REGISTRY.register("plague", () -> new PlagueMobEffect());
	public static final RegistryObject<MobEffect> ICHOR_BURN = REGISTRY.register("ichor_burn", () -> new IchorBurnMobEffect());
	public static final RegistryObject<MobEffect> POWERFUL_SHOT = REGISTRY.register("powerful_shot", () -> new PowerfulShotMobEffect());
	public static final RegistryObject<MobEffect> CRATE_MAGNET = REGISTRY.register("crate_magnet", () -> new CrateMagnetMobEffect());
	public static final RegistryObject<MobEffect> PARASITIZED = REGISTRY.register("parasitized", () -> new ParasitizedMobEffect());
	public static final RegistryObject<MobEffect> CREATURE_REPELLENT = REGISTRY.register("creature_repellent", () -> new CreatureRepellentMobEffect());
	public static final RegistryObject<MobEffect> ABYSSAL_MARK = REGISTRY.register("abyssal_mark", () -> new AbyssalMarkMobEffect());
	public static final RegistryObject<MobEffect> EXPERIENCED = REGISTRY.register("experienced", () -> new ExperiencedMobEffect());
	public static final RegistryObject<MobEffect> CHAINED = REGISTRY.register("chained", () -> new ChainedMobEffect());
	public static final RegistryObject<MobEffect> BULLSEYE = REGISTRY.register("bullseye", () -> new BullseyeMobEffect());
	public static final RegistryObject<MobEffect> BRAIN_FOG = REGISTRY.register("brain_fog", () -> new BrainFogMobEffect());
	public static final RegistryObject<MobEffect> TRIBUTE_TO_THE_VOID = REGISTRY.register("tribute_to_the_void", () -> new TributeToTheVoidMobEffect());
	public static final RegistryObject<MobEffect> STICKY = REGISTRY.register("sticky", () -> new StickyMobEffect());
	public static final RegistryObject<MobEffect> GLUTTONY = REGISTRY.register("gluttony", () -> new GluttonyMobEffect());
	public static final RegistryObject<MobEffect> DOMINATE = REGISTRY.register("dominate", () -> new DominateMobEffect());
	public static final RegistryObject<MobEffect> ADAPTIVE = REGISTRY.register("adaptive", () -> new AdaptiveMobEffect());
	public static final RegistryObject<MobEffect> TERROR = REGISTRY.register("terror", () -> new TerrorMobEffect());
	public static final RegistryObject<MobEffect> HANDS_OF_THE_ABERRATION = REGISTRY.register("hands_of_the_aberration", () -> new HandsOfTheAberrationMobEffect());
	public static final RegistryObject<MobEffect> ADAPTED = REGISTRY.register("adapted", () -> new AdaptedMobEffect());
}
