
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedeepvoid.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.thedeepvoid.item.WitherNeedleItem;
import net.mcreator.thedeepvoid.item.WeaverRobeItem;
import net.mcreator.thedeepvoid.item.WeaverOfSoulsTreasureBagItem;
import net.mcreator.thedeepvoid.item.WeaverMaskItem;
import net.mcreator.thedeepvoid.item.WeaverLeggingsItem;
import net.mcreator.thedeepvoid.item.WeaverBootsItem;
import net.mcreator.thedeepvoid.item.VultureMuzzleItem;
import net.mcreator.thedeepvoid.item.VoodooDollItem;
import net.mcreator.thedeepvoid.item.VoidriumSwordItem;
import net.mcreator.thedeepvoid.item.VoidriumShovelItem;
import net.mcreator.thedeepvoid.item.VoidriumPickaxeItem;
import net.mcreator.thedeepvoid.item.VoidriumItem;
import net.mcreator.thedeepvoid.item.VoidriumHoeItem;
import net.mcreator.thedeepvoid.item.VoidriumBulwarkItem;
import net.mcreator.thedeepvoid.item.VoidriumAxeItem;
import net.mcreator.thedeepvoid.item.VoidPendantItem;
import net.mcreator.thedeepvoid.item.VoidMirrorItem;
import net.mcreator.thedeepvoid.item.VoidMatterItem;
import net.mcreator.thedeepvoid.item.VoidLensItem;
import net.mcreator.thedeepvoid.item.VoidDaggerItem;
import net.mcreator.thedeepvoid.item.VoidCloakItem;
import net.mcreator.thedeepvoid.item.UmbriumGemItem;
import net.mcreator.thedeepvoid.item.TombstoneItem;
import net.mcreator.thedeepvoid.item.TheHarvestItem;
import net.mcreator.thedeepvoid.item.SulfurItem;
import net.mcreator.thedeepvoid.item.SulfurBombItem;
import net.mcreator.thedeepvoid.item.StalkerTreatItem;
import net.mcreator.thedeepvoid.item.StalkerScytheClawItem;
import net.mcreator.thedeepvoid.item.SpyglassDummyItem;
import net.mcreator.thedeepvoid.item.SpeedNeedleItem;
import net.mcreator.thedeepvoid.item.SoulShardItem;
import net.mcreator.thedeepvoid.item.SoulFusedIngotItem;
import net.mcreator.thedeepvoid.item.SoulCleaverItem;
import net.mcreator.thedeepvoid.item.SorrowArmorTrimItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateRotItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateOnyxItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateLavenditeItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateGrimItem;
import net.mcreator.thedeepvoid.item.SinsAndSinnersItem;
import net.mcreator.thedeepvoid.item.ShadestormItem;
import net.mcreator.thedeepvoid.item.ScavengerArmorTrimItem;
import net.mcreator.thedeepvoid.item.ScareArmorTrimItem;
import net.mcreator.thedeepvoid.item.SaturationNeedleItem;
import net.mcreator.thedeepvoid.item.SacredVoidriumItem;
import net.mcreator.thedeepvoid.item.SacredCinnabarItem;
import net.mcreator.thedeepvoid.item.RoughVoidriumItem;
import net.mcreator.thedeepvoid.item.RottenWoodenSwordItem;
import net.mcreator.thedeepvoid.item.RottenTongueHookItem;
import net.mcreator.thedeepvoid.item.RottenStoneSwordItem;
import net.mcreator.thedeepvoid.item.RottenNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.RottenIronSwordItem;
import net.mcreator.thedeepvoid.item.RottenGoldenSwordItem;
import net.mcreator.thedeepvoid.item.RottenDiamondSwordItem;
import net.mcreator.thedeepvoid.item.RottenDelightItem;
import net.mcreator.thedeepvoid.item.RottenDartItem;
import net.mcreator.thedeepvoid.item.RottenBoneItem;
import net.mcreator.thedeepvoid.item.RottenBoneArmorItem;
import net.mcreator.thedeepvoid.item.RottenAllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.RotNeedleItem;
import net.mcreator.thedeepvoid.item.RootingTomeItem;
import net.mcreator.thedeepvoid.item.RidingCropItem;
import net.mcreator.thedeepvoid.item.ResistanceNeedleItem;
import net.mcreator.thedeepvoid.item.ReinforcedPickaxeItem;
import net.mcreator.thedeepvoid.item.RegenerationNeedleItem;
import net.mcreator.thedeepvoid.item.RefinedOnyxItem;
import net.mcreator.thedeepvoid.item.RefinedCinnabarItem;
import net.mcreator.thedeepvoid.item.RefinedBismuthItem;
import net.mcreator.thedeepvoid.item.ReapingHookItem;
import net.mcreator.thedeepvoid.item.PusBallItem;
import net.mcreator.thedeepvoid.item.PoisonNeedleItem;
import net.mcreator.thedeepvoid.item.OnyxSwordItem;
import net.mcreator.thedeepvoid.item.OnyxShovelItem;
import net.mcreator.thedeepvoid.item.OnyxPickaxeItem;
import net.mcreator.thedeepvoid.item.OnyxNeedleItem;
import net.mcreator.thedeepvoid.item.OnyxItem;
import net.mcreator.thedeepvoid.item.OnyxHoeItem;
import net.mcreator.thedeepvoid.item.OnyxFlareGunItem;
import net.mcreator.thedeepvoid.item.OnyxAxeItem;
import net.mcreator.thedeepvoid.item.OnyxArmorItem;
import net.mcreator.thedeepvoid.item.OffHandVoidDaggerItem;
import net.mcreator.thedeepvoid.item.MournerHideItem;
import net.mcreator.thedeepvoid.item.LurkingMusicDiscItem;
import net.mcreator.thedeepvoid.item.LiquidVoidItem;
import net.mcreator.thedeepvoid.item.LickerHookItem;
import net.mcreator.thedeepvoid.item.LavenditeWoodenSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeVoidriumSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeStoneSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeShovelItem;
import net.mcreator.thedeepvoid.item.LavenditeShieldItem;
import net.mcreator.thedeepvoid.item.LavenditeShardItem;
import net.mcreator.thedeepvoid.item.LavenditePickaxeItem;
import net.mcreator.thedeepvoid.item.LavenditeOnyxSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeItem;
import net.mcreator.thedeepvoid.item.LavenditeIronSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeHoeItem;
import net.mcreator.thedeepvoid.item.LavenditeGoldenSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeDiamondSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeDevourerHookItem;
import net.mcreator.thedeepvoid.item.LavenditeBoneSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeAxeItem;
import net.mcreator.thedeepvoid.item.LavenditeArmorItem;
import net.mcreator.thedeepvoid.item.LavenditeAllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.KnifeGloveItem;
import net.mcreator.thedeepvoid.item.JumpBoostNeedleItem;
import net.mcreator.thedeepvoid.item.JudgementItem;
import net.mcreator.thedeepvoid.item.HexedNeedleItem;
import net.mcreator.thedeepvoid.item.HexedDollItem;
import net.mcreator.thedeepvoid.item.HeresyItem;
import net.mcreator.thedeepvoid.item.HealthBoostNeedleItem;
import net.mcreator.thedeepvoid.item.HatchingEnzymeItem;
import net.mcreator.thedeepvoid.item.HarvesterMaskItem;
import net.mcreator.thedeepvoid.item.HardFleshSwordItem;
import net.mcreator.thedeepvoid.item.HardFleshIngotItem;
import net.mcreator.thedeepvoid.item.GrimberryPieItem;
import net.mcreator.thedeepvoid.item.GrimberryJuiceItem;
import net.mcreator.thedeepvoid.item.GrimberryItem;
import net.mcreator.thedeepvoid.item.GrimSickleItem;
import net.mcreator.thedeepvoid.item.GrimShardItem;
import net.mcreator.thedeepvoid.item.GrimScytheItem;
import net.mcreator.thedeepvoid.item.GrimRottenBoneItem;
import net.mcreator.thedeepvoid.item.GrimLavenditeItem;
import net.mcreator.thedeepvoid.item.GrimGemItem;
import net.mcreator.thedeepvoid.item.GrimCrawlerItem;
import net.mcreator.thedeepvoid.item.GravediggerShovelItem;
import net.mcreator.thedeepvoid.item.GooSwordItem;
import net.mcreator.thedeepvoid.item.GooBallItem;
import net.mcreator.thedeepvoid.item.GoldenEyeballItem;
import net.mcreator.thedeepvoid.item.GlowingNeedleItem;
import net.mcreator.thedeepvoid.item.ForgottenTokenItem;
import net.mcreator.thedeepvoid.item.ForbiddenTomeItem;
import net.mcreator.thedeepvoid.item.FleshGloveItem;
import net.mcreator.thedeepvoid.item.FleshChunkItem;
import net.mcreator.thedeepvoid.item.FleshArmorItem;
import net.mcreator.thedeepvoid.item.FireResistanceNeedleItem;
import net.mcreator.thedeepvoid.item.EyeballSoupItem;
import net.mcreator.thedeepvoid.item.EyeballItem;
import net.mcreator.thedeepvoid.item.EyeShieldItem;
import net.mcreator.thedeepvoid.item.EndlessQuiverItem;
import net.mcreator.thedeepvoid.item.ElytraPieceItem;
import net.mcreator.thedeepvoid.item.DisturbingRootItem;
import net.mcreator.thedeepvoid.item.DevourerTendrilItem;
import net.mcreator.thedeepvoid.item.DevourerShieldItem;
import net.mcreator.thedeepvoid.item.DevourerHookItem;
import net.mcreator.thedeepvoid.item.DarkmareItem;
import net.mcreator.thedeepvoid.item.CultItem;
import net.mcreator.thedeepvoid.item.CruelStilettoItem;
import net.mcreator.thedeepvoid.item.CreepOMeterItem;
import net.mcreator.thedeepvoid.item.CrawlerOmeletteItem;
import net.mcreator.thedeepvoid.item.CrawlerItem;
import net.mcreator.thedeepvoid.item.CookedCrawlerEggItem;
import net.mcreator.thedeepvoid.item.CinnabarRollItem;
import net.mcreator.thedeepvoid.item.CinnabarItem;
import net.mcreator.thedeepvoid.item.ChasmsMusicDiscItem;
import net.mcreator.thedeepvoid.item.ChainsawItem;
import net.mcreator.thedeepvoid.item.BoneSwordItem;
import net.mcreator.thedeepvoid.item.BoneShovelItem;
import net.mcreator.thedeepvoid.item.BonePickaxeItem;
import net.mcreator.thedeepvoid.item.BoneNeedleItem;
import net.mcreator.thedeepvoid.item.BoneMushItem;
import net.mcreator.thedeepvoid.item.BoneLoafItem;
import net.mcreator.thedeepvoid.item.BoneHoeItem;
import net.mcreator.thedeepvoid.item.BoneCrawlerChitinItem;
import net.mcreator.thedeepvoid.item.BoneBallItem;
import net.mcreator.thedeepvoid.item.BoneAxeItem;
import net.mcreator.thedeepvoid.item.BloodyTongueItem;
import net.mcreator.thedeepvoid.item.BlackMossItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteShovelItem;
import net.mcreator.thedeepvoid.item.BismuthNetheritePickaxeItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteHoeItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteAxeItem;
import net.mcreator.thedeepvoid.item.BismuthItem;
import net.mcreator.thedeepvoid.item.ApostleOfCatastropheTreasureBagItem;
import net.mcreator.thedeepvoid.item.AncientOnyxItem;
import net.mcreator.thedeepvoid.item.AmbrosiaItem;
import net.mcreator.thedeepvoid.item.AllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.AllSeeingShovelItem;
import net.mcreator.thedeepvoid.item.AllSeeingPickaxeItem;
import net.mcreator.thedeepvoid.item.AllSeeingItem;
import net.mcreator.thedeepvoid.item.AllSeeingHoeItem;
import net.mcreator.thedeepvoid.item.AllSeeingAxeItem;
import net.mcreator.thedeepvoid.item.AbsorptionNeedleItem;
import net.mcreator.thedeepvoid.TheDeepVoidMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class TheDeepVoidModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, TheDeepVoidMod.MODID);
	public static final RegistryObject<Item> BLOCK_OF_BONE_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_BONE_PILE);
	public static final RegistryObject<Item> PILE_OF_BONES = block(TheDeepVoidModBlocks.PILE_OF_BONES);
	public static final RegistryObject<Item> STALKER_SCYTHE_CLAW = REGISTRY.register("stalker_scythe_claw", () -> new StalkerScytheClawItem());
	public static final RegistryObject<Item> ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.ROTTEN_BONE_BLOCK);
	public static final RegistryObject<Item> ROTTEN_BONE = REGISTRY.register("rotten_bone", () -> new RottenBoneItem());
	public static final RegistryObject<Item> BONE_MARROW = block(TheDeepVoidModBlocks.BONE_MARROW);
	public static final RegistryObject<Item> BONE_MUSH = REGISTRY.register("bone_mush", () -> new BoneMushItem());
	public static final RegistryObject<Item> CORPSE = block(TheDeepVoidModBlocks.CORPSE);
	public static final RegistryObject<Item> CORPSE_SPAWN = block(TheDeepVoidModBlocks.CORPSE_SPAWN);
	public static final RegistryObject<Item> BONE_SWORD = REGISTRY.register("bone_sword", () -> new BoneSwordItem());
	public static final RegistryObject<Item> BONE_PICKAXE = REGISTRY.register("bone_pickaxe", () -> new BonePickaxeItem());
	public static final RegistryObject<Item> BONE_AXE = REGISTRY.register("bone_axe", () -> new BoneAxeItem());
	public static final RegistryObject<Item> BONE_SHOVEL = REGISTRY.register("bone_shovel", () -> new BoneShovelItem());
	public static final RegistryObject<Item> BONE_HOE = REGISTRY.register("bone_hoe", () -> new BoneHoeItem());
	public static final RegistryObject<Item> ROTTEN_BONE_ARMOR_HELMET = REGISTRY.register("rotten_bone_armor_helmet", () -> new RottenBoneArmorItem.Helmet());
	public static final RegistryObject<Item> ROTTEN_BONE_ARMOR_CHESTPLATE = REGISTRY.register("rotten_bone_armor_chestplate", () -> new RottenBoneArmorItem.Chestplate());
	public static final RegistryObject<Item> ROTTEN_BONE_ARMOR_LEGGINGS = REGISTRY.register("rotten_bone_armor_leggings", () -> new RottenBoneArmorItem.Leggings());
	public static final RegistryObject<Item> ROTTEN_BONE_ARMOR_BOOTS = REGISTRY.register("rotten_bone_armor_boots", () -> new RottenBoneArmorItem.Boots());
	public static final RegistryObject<Item> MOURNER_HIDE = REGISTRY.register("mourner_hide", () -> new MournerHideItem());
	public static final RegistryObject<Item> ROTTEN_GRASS = doubleBlock(TheDeepVoidModBlocks.ROTTEN_GRASS);
	public static final RegistryObject<Item> MOSSY_BONE_PILE = block(TheDeepVoidModBlocks.MOSSY_BONE_PILE);
	public static final RegistryObject<Item> ONYX = REGISTRY.register("onyx", () -> new OnyxItem());
	public static final RegistryObject<Item> ONYX_ORE = block(TheDeepVoidModBlocks.ONYX_ORE);
	public static final RegistryObject<Item> SMITHING_TEMPLATE_ONYX = REGISTRY.register("smithing_template_onyx", () -> new SmithingTemplateOnyxItem());
	public static final RegistryObject<Item> FERRYMAN_LANTERN = block(TheDeepVoidModBlocks.FERRYMAN_LANTERN);
	public static final RegistryObject<Item> FERRYMAN_LANTERN_HANGED = block(TheDeepVoidModBlocks.FERRYMAN_LANTERN_HANGED);
	public static final RegistryObject<Item> ONYX_ARMOR_HELMET = REGISTRY.register("onyx_armor_helmet", () -> new OnyxArmorItem.Helmet());
	public static final RegistryObject<Item> ONYX_ARMOR_CHESTPLATE = REGISTRY.register("onyx_armor_chestplate", () -> new OnyxArmorItem.Chestplate());
	public static final RegistryObject<Item> ONYX_ARMOR_LEGGINGS = REGISTRY.register("onyx_armor_leggings", () -> new OnyxArmorItem.Leggings());
	public static final RegistryObject<Item> ONYX_ARMOR_BOOTS = REGISTRY.register("onyx_armor_boots", () -> new OnyxArmorItem.Boots());
	public static final RegistryObject<Item> VOID_PENDANT = REGISTRY.register("void_pendant", () -> new VoidPendantItem());
	public static final RegistryObject<Item> FORGOTTEN_TOKEN = REGISTRY.register("forgotten_token", () -> new ForgottenTokenItem());
	public static final RegistryObject<Item> ONYX_SWORD = REGISTRY.register("onyx_sword", () -> new OnyxSwordItem());
	public static final RegistryObject<Item> ONYX_PICKAXE = REGISTRY.register("onyx_pickaxe", () -> new OnyxPickaxeItem());
	public static final RegistryObject<Item> ONYX_AXE = REGISTRY.register("onyx_axe", () -> new OnyxAxeItem());
	public static final RegistryObject<Item> ONYX_SHOVEL = REGISTRY.register("onyx_shovel", () -> new OnyxShovelItem());
	public static final RegistryObject<Item> ONYX_HOE = REGISTRY.register("onyx_hoe", () -> new OnyxHoeItem());
	public static final RegistryObject<Item> BLOCK_OF_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_ONYX);
	public static final RegistryObject<Item> VOID_DAGGER = REGISTRY.register("void_dagger", () -> new VoidDaggerItem());
	public static final RegistryObject<Item> OFF_HAND_VOID_DAGGER = REGISTRY.register("off_hand_void_dagger", () -> new OffHandVoidDaggerItem());
	public static final RegistryObject<Item> STALKER_TREAT = REGISTRY.register("stalker_treat", () -> new StalkerTreatItem());
	public static final RegistryObject<Item> REFINED_ONYX = REGISTRY.register("refined_onyx", () -> new RefinedOnyxItem());
	public static final RegistryObject<Item> BONE_BALL = REGISTRY.register("bone_ball", () -> new BoneBallItem());
	public static final RegistryObject<Item> CAVE_GROWTH = block(TheDeepVoidModBlocks.CAVE_GROWTH);
	public static final RegistryObject<Item> VOID_CORE = block(TheDeepVoidModBlocks.VOID_CORE);
	public static final RegistryObject<Item> ANCIENT_BOOKSHELF = block(TheDeepVoidModBlocks.ANCIENT_BOOKSHELF);
	public static final RegistryObject<Item> CUT_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK);
	public static final RegistryObject<Item> CUT_ROTTEN_BONE_BLOCK_STAIRS = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK_STAIRS);
	public static final RegistryObject<Item> CUT_ROTTEN_BONE_BLOCK_SLAB = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK_SLAB);
	public static final RegistryObject<Item> CHISELED_CUT_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.CHISELED_CUT_ROTTEN_BONE_BLOCK);
	public static final RegistryObject<Item> ROTTEN_LOG = block(TheDeepVoidModBlocks.ROTTEN_LOG);
	public static final RegistryObject<Item> ROTTEN_WOOD = block(TheDeepVoidModBlocks.ROTTEN_WOOD);
	public static final RegistryObject<Item> GLUTTON_BLOCK = block(TheDeepVoidModBlocks.GLUTTON_BLOCK);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE);
	public static final RegistryObject<Item> ROTTEN_DART = REGISTRY.register("rotten_dart", () -> new RottenDartItem());
	public static final RegistryObject<Item> LAVENDITE = REGISTRY.register("lavendite", () -> new LavenditeItem());
	public static final RegistryObject<Item> LAVENDITE_ORE = block(TheDeepVoidModBlocks.LAVENDITE_ORE);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_STAIRS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_STAIRS);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_SLAB = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_SLAB);
	public static final RegistryObject<Item> SMITHING_TEMPLATE_LAVENDITE = REGISTRY.register("smithing_template_lavendite", () -> new SmithingTemplateLavenditeItem());
	public static final RegistryObject<Item> LAVENDITE_IRON_SWORD = REGISTRY.register("lavendite_iron_sword", () -> new LavenditeIronSwordItem());
	public static final RegistryObject<Item> LAVENDITE_DIAMOND_SWORD = REGISTRY.register("lavendite_diamond_sword", () -> new LavenditeDiamondSwordItem());
	public static final RegistryObject<Item> LAVENDITE_NETHERITE_SWORD = REGISTRY.register("lavendite_netherite_sword", () -> new LavenditeNetheriteSwordItem());
	public static final RegistryObject<Item> LAVENDITE_ONYX_SWORD = REGISTRY.register("lavendite_onyx_sword", () -> new LavenditeOnyxSwordItem());
	public static final RegistryObject<Item> LAVENDITE_BONE_SWORD = REGISTRY.register("lavendite_bone_sword", () -> new LavenditeBoneSwordItem());
	public static final RegistryObject<Item> LAVENDITE_GOLDEN_SWORD = REGISTRY.register("lavendite_golden_sword", () -> new LavenditeGoldenSwordItem());
	public static final RegistryObject<Item> LAVENDITE_STONE_SWORD = REGISTRY.register("lavendite_stone_sword", () -> new LavenditeStoneSwordItem());
	public static final RegistryObject<Item> LAVENDITE_WOODEN_SWORD = REGISTRY.register("lavendite_wooden_sword", () -> new LavenditeWoodenSwordItem());
	public static final RegistryObject<Item> LAVENDITE_SHIELD = REGISTRY.register("lavendite_shield", () -> new LavenditeShieldItem());
	public static final RegistryObject<Item> BLOCK_OF_LAVENDITE = block(TheDeepVoidModBlocks.BLOCK_OF_LAVENDITE);
	public static final RegistryObject<Item> SMITHING_TEMPLATE_ROT = REGISTRY.register("smithing_template_rot", () -> new SmithingTemplateRotItem());
	public static final RegistryObject<Item> ROTTEN_WOODEN_SWORD = REGISTRY.register("rotten_wooden_sword", () -> new RottenWoodenSwordItem());
	public static final RegistryObject<Item> ROTTEN_STONE_SWORD = REGISTRY.register("rotten_stone_sword", () -> new RottenStoneSwordItem());
	public static final RegistryObject<Item> ROTTEN_GOLDEN_SWORD = REGISTRY.register("rotten_golden_sword", () -> new RottenGoldenSwordItem());
	public static final RegistryObject<Item> ROTTEN_IRON_SWORD = REGISTRY.register("rotten_iron_sword", () -> new RottenIronSwordItem());
	public static final RegistryObject<Item> ROTTEN_DIAMOND_SWORD = REGISTRY.register("rotten_diamond_sword", () -> new RottenDiamondSwordItem());
	public static final RegistryObject<Item> ROTTEN_NETHERITE_SWORD = REGISTRY.register("rotten_netherite_sword", () -> new RottenNetheriteSwordItem());
	public static final RegistryObject<Item> ONYX_NEEDLE = REGISTRY.register("onyx_needle", () -> new OnyxNeedleItem());
	public static final RegistryObject<Item> LICKER_HOOK = REGISTRY.register("licker_hook", () -> new LickerHookItem());
	public static final RegistryObject<Item> BLOODY_TONGUE = REGISTRY.register("bloody_tongue", () -> new BloodyTongueItem());
	public static final RegistryObject<Item> ROTTEN_TONGUE_HOOK = REGISTRY.register("rotten_tongue_hook", () -> new RottenTongueHookItem());
	public static final RegistryObject<Item> VOID_CLOAK_CHESTPLATE = REGISTRY.register("void_cloak_chestplate", () -> new VoidCloakItem.Chestplate());
	public static final RegistryObject<Item> VOID_MATTER = REGISTRY.register("void_matter", () -> new VoidMatterItem());
	public static final RegistryObject<Item> BONE_CAVE_AIR = block(TheDeepVoidModBlocks.BONE_CAVE_AIR);
	public static final RegistryObject<Item> HANGING_MARROW = block(TheDeepVoidModBlocks.HANGING_MARROW);
	public static final RegistryObject<Item> FLESH_BLOCK = block(TheDeepVoidModBlocks.FLESH_BLOCK);
	public static final RegistryObject<Item> PUSTULENT_FLESH_BLOCK = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BLOCK);
	public static final RegistryObject<Item> PUS_FLOWER = block(TheDeepVoidModBlocks.PUS_FLOWER);
	public static final RegistryObject<Item> TENDRILS = block(TheDeepVoidModBlocks.TENDRILS);
	public static final RegistryObject<Item> TEETH = block(TheDeepVoidModBlocks.TEETH);
	public static final RegistryObject<Item> FLESH_CAVE_AIR = block(TheDeepVoidModBlocks.FLESH_CAVE_AIR);
	public static final RegistryObject<Item> EYE_VINE_STEM = block(TheDeepVoidModBlocks.EYE_VINE_STEM);
	public static final RegistryObject<Item> EYE_VINE = block(TheDeepVoidModBlocks.EYE_VINE);
	public static final RegistryObject<Item> PUS_SACK = block(TheDeepVoidModBlocks.PUS_SACK);
	public static final RegistryObject<Item> GREEN_EYE_VINE = block(TheDeepVoidModBlocks.GREEN_EYE_VINE);
	public static final RegistryObject<Item> RED_EYE_VINE = block(TheDeepVoidModBlocks.RED_EYE_VINE);
	public static final RegistryObject<Item> YELLOW_EYE_VINE = block(TheDeepVoidModBlocks.YELLOW_EYE_VINE);
	public static final RegistryObject<Item> PUS_BALL = REGISTRY.register("pus_ball", () -> new PusBallItem());
	public static final RegistryObject<Item> DESOLATE_SOIL = block(TheDeepVoidModBlocks.DESOLATE_SOIL);
	public static final RegistryObject<Item> DESOLATE_GROWTH = block(TheDeepVoidModBlocks.DESOLATE_GROWTH);
	public static final RegistryObject<Item> DESOLATE_STEM = block(TheDeepVoidModBlocks.DESOLATE_STEM);
	public static final RegistryObject<Item> VOIDLIGHT = block(TheDeepVoidModBlocks.VOIDLIGHT);
	public static final RegistryObject<Item> DESOLATE_CAVE_AIR = block(TheDeepVoidModBlocks.DESOLATE_CAVE_AIR);
	public static final RegistryObject<Item> DESOLATE_LICHEN = block(TheDeepVoidModBlocks.DESOLATE_LICHEN);
	public static final RegistryObject<Item> VOID_LENS = REGISTRY.register("void_lens", () -> new VoidLensItem());
	public static final RegistryObject<Item> SPYGLASS_DUMMY = REGISTRY.register("spyglass_dummy", () -> new SpyglassDummyItem());
	public static final RegistryObject<Item> GRIM_SHARD = REGISTRY.register("grim_shard", () -> new GrimShardItem());
	public static final RegistryObject<Item> GRIM_GEM = REGISTRY.register("grim_gem", () -> new GrimGemItem());
	public static final RegistryObject<Item> GRIM_ROTTEN_BONE_HELMET = REGISTRY.register("grim_rotten_bone_helmet", () -> new GrimRottenBoneItem.Helmet());
	public static final RegistryObject<Item> GRIM_ROTTEN_BONE_CHESTPLATE = REGISTRY.register("grim_rotten_bone_chestplate", () -> new GrimRottenBoneItem.Chestplate());
	public static final RegistryObject<Item> GRIM_ROTTEN_BONE_LEGGINGS = REGISTRY.register("grim_rotten_bone_leggings", () -> new GrimRottenBoneItem.Leggings());
	public static final RegistryObject<Item> GRIM_ROTTEN_BONE_BOOTS = REGISTRY.register("grim_rotten_bone_boots", () -> new GrimRottenBoneItem.Boots());
	public static final RegistryObject<Item> SMITHING_TEMPLATE_GRIM = REGISTRY.register("smithing_template_grim", () -> new SmithingTemplateGrimItem());
	public static final RegistryObject<Item> GRIM_SCYTHE = REGISTRY.register("grim_scythe", () -> new GrimScytheItem());
	public static final RegistryObject<Item> EYE_SHIELD = REGISTRY.register("eye_shield", () -> new EyeShieldItem());
	public static final RegistryObject<Item> REINFORCED_PICKAXE = REGISTRY.register("reinforced_pickaxe", () -> new ReinforcedPickaxeItem());
	public static final RegistryObject<Item> CRACKED_BEDROCK = block(TheDeepVoidModBlocks.CRACKED_BEDROCK);
	public static final RegistryObject<Item> DEEPSLATE_SERRATED_STALAGMITE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE);
	public static final RegistryObject<Item> DEEPSLATE_SERRATED_STALAGMITE_BASE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_BASE);
	public static final RegistryObject<Item> DEEPSLATE_SERRATED_STALAGMITE_MIDDLE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_MIDDLE);
	public static final RegistryObject<Item> DEEPSLATE_SERRATED_STALAGMITE_FRUSTUM = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_FRUSTUM);
	public static final RegistryObject<Item> BLACK_MOSS = REGISTRY.register("black_moss", () -> new BlackMossItem());
	public static final RegistryObject<Item> LIQUID_VOID_BUCKET = REGISTRY.register("liquid_void_bucket", () -> new LiquidVoidItem());
	public static final RegistryObject<Item> VOID_FILLED_SPONGE = block(TheDeepVoidModBlocks.VOID_FILLED_SPONGE);
	public static final RegistryObject<Item> ONYX_FLARE_GUN = REGISTRY.register("onyx_flare_gun", () -> new OnyxFlareGunItem());
	public static final RegistryObject<Item> LAVENDITE_ARMOR_HELMET = REGISTRY.register("lavendite_armor_helmet", () -> new LavenditeArmorItem.Helmet());
	public static final RegistryObject<Item> LAVENDITE_ARMOR_CHESTPLATE = REGISTRY.register("lavendite_armor_chestplate", () -> new LavenditeArmorItem.Chestplate());
	public static final RegistryObject<Item> LAVENDITE_ARMOR_LEGGINGS = REGISTRY.register("lavendite_armor_leggings", () -> new LavenditeArmorItem.Leggings());
	public static final RegistryObject<Item> LAVENDITE_ARMOR_BOOTS = REGISTRY.register("lavendite_armor_boots", () -> new LavenditeArmorItem.Boots());
	public static final RegistryObject<Item> LAVENDITE_SHARD = REGISTRY.register("lavendite_shard", () -> new LavenditeShardItem());
	public static final RegistryObject<Item> LAVENDITE_SWORD = REGISTRY.register("lavendite_sword", () -> new LavenditeSwordItem());
	public static final RegistryObject<Item> DEEPSLATE_SARCOPHAGUS = block(TheDeepVoidModBlocks.DEEPSLATE_SARCOPHAGUS);
	public static final RegistryObject<Item> LURKING_MUSIC_DISC = REGISTRY.register("lurking_music_disc", () -> new LurkingMusicDiscItem());
	public static final RegistryObject<Item> SCARE_ARMOR_TRIM = REGISTRY.register("scare_armor_trim", () -> new ScareArmorTrimItem());
	public static final RegistryObject<Item> SCAVENGER_ARMOR_TRIM = REGISTRY.register("scavenger_armor_trim", () -> new ScavengerArmorTrimItem());
	public static final RegistryObject<Item> DEVOURER_TENDRIL = REGISTRY.register("devourer_tendril", () -> new DevourerTendrilItem());
	public static final RegistryObject<Item> DEVOURER_SHIELD = REGISTRY.register("devourer_shield", () -> new DevourerShieldItem());
	public static final RegistryObject<Item> DEVOURER_HOOK = REGISTRY.register("devourer_hook", () -> new DevourerHookItem());
	public static final RegistryObject<Item> LAVENDITE_DEVOURER_HOOK = REGISTRY.register("lavendite_devourer_hook", () -> new LavenditeDevourerHookItem());
	public static final RegistryObject<Item> CHASMS_MUSIC_DISC = REGISTRY.register("chasms_music_disc", () -> new ChasmsMusicDiscItem());
	public static final RegistryObject<Item> AMALGAM_SPAWN_EGG = REGISTRY.register("amalgam_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.AMALGAM, -13234674, -5396066, new Item.Properties()));
	public static final RegistryObject<Item> VOID_CAVE_AIR = block(TheDeepVoidModBlocks.VOID_CAVE_AIR);
	public static final RegistryObject<Item> VOID_ROOTS = block(TheDeepVoidModBlocks.VOID_ROOTS);
	public static final RegistryObject<Item> VOID_ROSE = block(TheDeepVoidModBlocks.VOID_ROSE);
	public static final RegistryObject<Item> VOID_FERN = block(TheDeepVoidModBlocks.VOID_FERN);
	public static final RegistryObject<Item> FORBIDDEN_TOME = REGISTRY.register("forbidden_tome", () -> new ForbiddenTomeItem());
	public static final RegistryObject<Item> ROTTEN_PLANKS = block(TheDeepVoidModBlocks.ROTTEN_PLANKS);
	public static final RegistryObject<Item> ROTTEN_STAIRS = block(TheDeepVoidModBlocks.ROTTEN_STAIRS);
	public static final RegistryObject<Item> ROTTEN_SLAB = block(TheDeepVoidModBlocks.ROTTEN_SLAB);
	public static final RegistryObject<Item> FLESH_BRICKS = block(TheDeepVoidModBlocks.FLESH_BRICKS);
	public static final RegistryObject<Item> FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.FLESH_BRICK_STAIRS);
	public static final RegistryObject<Item> FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.FLESH_BRICK_SLAB);
	public static final RegistryObject<Item> PUSTULENT_FLESH_BRICKS = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICKS);
	public static final RegistryObject<Item> ROTTEN_DOOR = doubleBlock(TheDeepVoidModBlocks.ROTTEN_DOOR);
	public static final RegistryObject<Item> ROTTEN_TRAPDOOR = block(TheDeepVoidModBlocks.ROTTEN_TRAPDOOR);
	public static final RegistryObject<Item> WALL_CORPSE = block(TheDeepVoidModBlocks.WALL_CORPSE);
	public static final RegistryObject<Item> CANOPY_ROTTEN_GRASS = doubleBlock(TheDeepVoidModBlocks.CANOPY_ROTTEN_GRASS);
	public static final RegistryObject<Item> CANOPY_BONE_MARROW = block(TheDeepVoidModBlocks.CANOPY_BONE_MARROW);
	public static final RegistryObject<Item> ASH_PILE = block(TheDeepVoidModBlocks.ASH_PILE);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_BRICKS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICKS);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_BRICK_STAIRS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_STAIRS);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_BRICK_SLAB = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_SLAB);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_WALL = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_WALL);
	public static final RegistryObject<Item> ANCIENT_DEEPSLATE_BRICK_WALL = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_WALL);
	public static final RegistryObject<Item> COBBLED_ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.COBBLED_ANCIENT_DEEPSLATE);
	public static final RegistryObject<Item> SMOOTH_ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE);
	public static final RegistryObject<Item> SMOOTH_ANCIENT_DEEPSLATE_SLAB = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE_SLAB);
	public static final RegistryObject<Item> PUSTULENT_FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICK_STAIRS);
	public static final RegistryObject<Item> PUSTULENT_FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICK_SLAB);
	public static final RegistryObject<Item> DESOLATE_BRICKS = block(TheDeepVoidModBlocks.DESOLATE_BRICKS);
	public static final RegistryObject<Item> DESOLATE_BRICK_STAIRS = block(TheDeepVoidModBlocks.DESOLATE_BRICK_STAIRS);
	public static final RegistryObject<Item> DESOLATE_BRICK_SLAB = block(TheDeepVoidModBlocks.DESOLATE_BRICK_SLAB);
	public static final RegistryObject<Item> FLESH_BRICK_WALL = block(TheDeepVoidModBlocks.FLESH_BRICK_WALL);
	public static final RegistryObject<Item> DESOLATE_BRICK_WALL = block(TheDeepVoidModBlocks.DESOLATE_BRICK_WALL);
	public static final RegistryObject<Item> BISMUTH = REGISTRY.register("bismuth", () -> new BismuthItem());
	public static final RegistryObject<Item> REFINED_BISMUTH = REGISTRY.register("refined_bismuth", () -> new RefinedBismuthItem());
	public static final RegistryObject<Item> BISMUTH_ORE = block(TheDeepVoidModBlocks.BISMUTH_ORE);
	public static final RegistryObject<Item> BISMUTH_NETHERITE_HELMET = REGISTRY.register("bismuth_netherite_helmet", () -> new BismuthNetheriteItem.Helmet());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_CHESTPLATE = REGISTRY.register("bismuth_netherite_chestplate", () -> new BismuthNetheriteItem.Chestplate());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_LEGGINGS = REGISTRY.register("bismuth_netherite_leggings", () -> new BismuthNetheriteItem.Leggings());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_BOOTS = REGISTRY.register("bismuth_netherite_boots", () -> new BismuthNetheriteItem.Boots());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_SWORD = REGISTRY.register("bismuth_netherite_sword", () -> new BismuthNetheriteSwordItem());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_PICKAXE = REGISTRY.register("bismuth_netherite_pickaxe", () -> new BismuthNetheritePickaxeItem());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_AXE = REGISTRY.register("bismuth_netherite_axe", () -> new BismuthNetheriteAxeItem());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_SHOVEL = REGISTRY.register("bismuth_netherite_shovel", () -> new BismuthNetheriteShovelItem());
	public static final RegistryObject<Item> BISMUTH_NETHERITE_HOE = REGISTRY.register("bismuth_netherite_hoe", () -> new BismuthNetheriteHoeItem());
	public static final RegistryObject<Item> TEETH_TRAP = block(TheDeepVoidModBlocks.TEETH_TRAP);
	public static final RegistryObject<Item> TEETH_BLOCK = block(TheDeepVoidModBlocks.TEETH_BLOCK);
	public static final RegistryObject<Item> ASH_BLOCK = block(TheDeepVoidModBlocks.ASH_BLOCK);
	public static final RegistryObject<Item> CORPSE_SPAWN_GRAVEYARD = block(TheDeepVoidModBlocks.CORPSE_SPAWN_GRAVEYARD);
	public static final RegistryObject<Item> EYE_LANTERN = block(TheDeepVoidModBlocks.EYE_LANTERN);
	public static final RegistryObject<Item> EYE_LANTERN_HANGED = block(TheDeepVoidModBlocks.EYE_LANTERN_HANGED);
	public static final RegistryObject<Item> BLOCK_OF_BISMUTH = block(TheDeepVoidModBlocks.BLOCK_OF_BISMUTH);
	public static final RegistryObject<Item> BLOCK_OF_REFINED_BISMUTH = block(TheDeepVoidModBlocks.BLOCK_OF_REFINED_BISMUTH);
	public static final RegistryObject<Item> ROTTEN_SICKLE = REGISTRY.register("rotten_sickle", () -> new ReapingHookItem());
	public static final RegistryObject<Item> ROTTEN_FOSSIL = block(TheDeepVoidModBlocks.ROTTEN_FOSSIL);
	public static final RegistryObject<Item> SMOKE_VENT = block(TheDeepVoidModBlocks.SMOKE_VENT);
	public static final RegistryObject<Item> BISMUTH_LANTERN = block(TheDeepVoidModBlocks.BISMUTH_LANTERN);
	public static final RegistryObject<Item> BISMUTH_LANTERN_HANGED = block(TheDeepVoidModBlocks.BISMUTH_LANTERN_HANGED);
	public static final RegistryObject<Item> ROTTEN_MOSS = block(TheDeepVoidModBlocks.ROTTEN_MOSS);
	public static final RegistryObject<Item> BISMUTH_GLASS = block(TheDeepVoidModBlocks.BISMUTH_GLASS);
	public static final RegistryObject<Item> CONNECTED_MARROW = block(TheDeepVoidModBlocks.CONNECTED_MARROW);
	public static final RegistryObject<Item> SULFUR = REGISTRY.register("sulfur", () -> new SulfurItem());
	public static final RegistryObject<Item> SULFUR_ORE = block(TheDeepVoidModBlocks.SULFUR_ORE);
	public static final RegistryObject<Item> SULFUR_TNT = block(TheDeepVoidModBlocks.SULFUR_TNT);
	public static final RegistryObject<Item> SULFUR_POWDER = block(TheDeepVoidModBlocks.SULFUR_POWDER);
	public static final RegistryObject<Item> BLOCK_OF_SULFUR = block(TheDeepVoidModBlocks.BLOCK_OF_SULFUR);
	public static final RegistryObject<Item> BLUE_FIRE = block(TheDeepVoidModBlocks.BLUE_FIRE);
	public static final RegistryObject<Item> BLOCK_OF_RAW_SULFUR = block(TheDeepVoidModBlocks.BLOCK_OF_RAW_SULFUR);
	public static final RegistryObject<Item> SULFUR_GLASS = block(TheDeepVoidModBlocks.SULFUR_GLASS);
	public static final RegistryObject<Item> SULFUR_LANTERN = block(TheDeepVoidModBlocks.SULFUR_LANTERN);
	public static final RegistryObject<Item> SULFUR_LANTERN_HANGING = block(TheDeepVoidModBlocks.SULFUR_LANTERN_HANGING);
	public static final RegistryObject<Item> INFESTED_ROTTEN_LOG = block(TheDeepVoidModBlocks.INFESTED_ROTTEN_LOG);
	public static final RegistryObject<Item> WATCHING_WILLOW_SAPLING = block(TheDeepVoidModBlocks.WATCHING_WILLOW_SAPLING);
	public static final RegistryObject<Item> VOIDRIUM_ORE = block(TheDeepVoidModBlocks.VOIDRIUM_ORE);
	public static final RegistryObject<Item> VOIDRIUM_GEM = REGISTRY.register("voidrium_gem", () -> new UmbriumGemItem());
	public static final RegistryObject<Item> BLOCK_OF_VOIDRIUM = block(TheDeepVoidModBlocks.BLOCK_OF_VOIDRIUM);
	public static final RegistryObject<Item> VOIDRIUM_HELMET = REGISTRY.register("voidrium_helmet", () -> new VoidriumItem.Helmet());
	public static final RegistryObject<Item> VOIDRIUM_CHESTPLATE = REGISTRY.register("voidrium_chestplate", () -> new VoidriumItem.Chestplate());
	public static final RegistryObject<Item> VOIDRIUM_LEGGINGS = REGISTRY.register("voidrium_leggings", () -> new VoidriumItem.Leggings());
	public static final RegistryObject<Item> VOIDRIUM_BOOTS = REGISTRY.register("voidrium_boots", () -> new VoidriumItem.Boots());
	public static final RegistryObject<Item> GRIM_BLOCK = block(TheDeepVoidModBlocks.GRIM_BLOCK);
	public static final RegistryObject<Item> VOIDRIUM_SWORD = REGISTRY.register("voidrium_sword", () -> new VoidriumSwordItem());
	public static final RegistryObject<Item> LAVENDITE_VOIDRIUM_SWORD = REGISTRY.register("lavendite_voidrium_sword", () -> new LavenditeVoidriumSwordItem());
	public static final RegistryObject<Item> VOIDRIUM_PICKAXE = REGISTRY.register("voidrium_pickaxe", () -> new VoidriumPickaxeItem());
	public static final RegistryObject<Item> VOIDRIUM_AXE = REGISTRY.register("voidrium_axe", () -> new VoidriumAxeItem());
	public static final RegistryObject<Item> VOIDRIUM_SHOVEL = REGISTRY.register("voidrium_shovel", () -> new VoidriumShovelItem());
	public static final RegistryObject<Item> VOIDRIUM_HOE = REGISTRY.register("voidrium_hoe", () -> new VoidriumHoeItem());
	public static final RegistryObject<Item> BIG_TEETH = block(TheDeepVoidModBlocks.BIG_TEETH);
	public static final RegistryObject<Item> TEETH_TRAP_BLOCK = block(TheDeepVoidModBlocks.TEETH_TRAP_BLOCK);
	public static final RegistryObject<Item> PEEPING_ROOTS = block(TheDeepVoidModBlocks.PEEPING_ROOTS);
	public static final RegistryObject<Item> INACTIVE_PEEPING_ROOTS = block(TheDeepVoidModBlocks.INACTIVE_PEEPING_ROOTS);
	public static final RegistryObject<Item> PILE_OF_BONES_BLOCK = block(TheDeepVoidModBlocks.PILE_OF_BONES_BLOCK);
	public static final RegistryObject<Item> FLESHY_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_BONE_BLOCK);
	public static final RegistryObject<Item> HARD_FLESH_BLOCK = block(TheDeepVoidModBlocks.HARD_FLESH_BLOCK);
	public static final RegistryObject<Item> HARD_FLESH_STAIRS = block(TheDeepVoidModBlocks.HARD_FLESH_STAIRS);
	public static final RegistryObject<Item> HARD_FLESH_SLAB = block(TheDeepVoidModBlocks.HARD_FLESH_SLAB);
	public static final RegistryObject<Item> CRACKED_BEDROCK_STAIRS = block(TheDeepVoidModBlocks.CRACKED_BEDROCK_STAIRS);
	public static final RegistryObject<Item> CRACKED_BEDROCK_SLAB = block(TheDeepVoidModBlocks.CRACKED_BEDROCK_SLAB);
	public static final RegistryObject<Item> FAKE_BEDROCK = block(TheDeepVoidModBlocks.FAKE_BEDROCK);
	public static final RegistryObject<Item> FAKE_BEDROCK_STAIRS = block(TheDeepVoidModBlocks.FAKE_BEDROCK_STAIRS);
	public static final RegistryObject<Item> FAKE_BEDROCK_SLAB = block(TheDeepVoidModBlocks.FAKE_BEDROCK_SLAB);
	public static final RegistryObject<Item> GORE_STEMS = block(TheDeepVoidModBlocks.GORE_STEMS);
	public static final RegistryObject<Item> GROUND_BONES = block(TheDeepVoidModBlocks.GROUND_BONES);
	public static final RegistryObject<Item> GROUND_BONES_PLANT = block(TheDeepVoidModBlocks.GROUND_BONES_PLANT);
	public static final RegistryObject<Item> FOSSILIZED_FLESH = block(TheDeepVoidModBlocks.FOSSILIZED_FLESH);
	public static final RegistryObject<Item> FLESH_CHUNK = REGISTRY.register("flesh_chunk", () -> new FleshChunkItem());
	public static final RegistryObject<Item> FLESH_ARMOR_HELMET = REGISTRY.register("flesh_armor_helmet", () -> new FleshArmorItem.Helmet());
	public static final RegistryObject<Item> FLESH_ARMOR_CHESTPLATE = REGISTRY.register("flesh_armor_chestplate", () -> new FleshArmorItem.Chestplate());
	public static final RegistryObject<Item> FLESH_ARMOR_LEGGINGS = REGISTRY.register("flesh_armor_leggings", () -> new FleshArmorItem.Leggings());
	public static final RegistryObject<Item> FLESH_ARMOR_BOOTS = REGISTRY.register("flesh_armor_boots", () -> new FleshArmorItem.Boots());
	public static final RegistryObject<Item> HARD_FLESH_INGOT = REGISTRY.register("hard_flesh_ingot", () -> new HardFleshIngotItem());
	public static final RegistryObject<Item> GRAVEDIGGER_SHOVEL = REGISTRY.register("gravedigger_shovel", () -> new GravediggerShovelItem());
	public static final RegistryObject<Item> HARD_FLESH_SWORD = REGISTRY.register("hard_flesh_sword", () -> new HardFleshSwordItem());
	public static final RegistryObject<Item> BONE_PILE_BRICKS = block(TheDeepVoidModBlocks.BONE_PILE_BRICKS);
	public static final RegistryObject<Item> BONE_PILE_BRICK_STAIRS = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_STAIRS);
	public static final RegistryObject<Item> BONE_PILE_BRICK_SLAB = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_SLAB);
	public static final RegistryObject<Item> BONE_PILE_BRICK_WALL = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_WALL);
	public static final RegistryObject<Item> COMPACT_BONE_PILE = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE);
	public static final RegistryObject<Item> COMPACT_BONE_PILE_STAIRS = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE_STAIRS);
	public static final RegistryObject<Item> COMPACT_BONE_PILE_SLAB = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE_SLAB);
	public static final RegistryObject<Item> AMBROSIA = REGISTRY.register("ambrosia", () -> new AmbrosiaItem());
	public static final RegistryObject<Item> BISMUTH_GLASS_PANE = block(TheDeepVoidModBlocks.BISMUTH_GLASS_PANE);
	public static final RegistryObject<Item> SULFUR_GLASS_PANE = block(TheDeepVoidModBlocks.SULFUR_GLASS_PANE);
	public static final RegistryObject<Item> ASHEN_VOID_FERN = block(TheDeepVoidModBlocks.ASHEN_VOID_FERN);
	public static final RegistryObject<Item> DEEPSLATE_SARCOPHAGUS_BLOCK = block(TheDeepVoidModBlocks.DEEPSLATE_SARCOPHAGUS_BLOCK);
	public static final RegistryObject<Item> SMOOTH_ANCIENT_DEEPSLATE_STAIRS = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE_STAIRS);
	public static final RegistryObject<Item> ASH_BRICKS = block(TheDeepVoidModBlocks.ASH_BRICKS);
	public static final RegistryObject<Item> ASH_BRICK_STAIRS = block(TheDeepVoidModBlocks.ASH_BRICK_STAIRS);
	public static final RegistryObject<Item> ASH_BRICK_SLAB = block(TheDeepVoidModBlocks.ASH_BRICK_SLAB);
	public static final RegistryObject<Item> ASH_BRICK_WALL = block(TheDeepVoidModBlocks.ASH_BRICK_WALL);
	public static final RegistryObject<Item> DEEPSLATE_LAVA_GEYSER = block(TheDeepVoidModBlocks.DEEPSLATE_LAVA_GEYSER);
	public static final RegistryObject<Item> ASHEN_CAVE_AIR = block(TheDeepVoidModBlocks.ASHEN_CAVE_AIR);
	public static final RegistryObject<Item> SORROW_ARMOR_TRIM = REGISTRY.register("sorrow_armor_trim", () -> new SorrowArmorTrimItem());
	public static final RegistryObject<Item> MONOLITHIC_STONE = block(TheDeepVoidModBlocks.MONOLITHIC_STONE);
	public static final RegistryObject<Item> SEER = block(TheDeepVoidModBlocks.SEER);
	public static final RegistryObject<Item> CINNABAR = REGISTRY.register("cinnabar", () -> new CinnabarItem());
	public static final RegistryObject<Item> REFINED_CINNABAR = REGISTRY.register("refined_cinnabar", () -> new RefinedCinnabarItem());
	public static final RegistryObject<Item> OVERSEER_PILLAR_SPAWN_EGG = REGISTRY.register("overseer_pillar_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.OVERSEER_PILLAR, -15460839, -14216943, new Item.Properties()));
	public static final RegistryObject<Item> CINNABAR_ORE = block(TheDeepVoidModBlocks.CINNABAR_ORE);
	public static final RegistryObject<Item> MONOLITHIC_STONE_STAIRS = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_STAIRS);
	public static final RegistryObject<Item> MONOLITHIC_STONE_SLAB = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_SLAB);
	public static final RegistryObject<Item> MONOLITHIC_STONE_WALL = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_WALL);
	public static final RegistryObject<Item> BLOCK_OF_CINNABAR = block(TheDeepVoidModBlocks.BLOCK_OF_CINNABAR);
	public static final RegistryObject<Item> MONOLITHIC_BRICKS = block(TheDeepVoidModBlocks.MONOLITHIC_BRICKS);
	public static final RegistryObject<Item> MONOLITHIC_BRICK_STAIRS = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_STAIRS);
	public static final RegistryObject<Item> MONOLITHIC_BRICK_SLAB = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_SLAB);
	public static final RegistryObject<Item> MONOLITHIC_BRICK_WALL = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_WALL);
	public static final RegistryObject<Item> CINNABAR_ROLL = REGISTRY.register("cinnabar_roll", () -> new CinnabarRollItem());
	public static final RegistryObject<Item> EYEBALL = REGISTRY.register("eyeball", () -> new EyeballItem());
	public static final RegistryObject<Item> BLOSSOMING_DESOLATE_LICHEN = block(TheDeepVoidModBlocks.BLOSSOMING_DESOLATE_LICHEN);
	public static final RegistryObject<Item> GRIMBERRY = REGISTRY.register("grimberry", () -> new GrimberryItem());
	public static final RegistryObject<Item> ALL_SEEING_PICKAXE = REGISTRY.register("all_seeing_pickaxe", () -> new AllSeeingPickaxeItem());
	public static final RegistryObject<Item> EYEBALL_SOUP = REGISTRY.register("eyeball_soup", () -> new EyeballSoupItem());
	public static final RegistryObject<Item> GRIMBERRY_JUICE = REGISTRY.register("grimberry_juice", () -> new GrimberryJuiceItem());
	public static final RegistryObject<Item> ALL_SEEING_AXE = REGISTRY.register("all_seeing_axe", () -> new AllSeeingAxeItem());
	public static final RegistryObject<Item> ALL_SEEING_SHOVEL = REGISTRY.register("all_seeing_shovel", () -> new AllSeeingShovelItem());
	public static final RegistryObject<Item> ALL_SEEING_HOE = REGISTRY.register("all_seeing_hoe", () -> new AllSeeingHoeItem());
	public static final RegistryObject<Item> ALL_SEEING_SWORD = REGISTRY.register("all_seeing_sword", () -> new AllSeeingSwordItem());
	public static final RegistryObject<Item> GRIMBERRY_PIE = REGISTRY.register("grimberry_pie", () -> new GrimberryPieItem());
	public static final RegistryObject<Item> LAVENDITE_ALL_SEEING_SWORD = REGISTRY.register("lavendite_all_seeing_sword", () -> new LavenditeAllSeeingSwordItem());
	public static final RegistryObject<Item> ROTTEN_ALL_SEEING_SWORD = REGISTRY.register("rotten_all_seeing_sword", () -> new RottenAllSeeingSwordItem());
	public static final RegistryObject<Item> ALL_SEEING_HELMET = REGISTRY.register("all_seeing_helmet", () -> new AllSeeingItem.Helmet());
	public static final RegistryObject<Item> ALL_SEEING_CHESTPLATE = REGISTRY.register("all_seeing_chestplate", () -> new AllSeeingItem.Chestplate());
	public static final RegistryObject<Item> ALL_SEEING_LEGGINGS = REGISTRY.register("all_seeing_leggings", () -> new AllSeeingItem.Leggings());
	public static final RegistryObject<Item> ALL_SEEING_BOOTS = REGISTRY.register("all_seeing_boots", () -> new AllSeeingItem.Boots());
	public static final RegistryObject<Item> SMOOTH_MONOLITHIC_STONE = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE);
	public static final RegistryObject<Item> SMOOTH_MONOLITHIC_STONE_STAIRS = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE_STAIRS);
	public static final RegistryObject<Item> SMOOTH_MONOLITHIC_STONE_SLAB = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE_SLAB);
	public static final RegistryObject<Item> TRANSFORMED_SEER = block(TheDeepVoidModBlocks.TRANSFORMED_SEER);
	public static final RegistryObject<Item> MADNESS_LANTERN = block(TheDeepVoidModBlocks.MADNESS_LANTERN);
	public static final RegistryObject<Item> MADNESS_LANTERN_HANGED = block(TheDeepVoidModBlocks.MADNESS_LANTERN_HANGED);
	public static final RegistryObject<Item> ROTTEN_FENCE = block(TheDeepVoidModBlocks.ROTTEN_FENCE);
	public static final RegistryObject<Item> ROTTEN_FENCE_GATE = block(TheDeepVoidModBlocks.ROTTEN_FENCE_GATE);
	public static final RegistryObject<Item> ROTTEN_PRESSURE_PLATE = block(TheDeepVoidModBlocks.ROTTEN_PRESSURE_PLATE);
	public static final RegistryObject<Item> ROTTEN_BUTTON = block(TheDeepVoidModBlocks.ROTTEN_BUTTON);
	public static final RegistryObject<Item> BLOCK_OF_ANCIENT_FLESH = block(TheDeepVoidModBlocks.BLOCK_OF_ANCIENT_FLESH);
	public static final RegistryObject<Item> CINNABAR_MONOLITH_STONE = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE);
	public static final RegistryObject<Item> CINNABAR_MONOLITH_STONE_STAIRS = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_STAIRS);
	public static final RegistryObject<Item> CINNABAR_MONOLITH_STONE_SLAB = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_SLAB);
	public static final RegistryObject<Item> CINNABAR_MONOLITH_STONE_WALL = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_WALL);
	public static final RegistryObject<Item> ATTRACTOR = block(TheDeepVoidModBlocks.ATTRACTOR);
	public static final RegistryObject<Item> ATTRACTOR_ON = block(TheDeepVoidModBlocks.ATTRACTOR_ON);
	public static final RegistryObject<Item> EYE_FLESH_BLOCK = block(TheDeepVoidModBlocks.EYE_FLESH_BLOCK);
	public static final RegistryObject<Item> ROUGH_VOIDRIUM = REGISTRY.register("rough_voidrium", () -> new RoughVoidriumItem());
	public static final RegistryObject<Item> EYE_FLESH_BRICKS = block(TheDeepVoidModBlocks.EYE_FLESH_BRICKS);
	public static final RegistryObject<Item> EYE_FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.EYE_FLESH_BRICK_STAIRS);
	public static final RegistryObject<Item> EYE_FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.EYE_FLESH_BRICK_SLAB);
	public static final RegistryObject<Item> PRIMORDIAL_STONE = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE);
	public static final RegistryObject<Item> PRIMORDIAL_STONE_REPLICA = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_REPLICA);
	public static final RegistryObject<Item> PRIMORDIAL_STONE_STAIRS = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_STAIRS);
	public static final RegistryObject<Item> PRIMORDIAL_STONE_SLAB = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_SLAB);
	public static final RegistryObject<Item> DISTURBING_ROOT = REGISTRY.register("disturbing_root", () -> new DisturbingRootItem());
	public static final RegistryObject<Item> ROOTER = block(TheDeepVoidModBlocks.ROOTER);
	public static final RegistryObject<Item> ROOTER_ON = block(TheDeepVoidModBlocks.ROOTER_ON);
	public static final RegistryObject<Item> SHORT_CIRCUIT_ROOTER = block(TheDeepVoidModBlocks.SHORT_CIRCUIT_ROOTER);
	public static final RegistryObject<Item> INFESTED_ROTTEN_ROOTS = block(TheDeepVoidModBlocks.INFESTED_ROTTEN_ROOTS);
	public static final RegistryObject<Item> INACTIVE_INFESTED_ROTTEN_ROOTS = block(TheDeepVoidModBlocks.INACTIVE_INFESTED_ROTTEN_ROOTS);
	public static final RegistryObject<Item> CHISELED_ANCIENT_DEEPSLATE_BRICKS = block(TheDeepVoidModBlocks.CHISELED_ANCIENT_DEEPSLATE_BRICKS);
	public static final RegistryObject<Item> CHISELED_DESOLATE_BRICKS = block(TheDeepVoidModBlocks.CHISELED_DESOLATE_BRICKS);
	public static final RegistryObject<Item> ROTTEN_ROOTS = block(TheDeepVoidModBlocks.ROTTEN_ROOTS);
	public static final RegistryObject<Item> POWERED_LAVA_GEYSER = block(TheDeepVoidModBlocks.POWERED_LAVA_GEYSER);
	public static final RegistryObject<Item> POWERED_LAVA_GEYSER_ON = block(TheDeepVoidModBlocks.POWERED_LAVA_GEYSER_ON);
	public static final RegistryObject<Item> CRUMBLING_DEEPSLATE = block(TheDeepVoidModBlocks.CRUMBLING_DEEPSLATE);
	public static final RegistryObject<Item> CRUMBLING_BEDROCK = block(TheDeepVoidModBlocks.CRUMBLING_BEDROCK);
	public static final RegistryObject<Item> COVERED_CORPSE = block(TheDeepVoidModBlocks.COVERED_CORPSE);
	public static final RegistryObject<Item> COVERED_CORPSE_SPAWN = block(TheDeepVoidModBlocks.COVERED_CORPSE_SPAWN);
	public static final RegistryObject<Item> CORPSE_CHANDELIER = block(TheDeepVoidModBlocks.CORPSE_CHANDELIER);
	public static final RegistryObject<Item> JACK_O_CORPSE = block(TheDeepVoidModBlocks.JACK_O_CORPSE);
	public static final RegistryObject<Item> JACK_O_COVERED_CORPSE = block(TheDeepVoidModBlocks.JACK_O_COVERED_CORPSE);
	public static final RegistryObject<Item> JACK_O_WALL_CORPSE = block(TheDeepVoidModBlocks.JACK_O_WALL_CORPSE);
	public static final RegistryObject<Item> ROOTING_TOME = REGISTRY.register("rooting_tome", () -> new RootingTomeItem());
	public static final RegistryObject<Item> GRIM_SICKLE = REGISTRY.register("grim_sickle", () -> new GrimSickleItem());
	public static final RegistryObject<Item> LURKER_HEAD = block(TheDeepVoidModBlocks.LURKER_HEAD);
	public static final RegistryObject<Item> VOIDLIGHT_BRICKS = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICKS);
	public static final RegistryObject<Item> VOIDLIGHT_BRICK_STAIRS = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_STAIRS);
	public static final RegistryObject<Item> VOIDLIGHT_BRICK_SLAB = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_SLAB);
	public static final RegistryObject<Item> VOIDLIGHT_BRICK_WALL = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_WALL);
	public static final RegistryObject<Item> CHISELED_VOIDLIGHT = block(TheDeepVoidModBlocks.CHISELED_VOIDLIGHT);
	public static final RegistryObject<Item> DEAD_FERRYMAN = block(TheDeepVoidModBlocks.DEAD_FERRYMAN);
	public static final RegistryObject<Item> HANGED_LURKER_HEAD = block(TheDeepVoidModBlocks.HANGED_LURKER_HEAD);
	public static final RegistryObject<Item> GOLDEN_EYEBALL = REGISTRY.register("golden_eyeball", () -> new GoldenEyeballItem());
	public static final RegistryObject<Item> BLOCK_OF_SKULL_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_SKULL_PILE);
	public static final RegistryObject<Item> GRIM_SOIL = block(TheDeepVoidModBlocks.GRIM_SOIL);
	public static final RegistryObject<Item> COVERED_SKULL_PILE = block(TheDeepVoidModBlocks.COVERED_SKULL_PILE);
	public static final RegistryObject<Item> COVERED_BONE_PILE = block(TheDeepVoidModBlocks.COVERED_BONE_PILE);
	public static final RegistryObject<Item> HANGING_GOO = block(TheDeepVoidModBlocks.HANGING_GOO);
	public static final RegistryObject<Item> GOO_COVER = block(TheDeepVoidModBlocks.GOO_COVER);
	public static final RegistryObject<Item> GOO_COVER_BLOCK = block(TheDeepVoidModBlocks.GOO_COVER_BLOCK);
	public static final RegistryObject<Item> CONNECTED_HANGING_GOO = block(TheDeepVoidModBlocks.CONNECTED_HANGING_GOO);
	public static final RegistryObject<Item> BLOCK_OF_GOO = block(TheDeepVoidModBlocks.BLOCK_OF_GOO);
	public static final RegistryObject<Item> BONE_CRAWLER_EGG = block(TheDeepVoidModBlocks.BONE_CRAWLER_EGG);
	public static final RegistryObject<Item> BONE_CRAWLER_EGG_GENERATE = block(TheDeepVoidModBlocks.BONE_CRAWLER_EGG_GENERATE);
	public static final RegistryObject<Item> REGURGITATED_MATTER = block(TheDeepVoidModBlocks.REGURGITATED_MATTER);
	public static final RegistryObject<Item> GOO_GROWTH = doubleBlock(TheDeepVoidModBlocks.GOO_GROWTH);
	public static final RegistryObject<Item> GOO_BALL = REGISTRY.register("goo_ball", () -> new GooBallItem());
	public static final RegistryObject<Item> GOO_BRICKS = block(TheDeepVoidModBlocks.GOO_BRICKS);
	public static final RegistryObject<Item> GOO_BRICK_STAIRS = block(TheDeepVoidModBlocks.GOO_BRICK_STAIRS);
	public static final RegistryObject<Item> GOO_BRICK_SLAB = block(TheDeepVoidModBlocks.GOO_BRICK_SLAB);
	public static final RegistryObject<Item> GOO_BRICK_WALL = block(TheDeepVoidModBlocks.GOO_BRICK_WALL);
	public static final RegistryObject<Item> GOO_WEB = block(TheDeepVoidModBlocks.GOO_WEB);
	public static final RegistryObject<Item> ROTTEN_FLESH_CHUNK = block(TheDeepVoidModBlocks.ROTTEN_FLESH_CHUNK);
	public static final RegistryObject<Item> HANGING_ROTTEN_FLESH = block(TheDeepVoidModBlocks.HANGING_ROTTEN_FLESH);
	public static final RegistryObject<Item> ROTTEN_FLESH_STAIRS = block(TheDeepVoidModBlocks.ROTTEN_FLESH_STAIRS);
	public static final RegistryObject<Item> ROTTEN_FLESH_SLAB = block(TheDeepVoidModBlocks.ROTTEN_FLESH_SLAB);
	public static final RegistryObject<Item> MELTED_GOO = block(TheDeepVoidModBlocks.MELTED_GOO);
	public static final RegistryObject<Item> MELTED_GOO_STAIRS = block(TheDeepVoidModBlocks.MELTED_GOO_STAIRS);
	public static final RegistryObject<Item> MELTED_GOO_SLAB = block(TheDeepVoidModBlocks.MELTED_GOO_SLAB);
	public static final RegistryObject<Item> ROTTING_CORPSE = block(TheDeepVoidModBlocks.ROTTING_CORPSE);
	public static final RegistryObject<Item> ROTTING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_CORPSE_SPAWN);
	public static final RegistryObject<Item> ROTTING_COVERED_CORPSE = block(TheDeepVoidModBlocks.ROTTING_COVERED_CORPSE);
	public static final RegistryObject<Item> ROTTING_COVERED_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_COVERED_CORPSE_SPAWN);
	public static final RegistryObject<Item> ROTTING_LAYING_CORPSE = block(TheDeepVoidModBlocks.ROTTING_LAYING_CORPSE);
	public static final RegistryObject<Item> ROTTING_LAYING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_LAYING_CORPSE_SPAWN);
	public static final RegistryObject<Item> ROTTING_WALL_CORPSE = block(TheDeepVoidModBlocks.ROTTING_WALL_CORPSE);
	public static final RegistryObject<Item> TRANSLUCENT_GOO = block(TheDeepVoidModBlocks.TRANSLUCENT_GOO);
	public static final RegistryObject<Item> COOKED_CRAWLER_EGG = REGISTRY.register("cooked_crawler_egg", () -> new CookedCrawlerEggItem());
	public static final RegistryObject<Item> CRAWLER_OMELETTE = REGISTRY.register("crawler_omelette", () -> new CrawlerOmeletteItem());
	public static final RegistryObject<Item> BIG_BLUE_EYE = block(TheDeepVoidModBlocks.BIG_BLUE_EYE);
	public static final RegistryObject<Item> BIG_GREEN_EYE = block(TheDeepVoidModBlocks.BIG_GREEN_EYE);
	public static final RegistryObject<Item> BIG_RED_EYE = block(TheDeepVoidModBlocks.BIG_RED_EYE);
	public static final RegistryObject<Item> BIG_YELLOW_EYE = block(TheDeepVoidModBlocks.BIG_YELLOW_EYE);
	public static final RegistryObject<Item> HUGE_EYE_VINE_STEM = block(TheDeepVoidModBlocks.HUGE_EYE_VINE_STEM);
	public static final RegistryObject<Item> POROUS_FLESH = block(TheDeepVoidModBlocks.POROUS_FLESH);
	public static final RegistryObject<Item> VEINY_FLESH = block(TheDeepVoidModBlocks.VEINY_FLESH);
	public static final RegistryObject<Item> GAPING_POROUS_FLESH = block(TheDeepVoidModBlocks.GAPING_POROUS_FLESH);
	public static final RegistryObject<Item> CARRION = block(TheDeepVoidModBlocks.CARRION);
	public static final RegistryObject<Item> MESSY_FLESH = block(TheDeepVoidModBlocks.MESSY_FLESH);
	public static final RegistryObject<Item> HATCHING_ENZYME = REGISTRY.register("hatching_enzyme", () -> new HatchingEnzymeItem());
	public static final RegistryObject<Item> VULTURE_MUZZLE = REGISTRY.register("vulture_muzzle", () -> new VultureMuzzleItem());
	public static final RegistryObject<Item> RIDING_CROP = REGISTRY.register("riding_crop", () -> new RidingCropItem());
	public static final RegistryObject<Item> BONE_CRAWLER_CHITIN = REGISTRY.register("bone_crawler_chitin", () -> new BoneCrawlerChitinItem());
	public static final RegistryObject<Item> CRAWLER_HELMET = REGISTRY.register("crawler_helmet", () -> new CrawlerItem.Helmet());
	public static final RegistryObject<Item> CRAWLER_CHESTPLATE = REGISTRY.register("crawler_chestplate", () -> new CrawlerItem.Chestplate());
	public static final RegistryObject<Item> CRAWLER_LEGGINGS = REGISTRY.register("crawler_leggings", () -> new CrawlerItem.Leggings());
	public static final RegistryObject<Item> CRAWLER_BOOTS = REGISTRY.register("crawler_boots", () -> new CrawlerItem.Boots());
	public static final RegistryObject<Item> VOIDRIUM_GLASS = block(TheDeepVoidModBlocks.VOIDRIUM_GLASS);
	public static final RegistryObject<Item> GRIM_CRAWLER_HELMET = REGISTRY.register("grim_crawler_helmet", () -> new GrimCrawlerItem.Helmet());
	public static final RegistryObject<Item> GRIM_CRAWLER_CHESTPLATE = REGISTRY.register("grim_crawler_chestplate", () -> new GrimCrawlerItem.Chestplate());
	public static final RegistryObject<Item> GRIM_CRAWLER_LEGGINGS = REGISTRY.register("grim_crawler_leggings", () -> new GrimCrawlerItem.Leggings());
	public static final RegistryObject<Item> GRIM_CRAWLER_BOOTS = REGISTRY.register("grim_crawler_boots", () -> new GrimCrawlerItem.Boots());
	public static final RegistryObject<Item> GOO_SWORD = REGISTRY.register("goo_sword", () -> new GooSwordItem());
	public static final RegistryObject<Item> SULFUR_BOMB = REGISTRY.register("sulfur_bomb", () -> new SulfurBombItem());
	public static final RegistryObject<Item> BLOCK_OF_ROTTEN_BONE_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_ROTTEN_BONE_PILE);
	public static final RegistryObject<Item> CULT_HELMET = REGISTRY.register("cult_helmet", () -> new CultItem.Helmet());
	public static final RegistryObject<Item> CULT_CHESTPLATE = REGISTRY.register("cult_chestplate", () -> new CultItem.Chestplate());
	public static final RegistryObject<Item> CULT_LEGGINGS = REGISTRY.register("cult_leggings", () -> new CultItem.Leggings());
	public static final RegistryObject<Item> CULT_BOOTS = REGISTRY.register("cult_boots", () -> new CultItem.Boots());
	public static final RegistryObject<Item> CINNABAR_CHAIN = block(TheDeepVoidModBlocks.CINNABAR_CHAIN);
	public static final RegistryObject<Item> WEAVER_MASK_HELMET = REGISTRY.register("weaver_mask_helmet", () -> new WeaverMaskItem.Helmet());
	public static final RegistryObject<Item> LAYING_CORPSE = block(TheDeepVoidModBlocks.LAYING_CORPSE);
	public static final RegistryObject<Item> JACK_O_LAYING_CORPSE = block(TheDeepVoidModBlocks.JACK_O_LAYING_CORPSE);
	public static final RegistryObject<Item> LAYING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.LAYING_CORPSE_SPAWN);
	public static final RegistryObject<Item> MRORDYYGOTHRE_SPAWN_EGG = REGISTRY.register("mrordyygothre_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.MRORDYYGOTHRE, -14811136, -3785941, new Item.Properties()));
	public static final RegistryObject<Item> SINS_AND_SINNERS = REGISTRY.register("sins_and_sinners", () -> new SinsAndSinnersItem());
	public static final RegistryObject<Item> ANCIENT_ALTAR = block(TheDeepVoidModBlocks.ANCIENT_ALTAR);
	public static final RegistryObject<Item> BLIND_PROPHET_SPAWN_EGG = REGISTRY.register("blind_prophet_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.BLIND_PROPHET, -4506307, -14483456, new Item.Properties()));
	public static final RegistryObject<Item> WEAVER_ROBE_CHESTPLATE = REGISTRY.register("weaver_robe_chestplate", () -> new WeaverRobeItem.Chestplate());
	public static final RegistryObject<Item> SACRED_CINNABAR = REGISTRY.register("sacred_cinnabar", () -> new SacredCinnabarItem());
	public static final RegistryObject<Item> SACRED_VOIDRIUM_HELMET = REGISTRY.register("sacred_voidrium_helmet", () -> new SacredVoidriumItem.Helmet());
	public static final RegistryObject<Item> SACRED_VOIDRIUM_CHESTPLATE = REGISTRY.register("sacred_voidrium_chestplate", () -> new SacredVoidriumItem.Chestplate());
	public static final RegistryObject<Item> SACRED_VOIDRIUM_LEGGINGS = REGISTRY.register("sacred_voidrium_leggings", () -> new SacredVoidriumItem.Leggings());
	public static final RegistryObject<Item> SACRED_VOIDRIUM_BOOTS = REGISTRY.register("sacred_voidrium_boots", () -> new SacredVoidriumItem.Boots());
	public static final RegistryObject<Item> GRIM_LAVENDITE_HELMET = REGISTRY.register("grim_lavendite_helmet", () -> new GrimLavenditeItem.Helmet());
	public static final RegistryObject<Item> GRIM_LAVENDITE_CHESTPLATE = REGISTRY.register("grim_lavendite_chestplate", () -> new GrimLavenditeItem.Chestplate());
	public static final RegistryObject<Item> GRIM_LAVENDITE_LEGGINGS = REGISTRY.register("grim_lavendite_leggings", () -> new GrimLavenditeItem.Leggings());
	public static final RegistryObject<Item> GRIM_LAVENDITE_BOOTS = REGISTRY.register("grim_lavendite_boots", () -> new GrimLavenditeItem.Boots());
	public static final RegistryObject<Item> BLOCK_OF_RAW_CINNABAR = block(TheDeepVoidModBlocks.BLOCK_OF_RAW_CINNABAR);
	public static final RegistryObject<Item> ANCIENT_ONYX = REGISTRY.register("ancient_onyx", () -> new AncientOnyxItem());
	public static final RegistryObject<Item> BISMUTH_BRICKS = block(TheDeepVoidModBlocks.BISMUTH_BRICKS);
	public static final RegistryObject<Item> BISMUTH_BRICK_STAIRS = block(TheDeepVoidModBlocks.BISMUTH_BRICK_STAIRS);
	public static final RegistryObject<Item> BISMUTH_BRICK_SLAB = block(TheDeepVoidModBlocks.BISMUTH_BRICK_SLAB);
	public static final RegistryObject<Item> BLOCK_OF_REFINED_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_REFINED_ONYX);
	public static final RegistryObject<Item> BLOCK_OF_ANCIENT_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_ANCIENT_ONYX);
	public static final RegistryObject<Item> REFINED_ONYX_STAIRS = block(TheDeepVoidModBlocks.REFINED_ONYX_STAIRS);
	public static final RegistryObject<Item> REFINED_ONYX_SLAB = block(TheDeepVoidModBlocks.REFINED_ONYX_SLAB);
	public static final RegistryObject<Item> CRUEL_STILETTO = REGISTRY.register("cruel_stiletto", () -> new CruelStilettoItem());
	public static final RegistryObject<Item> SHADESTORM = REGISTRY.register("shadestorm", () -> new ShadestormItem());
	public static final RegistryObject<Item> MOURNER_SPAWN_EGG = REGISTRY.register("mourner_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.MOURNER, -16777216, -14408668, new Item.Properties()));
	public static final RegistryObject<Item> BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("bone_crawler_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.BONE_CRAWLER, -14474721, -10724523, new Item.Properties()));
	public static final RegistryObject<Item> FOOL_EATER_SPAWN_EGG = REGISTRY.register("fool_eater_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.FOOL_EATER, -15790835, -13298925, new Item.Properties()));
	public static final RegistryObject<Item> HALLUCINATION_SPAWN_EGG = REGISTRY.register("hallucination_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.HALLUCINATION, -15987700, -12632257, new Item.Properties()));
	public static final RegistryObject<Item> LURKER_SPAWN_EGG = REGISTRY.register("lurker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.LURKER, -13685463, -11712192, new Item.Properties()));
	public static final RegistryObject<Item> STALKER_SPAWN_EGG = REGISTRY.register("stalker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.STALKER, -15132648, -13752280, new Item.Properties()));
	public static final RegistryObject<Item> ABDUCTOR_SPAWN_EGG = REGISTRY.register("abductor_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ABDUCTOR, -13882324, -15790321, new Item.Properties()));
	public static final RegistryObject<Item> VOID_DWELLER_SPAWN_EGG = REGISTRY.register("void_dweller_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.VOID_DWELLER, -15132123, -12829636, new Item.Properties()));
	public static final RegistryObject<Item> LICKER_SPAWN_EGG = REGISTRY.register("licker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.LICKER, -14934235, -12517376, new Item.Properties()));
	public static final RegistryObject<Item> FLESH_CUBE_SPAWN_EGG = REGISTRY.register("flesh_cube_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.FLESH_CUBE, -13887207, -13096920, new Item.Properties()));
	public static final RegistryObject<Item> SPORE_SPEWER_SPAWN_EGG = REGISTRY.register("spore_spewer_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SPORE_SPEWER, -14151407, -11450067, new Item.Properties()));
	public static final RegistryObject<Item> WANDERER_SPAWN_EGG = REGISTRY.register("wanderer_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.WANDERER, -11908798, -15395563, new Item.Properties()));
	public static final RegistryObject<Item> GRAVEKEEPER_SPAWN_EGG = REGISTRY.register("gravekeeper_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.GRAVEKEEPER, -12303809, -14408927, new Item.Properties()));
	public static final RegistryObject<Item> GOO_SPITTER_SPAWN_EGG = REGISTRY.register("goo_spitter_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.GOO_SPITTER, -14474721, -10724523, new Item.Properties()));
	public static final RegistryObject<Item> ROAMER_SPAWN_EGG = REGISTRY.register("roamer_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ROAMER, -11448500, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> ENDLESS_QUIVER = REGISTRY.register("endless_quiver", () -> new EndlessQuiverItem());
	public static final RegistryObject<Item> MOTHER_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("mother_bone_crawler_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.MOTHER_BONE_CRAWLER, -14145757, -5786461, new Item.Properties()));
	public static final RegistryObject<Item> ALPHA_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("alpha_bone_crawler_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ALPHA_BONE_CRAWLER, -15593201, -13224397, new Item.Properties()));
	public static final RegistryObject<Item> BABY_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("baby_bone_crawler_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.BABY_BONE_CRAWLER, -10790830, -7698308, new Item.Properties()));
	public static final RegistryObject<Item> ROTTEN_CORPSE_SPAWN_EGG = REGISTRY.register("rotten_corpse_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ROTTEN_CORPSE, -6513508, -11711422, new Item.Properties()));
	public static final RegistryObject<Item> ROTTEN_CULT_MEMBER_SPAWN_EGG = REGISTRY.register("rotten_cult_member_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ROTTEN_CULT_MEMBER, -6513508, -16053493, new Item.Properties()));
	public static final RegistryObject<Item> EYEKIN_SPAWN_EGG = REGISTRY.register("eyekin_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.EYEKIN, -10551296, -11099436, new Item.Properties()));
	public static final RegistryObject<Item> SWARMER_SPAWN_EGG = REGISTRY.register("swarmer_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SWARMER, -10019812, -14271126, new Item.Properties()));
	public static final RegistryObject<Item> DEATH_MAW_SPAWN_EGG = REGISTRY.register("death_maw_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.DEATH_MAW, -15987700, -13684945, new Item.Properties()));
	public static final RegistryObject<Item> BEHOLDER_SPAWN_EGG = REGISTRY.register("beholder_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.BEHOLDER, -13955570, -3357500, new Item.Properties()));
	public static final RegistryObject<Item> EVERHUNGER_SPAWN_EGG = REGISTRY.register("everhunger_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.EVERHUNGER, -13890034, -6779263, new Item.Properties()));
	public static final RegistryObject<Item> DEATH_VULTURE_SPAWN_EGG = REGISTRY.register("death_vulture_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.DEATH_VULTURE, -15329770, -4342877, new Item.Properties()));
	public static final RegistryObject<Item> DEVOURER_SPAWN_EGG = REGISTRY.register("devourer_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.DEVOURER, -15268603, -7455170, new Item.Properties()));
	public static final RegistryObject<Item> ROOTED_SPAWN_EGG = REGISTRY.register("rooted_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.ROOTED, -14474718, -8421505, new Item.Properties()));
	public static final RegistryObject<Item> SCARECROW_SPAWN_EGG = REGISTRY.register("scarecrow_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SCARECROW, -13697024, -3816264, new Item.Properties()));
	public static final RegistryObject<Item> NIGHTMARE_SPAWN_EGG = REGISTRY.register("nightmare_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.NIGHTMARE, -15526884, -14013133, new Item.Properties()));
	public static final RegistryObject<Item> OVERSEER_BIG_PILLAR_SPAWN_EGG = REGISTRY.register("overseer_big_pillar_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.OVERSEER_BIG_PILLAR, -15460839, -14216943, new Item.Properties()));
	public static final RegistryObject<Item> BONE_LOAF = REGISTRY.register("bone_loaf", () -> new BoneLoafItem());
	public static final RegistryObject<Item> ROTTEN_DELIGHT = REGISTRY.register("rotten_delight", () -> new RottenDelightItem());
	public static final RegistryObject<Item> CREEP_O_METER = REGISTRY.register("creep_o_meter", () -> new CreepOMeterItem());
	public static final RegistryObject<Item> CENTIGAZE_SPAWN_EGG = REGISTRY.register("centigaze_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.CENTIGAZE, -16382190, -14475466, new Item.Properties()));
	public static final RegistryObject<Item> DESOLATE_SOIL_ACTIVE = block(TheDeepVoidModBlocks.DESOLATE_SOIL_ACTIVE);
	public static final RegistryObject<Item> STALKING_STALKER_SPAWN_EGG = REGISTRY.register("stalking_stalker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.STALKING_STALKER, -16053493, -14475232, new Item.Properties()));
	public static final RegistryObject<Item> SHADOW_SPAWN_EGG = REGISTRY.register("shadow_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SHADOW, -16777216, -15329770, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_CLEAVER = REGISTRY.register("soul_cleaver", () -> new SoulCleaverItem());
	public static final RegistryObject<Item> WEAVER_LEGGINGS_LEGGINGS = REGISTRY.register("weaver_leggings_leggings", () -> new WeaverLeggingsItem.Leggings());
	public static final RegistryObject<Item> WEAVER_BOOTS_BOOTS = REGISTRY.register("weaver_boots_boots", () -> new WeaverBootsItem.Boots());
	public static final RegistryObject<Item> WATCHING_STALKER_SPAWN_EGG = REGISTRY.register("watching_stalker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.WATCHING_STALKER, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> VOID_MIRROR = REGISTRY.register("void_mirror", () -> new VoidMirrorItem());
	public static final RegistryObject<Item> WEAVER_OF_SOULS_SPAWN_EGG = REGISTRY.register("weaver_of_souls_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.WEAVER_OF_SOULS, -15724528, -15786978, new Item.Properties()));
	public static final RegistryObject<Item> DARKMARE = REGISTRY.register("darkmare", () -> new DarkmareItem());
	public static final RegistryObject<Item> HAND_SPAWN_SPAWN_EGG = REGISTRY.register("hand_spawn_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.HAND_SPAWN, -16760499, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> DAMNED_SPAWN_EGG = REGISTRY.register("damned_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.DAMNED, -15396334, -1, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_ORB_PILLAR = block(TheDeepVoidModBlocks.SOUL_ORB_PILLAR);
	public static final RegistryObject<Item> SOUL_ORB_SPAWN_EGG = REGISTRY.register("soul_orb_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SOUL_ORB, -16743782, -12590593, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_CONTAINER = block(TheDeepVoidModBlocks.SOUL_CONTAINER);
	public static final RegistryObject<Item> CHAINED_WEAVER_SPAWN_EGG = REGISTRY.register("chained_weaver_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.CHAINED_WEAVER, -12036769, -15786978, new Item.Properties()));
	public static final RegistryObject<Item> HEXED_DOLL = REGISTRY.register("hexed_doll", () -> new HexedDollItem());
	public static final RegistryObject<Item> WEAVER_OF_SOULS_TREASURE_BAG = REGISTRY.register("weaver_of_souls_treasure_bag", () -> new WeaverOfSoulsTreasureBagItem());
	public static final RegistryObject<Item> VOODOO_DOLL = REGISTRY.register("voodoo_doll", () -> new VoodooDollItem());
	public static final RegistryObject<Item> SOUL_SHARD = REGISTRY.register("soul_shard", () -> new SoulShardItem());
	public static final RegistryObject<Item> THE_HARVEST = REGISTRY.register("the_harvest", () -> new TheHarvestItem());
	public static final RegistryObject<Item> HARVESTER_MASK_HELMET = REGISTRY.register("harvester_mask_helmet", () -> new HarvesterMaskItem.Helmet());
	public static final RegistryObject<Item> TOMBSTONE = REGISTRY.register("tombstone", () -> new TombstoneItem());
	public static final RegistryObject<Item> VOID_EFFIGY = block(TheDeepVoidModBlocks.VOID_EFFIGY);
	public static final RegistryObject<Item> VOID_EFFIGY_OPEN = block(TheDeepVoidModBlocks.VOID_EFFIGY_OPEN);
	public static final RegistryObject<Item> CINNABAR_GLASS = block(TheDeepVoidModBlocks.CINNABAR_GLASS);
	public static final RegistryObject<Item> CINNABAR_GLASS_PANE = block(TheDeepVoidModBlocks.CINNABAR_GLASS_PANE);
	public static final RegistryObject<Item> FLESH_GLOVE = REGISTRY.register("flesh_glove", () -> new FleshGloveItem());
	public static final RegistryObject<Item> LAVENDITE_PICKAXE = REGISTRY.register("lavendite_pickaxe", () -> new LavenditePickaxeItem());
	public static final RegistryObject<Item> LAVENDITE_AXE = REGISTRY.register("lavendite_axe", () -> new LavenditeAxeItem());
	public static final RegistryObject<Item> LAVENDITE_SHOVEL = REGISTRY.register("lavendite_shovel", () -> new LavenditeShovelItem());
	public static final RegistryObject<Item> LAVENDITE_HOE = REGISTRY.register("lavendite_hoe", () -> new LavenditeHoeItem());
	public static final RegistryObject<Item> BONE_NEEDLE = REGISTRY.register("bone_needle", () -> new BoneNeedleItem());
	public static final RegistryObject<Item> REGENERATION_NEEDLE = REGISTRY.register("regeneration_needle", () -> new RegenerationNeedleItem());
	public static final RegistryObject<Item> ABSORPTION_NEEDLE = REGISTRY.register("absorption_needle", () -> new AbsorptionNeedleItem());
	public static final RegistryObject<Item> RESISTANCE_NEEDLE = REGISTRY.register("resistance_needle", () -> new ResistanceNeedleItem());
	public static final RegistryObject<Item> GLOWING_NEEDLE = REGISTRY.register("glowing_needle", () -> new GlowingNeedleItem());
	public static final RegistryObject<Item> ROT_NEEDLE = REGISTRY.register("rot_needle", () -> new RotNeedleItem());
	public static final RegistryObject<Item> JUMP_BOOST_NEEDLE = REGISTRY.register("jump_boost_needle", () -> new JumpBoostNeedleItem());
	public static final RegistryObject<Item> HEXED_NEEDLE = REGISTRY.register("hexed_needle", () -> new HexedNeedleItem());
	public static final RegistryObject<Item> FIRE_RESISTANCE_NEEDLE = REGISTRY.register("fire_resistance_needle", () -> new FireResistanceNeedleItem());
	public static final RegistryObject<Item> POISON_NEEDLE = REGISTRY.register("poison_needle", () -> new PoisonNeedleItem());
	public static final RegistryObject<Item> SPEED_NEEDLE = REGISTRY.register("speed_needle", () -> new SpeedNeedleItem());
	public static final RegistryObject<Item> HEALTH_BOOST_NEEDLE = REGISTRY.register("health_boost_needle", () -> new HealthBoostNeedleItem());
	public static final RegistryObject<Item> WITHER_NEEDLE = REGISTRY.register("wither_needle", () -> new WitherNeedleItem());
	public static final RegistryObject<Item> SATURATION_NEEDLE = REGISTRY.register("saturation_needle", () -> new SaturationNeedleItem());
	public static final RegistryObject<Item> JUDGEMENT = REGISTRY.register("judgement", () -> new JudgementItem());
	public static final RegistryObject<Item> FORSAKEN_SPAWN_EGG = REGISTRY.register("forsaken_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.FORSAKEN, -14014174, -1, new Item.Properties()));
	public static final RegistryObject<Item> ELYTRA_PIECE = REGISTRY.register("elytra_piece", () -> new ElytraPieceItem());
	public static final RegistryObject<Item> VOIDRIUM_BULWARK = REGISTRY.register("voidrium_bulwark", () -> new VoidriumBulwarkItem());
	public static final RegistryObject<Item> ROTTEN_MOSS_ACTIVE = block(TheDeepVoidModBlocks.ROTTEN_MOSS_ACTIVE);
	public static final RegistryObject<Item> BIG_SMOKE_VENT = block(TheDeepVoidModBlocks.BIG_SMOKE_VENT);
	public static final RegistryObject<Item> BIG_SMOKE_VENT_CORNER = block(TheDeepVoidModBlocks.BIG_SMOKE_VENT_CORNER);
	public static final RegistryObject<Item> VENT_STONE = block(TheDeepVoidModBlocks.VENT_STONE);
	public static final RegistryObject<Item> CORPSE_PILE = block(TheDeepVoidModBlocks.CORPSE_PILE);
	public static final RegistryObject<Item> SEEKER_SPAWN_EGG = REGISTRY.register("seeker_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.SEEKER, -16777216, -1, new Item.Properties()));
	public static final RegistryObject<Item> BIG_TOOTH = block(TheDeepVoidModBlocks.BIG_TOOTH);
	public static final RegistryObject<Item> SOUL_FORGE = block(TheDeepVoidModBlocks.SOUL_FORGE);
	public static final RegistryObject<Item> SOUL_FUSED_INGOT = REGISTRY.register("soul_fused_ingot", () -> new SoulFusedIngotItem());
	public static final RegistryObject<Item> APOSTLE_OF_CATASTROPHE_SPAWN_EGG = REGISTRY.register("apostle_of_catastrophe_spawn_egg",
			() -> new ForgeSpawnEggItem(TheDeepVoidModEntities.APOSTLE_OF_CATASTROPHE, -13762560, -11776, new Item.Properties()));
	public static final RegistryObject<Item> CHAINSAW = REGISTRY.register("chainsaw", () -> new ChainsawItem());
	public static final RegistryObject<Item> APOSTLE_OF_CATASTROPHE_TREASURE_BAG = REGISTRY.register("apostle_of_catastrophe_treasure_bag", () -> new ApostleOfCatastropheTreasureBagItem());
	public static final RegistryObject<Item> RED_GATE = block(TheDeepVoidModBlocks.RED_GATE);
	public static final RegistryObject<Item> RED_GATE_NON_SOLID = block(TheDeepVoidModBlocks.RED_GATE_NON_SOLID);
	public static final RegistryObject<Item> IDLING_APOSTLE_SPAWN_EGG = REGISTRY.register("idling_apostle_spawn_egg", () -> new ForgeSpawnEggItem(TheDeepVoidModEntities.IDLING_APOSTLE, -15597568, -8427264, new Item.Properties()));
	public static final RegistryObject<Item> KNIFE_GLOVE = REGISTRY.register("knife_glove", () -> new KnifeGloveItem());
	public static final RegistryObject<Item> BLOCK_OF_SOUL_FUSED_INGOTS = block(TheDeepVoidModBlocks.BLOCK_OF_SOUL_FUSED_INGOTS);
	public static final RegistryObject<Item> VOID_GROWTH = block(TheDeepVoidModBlocks.VOID_GROWTH);
	public static final RegistryObject<Item> HERESY = REGISTRY.register("heresy", () -> new HeresyItem());
	public static final RegistryObject<Item> FLESH_STAIRS = block(TheDeepVoidModBlocks.FLESH_STAIRS);
	public static final RegistryObject<Item> FLESH_SLAB = block(TheDeepVoidModBlocks.FLESH_SLAB);
	public static final RegistryObject<Item> TENDONS = block(TheDeepVoidModBlocks.TENDONS);
	public static final RegistryObject<Item> OLD_CORPSE_PILE = block(TheDeepVoidModBlocks.OLD_CORPSE_PILE);
	public static final RegistryObject<Item> OLD_CORPSE = block(TheDeepVoidModBlocks.OLD_CORPSE);
	public static final RegistryObject<Item> OLD_WALL_CORPSE = block(TheDeepVoidModBlocks.OLD_WALL_CORPSE);
	public static final RegistryObject<Item> OLD_COVERED_CORPSE = block(TheDeepVoidModBlocks.OLD_COVERED_CORPSE);
	public static final RegistryObject<Item> OLD_LAYING_CORPSE = block(TheDeepVoidModBlocks.OLD_LAYING_CORPSE);
	public static final RegistryObject<Item> OLD_BONE_BLOCK = block(TheDeepVoidModBlocks.OLD_BONE_BLOCK);
	public static final RegistryObject<Item> FLESHY_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_ROTTEN_BONE_BLOCK);
	public static final RegistryObject<Item> FLESHY_OLD_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_OLD_BONE_BLOCK);
	public static final RegistryObject<Item> EYE_TENDONS = block(TheDeepVoidModBlocks.EYE_TENDONS);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(LAVENDITE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(EYE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(DEVOURER_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
			ItemProperties.register(VOIDRIUM_BULWARK.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
		});
	}
}
