
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedeepvoid.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.thedeepvoid.block.YellowEyeVineBlock;
import net.mcreator.thedeepvoid.block.YellowCandlestickBlock;
import net.mcreator.thedeepvoid.block.YellowCandelabraBlock;
import net.mcreator.thedeepvoid.block.WhiteCandlestickBlock;
import net.mcreator.thedeepvoid.block.WhiteCandelabraBlock;
import net.mcreator.thedeepvoid.block.WatchingWillowSaplingBlock;
import net.mcreator.thedeepvoid.block.WatcherOnBlock;
import net.mcreator.thedeepvoid.block.WatcherBlock;
import net.mcreator.thedeepvoid.block.WallCorpseBlock;
import net.mcreator.thedeepvoid.block.VoidriumSawTrapBlock;
import net.mcreator.thedeepvoid.block.VoidriumGlassBlock;
import net.mcreator.thedeepvoid.block.VoidlightBricksBlock;
import net.mcreator.thedeepvoid.block.VoidlightBrickWallBlock;
import net.mcreator.thedeepvoid.block.VoidlightBrickStairsBlock;
import net.mcreator.thedeepvoid.block.VoidlightBrickSlabBlock;
import net.mcreator.thedeepvoid.block.VoidlightBlock;
import net.mcreator.thedeepvoid.block.VoidStemBlock;
import net.mcreator.thedeepvoid.block.VoidRoseBlock;
import net.mcreator.thedeepvoid.block.VoidRootsBlock;
import net.mcreator.thedeepvoid.block.VoidGrowthBlock;
import net.mcreator.thedeepvoid.block.VoidFilledSpongeBlock;
import net.mcreator.thedeepvoid.block.VoidFernBlock;
import net.mcreator.thedeepvoid.block.VoidEffigyOpenBlock;
import net.mcreator.thedeepvoid.block.VoidEffigyBlock;
import net.mcreator.thedeepvoid.block.VoidCoreBlock;
import net.mcreator.thedeepvoid.block.VoidBlossomBlock;
import net.mcreator.thedeepvoid.block.VentStoneBlock;
import net.mcreator.thedeepvoid.block.VeinyFleshBlock;
import net.mcreator.thedeepvoid.block.UmbriumOreBlock;
import net.mcreator.thedeepvoid.block.TwistingSpineBlock;
import net.mcreator.thedeepvoid.block.TrapBoneSpikesBlock;
import net.mcreator.thedeepvoid.block.TranslucentGooBlock;
import net.mcreator.thedeepvoid.block.TransformedSeerBlock;
import net.mcreator.thedeepvoid.block.TendrilsBlock;
import net.mcreator.thedeepvoid.block.TendonsBlock;
import net.mcreator.thedeepvoid.block.TeethTrapBlockBlock;
import net.mcreator.thedeepvoid.block.TeethTrapBlock;
import net.mcreator.thedeepvoid.block.TeethBlockBlock;
import net.mcreator.thedeepvoid.block.TeethBlock;
import net.mcreator.thedeepvoid.block.SulfurTntBlock;
import net.mcreator.thedeepvoid.block.SulfurPowderBlock;
import net.mcreator.thedeepvoid.block.SulfurOreBlock;
import net.mcreator.thedeepvoid.block.SulfurLanternBlock;
import net.mcreator.thedeepvoid.block.SulfurGlassPaneBlock;
import net.mcreator.thedeepvoid.block.SulfurGlassBlock;
import net.mcreator.thedeepvoid.block.StrippedRottenWoodBlock;
import net.mcreator.thedeepvoid.block.StrippedRottenLogBlock;
import net.mcreator.thedeepvoid.block.SoulOrbPillarBlock;
import net.mcreator.thedeepvoid.block.SoulForgeBlock;
import net.mcreator.thedeepvoid.block.SoulContainerBlock;
import net.mcreator.thedeepvoid.block.SolidVoidStairsBlock;
import net.mcreator.thedeepvoid.block.SolidVoidSlabBlock;
import net.mcreator.thedeepvoid.block.SolidVoidBricksBlock;
import net.mcreator.thedeepvoid.block.SolidVoidBrickWallBlock;
import net.mcreator.thedeepvoid.block.SolidVoidBrickStairsBlock;
import net.mcreator.thedeepvoid.block.SolidVoidBrickSlabBlock;
import net.mcreator.thedeepvoid.block.SolidVoidBlockBlock;
import net.mcreator.thedeepvoid.block.SolidAmbrosiaBlock;
import net.mcreator.thedeepvoid.block.SmoothSolidVoidBlock;
import net.mcreator.thedeepvoid.block.SmoothMonolithicStoneStairsBlock;
import net.mcreator.thedeepvoid.block.SmoothMonolithicStoneSlabBlock;
import net.mcreator.thedeepvoid.block.SmoothMonolithicStoneBlock;
import net.mcreator.thedeepvoid.block.SmoothAncientDeepslateStairsBlock;
import net.mcreator.thedeepvoid.block.SmoothAncientDeepslateSlabBlock;
import net.mcreator.thedeepvoid.block.SmoothAncientDeepslatePressurePlateBlock;
import net.mcreator.thedeepvoid.block.SmoothAncientDeepslateButtonBlock;
import net.mcreator.thedeepvoid.block.SmoothAncientDeepslateBlock;
import net.mcreator.thedeepvoid.block.SmokeVentBlock;
import net.mcreator.thedeepvoid.block.ShortCircuitRooterBlock;
import net.mcreator.thedeepvoid.block.SeerBlock;
import net.mcreator.thedeepvoid.block.RottingWallCorpseBlock;
import net.mcreator.thedeepvoid.block.RottingLayingCorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.RottingLayingCorpseBlock;
import net.mcreator.thedeepvoid.block.RottingCoveredCorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.RottingCoveredCorpseBlock;
import net.mcreator.thedeepvoid.block.RottingCorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.RottingCorpseInACageBlock;
import net.mcreator.thedeepvoid.block.RottingCorpseBlock;
import net.mcreator.thedeepvoid.block.RottenWoodBlock;
import net.mcreator.thedeepvoid.block.RottenTrapdoorBlock;
import net.mcreator.thedeepvoid.block.RottenStairsBlock;
import net.mcreator.thedeepvoid.block.RottenSlabBlock;
import net.mcreator.thedeepvoid.block.RottenRootsBlock;
import net.mcreator.thedeepvoid.block.RottenPressurePlateBlock;
import net.mcreator.thedeepvoid.block.RottenPlanksBlock;
import net.mcreator.thedeepvoid.block.RottenMossBlock;
import net.mcreator.thedeepvoid.block.RottenMossActiveBlock;
import net.mcreator.thedeepvoid.block.RottenLogBlock;
import net.mcreator.thedeepvoid.block.RottenGrowthBlock;
import net.mcreator.thedeepvoid.block.RottenGrassBlock;
import net.mcreator.thedeepvoid.block.RottenFossilBlock;
import net.mcreator.thedeepvoid.block.RottenFleshStairsBlock;
import net.mcreator.thedeepvoid.block.RottenFleshSlabBlock;
import net.mcreator.thedeepvoid.block.RottenFleshChunkBlock;
import net.mcreator.thedeepvoid.block.RottenFenceGateBlock;
import net.mcreator.thedeepvoid.block.RottenFenceBlock;
import net.mcreator.thedeepvoid.block.RottenDoorBlock;
import net.mcreator.thedeepvoid.block.RottenCrateBlock;
import net.mcreator.thedeepvoid.block.RottenButtonBlock;
import net.mcreator.thedeepvoid.block.RottenBoneBlockBlock;
import net.mcreator.thedeepvoid.block.RottenAncientDeepslateBricksBlock;
import net.mcreator.thedeepvoid.block.RottenAncientDeepslateBrickWallBlock;
import net.mcreator.thedeepvoid.block.RottenAncientDeepslateBrickStairsBlock;
import net.mcreator.thedeepvoid.block.RottenAncientDeepslateBrickSlabBlock;
import net.mcreator.thedeepvoid.block.RooterOnBlock;
import net.mcreator.thedeepvoid.block.RooterBlock;
import net.mcreator.thedeepvoid.block.RegurgitatedMatterBlock;
import net.mcreator.thedeepvoid.block.RefinedOnyxStairsBlock;
import net.mcreator.thedeepvoid.block.RefinedOnyxSlabBlock;
import net.mcreator.thedeepvoid.block.RedGateNonSolidBlock;
import net.mcreator.thedeepvoid.block.RedGateBlock;
import net.mcreator.thedeepvoid.block.RedEyeVineBlock;
import net.mcreator.thedeepvoid.block.RedCandlestickBlock;
import net.mcreator.thedeepvoid.block.RedCandelabraBlock;
import net.mcreator.thedeepvoid.block.PustulentFleshBricksBlock;
import net.mcreator.thedeepvoid.block.PustulentFleshBrickStairsBlock;
import net.mcreator.thedeepvoid.block.PustulentFleshBrickSlabBlock;
import net.mcreator.thedeepvoid.block.PustulentFleshBlockBlock;
import net.mcreator.thedeepvoid.block.PusSackBlock;
import net.mcreator.thedeepvoid.block.PusFlowerBlock;
import net.mcreator.thedeepvoid.block.PurpleEyeVineBlock;
import net.mcreator.thedeepvoid.block.PurpleCandlestickBlock;
import net.mcreator.thedeepvoid.block.PurpleCandelabraBlock;
import net.mcreator.thedeepvoid.block.ProtrudingMarrowBlock;
import net.mcreator.thedeepvoid.block.PrimordialStoneStairsBlock;
import net.mcreator.thedeepvoid.block.PrimordialStoneSlabBlock;
import net.mcreator.thedeepvoid.block.PrimordialStoneReplicaBlock;
import net.mcreator.thedeepvoid.block.PrimordialStoneBlock;
import net.mcreator.thedeepvoid.block.PoweredLavaGeyserOnBlock;
import net.mcreator.thedeepvoid.block.PoweredLavaGeyserBlock;
import net.mcreator.thedeepvoid.block.PorousFleshBlock;
import net.mcreator.thedeepvoid.block.PolishedLavenditeStairsBlock;
import net.mcreator.thedeepvoid.block.PolishedLavenditeSlabBlock;
import net.mcreator.thedeepvoid.block.PolishedLavenditeBlockBlock;
import net.mcreator.thedeepvoid.block.PinkCandlestickBlock;
import net.mcreator.thedeepvoid.block.PinkCandelabraBlock;
import net.mcreator.thedeepvoid.block.PileOfBonesBlockBlock;
import net.mcreator.thedeepvoid.block.PileOfBonesBlock;
import net.mcreator.thedeepvoid.block.PenitentInACageBlock;
import net.mcreator.thedeepvoid.block.PeepingStemBlock;
import net.mcreator.thedeepvoid.block.PeepingRootsBlock;
import net.mcreator.thedeepvoid.block.PackedFleshBlock;
import net.mcreator.thedeepvoid.block.OrangeCandlestickBlock;
import net.mcreator.thedeepvoid.block.OrangeCandelabraBlock;
import net.mcreator.thedeepvoid.block.OnyxOreBlock;
import net.mcreator.thedeepvoid.block.OldWallCorpseBlock;
import net.mcreator.thedeepvoid.block.OldLayingCorpseBlock;
import net.mcreator.thedeepvoid.block.OldCoveredCorpseBlock;
import net.mcreator.thedeepvoid.block.OldCorpsePileBlock;
import net.mcreator.thedeepvoid.block.OldCorpseInACageBlock;
import net.mcreator.thedeepvoid.block.OldCorpseBlock;
import net.mcreator.thedeepvoid.block.OldBoneBlockBlock;
import net.mcreator.thedeepvoid.block.MossyBonePileBlock;
import net.mcreator.thedeepvoid.block.MonolithicStoneWallBlock;
import net.mcreator.thedeepvoid.block.MonolithicStoneStairsBlock;
import net.mcreator.thedeepvoid.block.MonolithicStoneSlabBlock;
import net.mcreator.thedeepvoid.block.MonolithicStoneBlock;
import net.mcreator.thedeepvoid.block.MonolithicBricksBlock;
import net.mcreator.thedeepvoid.block.MonolithicBrickWallBlock;
import net.mcreator.thedeepvoid.block.MonolithicBrickStairsBlock;
import net.mcreator.thedeepvoid.block.MonolithicBrickSlabBlock;
import net.mcreator.thedeepvoid.block.MistedRemainsBlock;
import net.mcreator.thedeepvoid.block.MessyFleshBlock;
import net.mcreator.thedeepvoid.block.MeltedGooStairsBlock;
import net.mcreator.thedeepvoid.block.MeltedGooSlabBlock;
import net.mcreator.thedeepvoid.block.MeltedGooBlock;
import net.mcreator.thedeepvoid.block.MagentaCandlestickBlock;
import net.mcreator.thedeepvoid.block.MagentaCandelabraBlock;
import net.mcreator.thedeepvoid.block.MadnessLanternBlock;
import net.mcreator.thedeepvoid.block.LurkerShrineBlock;
import net.mcreator.thedeepvoid.block.LurkerHeadBlock;
import net.mcreator.thedeepvoid.block.LiquidVoidBlock;
import net.mcreator.thedeepvoid.block.LiquidIchorBlock;
import net.mcreator.thedeepvoid.block.LimeCandlestickBlock;
import net.mcreator.thedeepvoid.block.LimeCandelabraBlock;
import net.mcreator.thedeepvoid.block.LightGrayCandlestickBlock;
import net.mcreator.thedeepvoid.block.LightGrayCandelabraBlock;
import net.mcreator.thedeepvoid.block.LightBlueCandlestickBlock;
import net.mcreator.thedeepvoid.block.LightBlueCandelabraBlock;
import net.mcreator.thedeepvoid.block.LayingCorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.LayingCorpseBlock;
import net.mcreator.thedeepvoid.block.LavenditeOreBlock;
import net.mcreator.thedeepvoid.block.JackOWallCorpseBlock;
import net.mcreator.thedeepvoid.block.JackOLayingCorpseBlock;
import net.mcreator.thedeepvoid.block.JackOCoveredCorpseBlock;
import net.mcreator.thedeepvoid.block.JackOCorpseInACageBlock;
import net.mcreator.thedeepvoid.block.JackOCorpseBlock;
import net.mcreator.thedeepvoid.block.IntertwinedBlackMossBlock;
import net.mcreator.thedeepvoid.block.InscribedAncientDeepslateBlock;
import net.mcreator.thedeepvoid.block.InfestedRottenRootsBlock;
import net.mcreator.thedeepvoid.block.InfestedRottenLogBlock;
import net.mcreator.thedeepvoid.block.InfestedBoneCrawlerEggGenerateBlock;
import net.mcreator.thedeepvoid.block.InfestedBoneCrawlerEggBlock;
import net.mcreator.thedeepvoid.block.InactivePeepingRootsBlock;
import net.mcreator.thedeepvoid.block.InactiveInfestedRottenRootsBlock;
import net.mcreator.thedeepvoid.block.IchorLanternBlock;
import net.mcreator.thedeepvoid.block.HugeEyeVineStemBlock;
import net.mcreator.thedeepvoid.block.HeartOfTheMindBlock;
import net.mcreator.thedeepvoid.block.HeadOfTheWeaverBlock;
import net.mcreator.thedeepvoid.block.HeadOfThePrimordialCrawlerBlock;
import net.mcreator.thedeepvoid.block.HeadOfTheHunterBlock;
import net.mcreator.thedeepvoid.block.HeadOfTheHivemindBlock;
import net.mcreator.thedeepvoid.block.HeadOfTheApostleBlock;
import net.mcreator.thedeepvoid.block.HardFleshStairsBlock;
import net.mcreator.thedeepvoid.block.HardFleshSlabBlock;
import net.mcreator.thedeepvoid.block.HardFleshBlockBlock;
import net.mcreator.thedeepvoid.block.HangingRottenFleshBlock;
import net.mcreator.thedeepvoid.block.HangingMarrowBlock;
import net.mcreator.thedeepvoid.block.HangingGooBlock;
import net.mcreator.thedeepvoid.block.HangedLurkerHeadBlock;
import net.mcreator.thedeepvoid.block.GroundBonesPlantBlock;
import net.mcreator.thedeepvoid.block.GroundBonesBlock;
import net.mcreator.thedeepvoid.block.GrimSoilBlock;
import net.mcreator.thedeepvoid.block.GrimBlockBlock;
import net.mcreator.thedeepvoid.block.GreenEyeVineBlock;
import net.mcreator.thedeepvoid.block.GreenCandlestickBlock;
import net.mcreator.thedeepvoid.block.GreenCandelabraBlock;
import net.mcreator.thedeepvoid.block.GrayCandlestickBlock;
import net.mcreator.thedeepvoid.block.GrayCandelabraBlock;
import net.mcreator.thedeepvoid.block.GoreStemsBlock;
import net.mcreator.thedeepvoid.block.GooWebBlock;
import net.mcreator.thedeepvoid.block.GooGrowthBlock;
import net.mcreator.thedeepvoid.block.GooCoverBlockBlock;
import net.mcreator.thedeepvoid.block.GooCoverBlock;
import net.mcreator.thedeepvoid.block.GooBricksBlock;
import net.mcreator.thedeepvoid.block.GooBrickWallBlock;
import net.mcreator.thedeepvoid.block.GooBrickStairsBlock;
import net.mcreator.thedeepvoid.block.GooBrickSlabBlock;
import net.mcreator.thedeepvoid.block.GoldenRottenCrateBlock;
import net.mcreator.thedeepvoid.block.GoldenRegurgitatedMatterBlock;
import net.mcreator.thedeepvoid.block.GoldenFleshCrateBlock;
import net.mcreator.thedeepvoid.block.GluttonBlockBlock;
import net.mcreator.thedeepvoid.block.GapingPorousFleshBlock;
import net.mcreator.thedeepvoid.block.FramedSulfurGlassPaneBlock;
import net.mcreator.thedeepvoid.block.FramedSulfurGlassBlock;
import net.mcreator.thedeepvoid.block.FramedGlassPaneBlock;
import net.mcreator.thedeepvoid.block.FramedGlassBlock;
import net.mcreator.thedeepvoid.block.FramedCinnabarGlassPaneBlock;
import net.mcreator.thedeepvoid.block.FramedCinnabarGlassBlock;
import net.mcreator.thedeepvoid.block.FramedBismuthGlassPaneBlock;
import net.mcreator.thedeepvoid.block.FramedBismuthGlassBlock;
import net.mcreator.thedeepvoid.block.FossilizedFleshBlock;
import net.mcreator.thedeepvoid.block.FleshyRottenBoneBlockBlock;
import net.mcreator.thedeepvoid.block.FleshyOldBoneBlockBlock;
import net.mcreator.thedeepvoid.block.FleshyBoneBlockBlock;
import net.mcreator.thedeepvoid.block.FleshStairsBlock;
import net.mcreator.thedeepvoid.block.FleshSlabBlock;
import net.mcreator.thedeepvoid.block.FleshCrateBlock;
import net.mcreator.thedeepvoid.block.FleshBricksBlock;
import net.mcreator.thedeepvoid.block.FleshBrickWallBlock;
import net.mcreator.thedeepvoid.block.FleshBrickStairsBlock;
import net.mcreator.thedeepvoid.block.FleshBrickSlabBlock;
import net.mcreator.thedeepvoid.block.FleshBloodstoneOreBlock;
import net.mcreator.thedeepvoid.block.FleshBlockBlock;
import net.mcreator.thedeepvoid.block.FerrymanLanternBlock;
import net.mcreator.thedeepvoid.block.FakeTorchBlock;
import net.mcreator.thedeepvoid.block.FakeBedrockStairsBlock;
import net.mcreator.thedeepvoid.block.FakeBedrockSlabBlock;
import net.mcreator.thedeepvoid.block.FakeBedrockBlock;
import net.mcreator.thedeepvoid.block.EyeVineStemBlock;
import net.mcreator.thedeepvoid.block.EyeVineBlock;
import net.mcreator.thedeepvoid.block.EyeTendonsBlock;
import net.mcreator.thedeepvoid.block.EyeOfTheHiveWatcherBlock;
import net.mcreator.thedeepvoid.block.EyeLanternBlock;
import net.mcreator.thedeepvoid.block.EyeFleshBricksBlock;
import net.mcreator.thedeepvoid.block.EyeFleshBrickStairsBlock;
import net.mcreator.thedeepvoid.block.EyeFleshBrickSlabBlock;
import net.mcreator.thedeepvoid.block.EyeFleshBlockBlock;
import net.mcreator.thedeepvoid.block.EyeCakeBlock;
import net.mcreator.thedeepvoid.block.EmptySolidAmbrosiaBlock;
import net.mcreator.thedeepvoid.block.DesolateStemBlock;
import net.mcreator.thedeepvoid.block.DesolateSoilBlock;
import net.mcreator.thedeepvoid.block.DesolateSoilActiveBlock;
import net.mcreator.thedeepvoid.block.DesolateLichenBlock;
import net.mcreator.thedeepvoid.block.DesolateGrowthBlock;
import net.mcreator.thedeepvoid.block.DesolateBricksBlock;
import net.mcreator.thedeepvoid.block.DesolateBrickWallBlock;
import net.mcreator.thedeepvoid.block.DesolateBrickStairsBlock;
import net.mcreator.thedeepvoid.block.DesolateBrickSlabBlock;
import net.mcreator.thedeepvoid.block.DeepslateSerratedStalagmiteMiddleBlock;
import net.mcreator.thedeepvoid.block.DeepslateSerratedStalagmiteFrustumBlock;
import net.mcreator.thedeepvoid.block.DeepslateSerratedStalagmiteBlock;
import net.mcreator.thedeepvoid.block.DeepslateSerratedStalagmiteBaseBlock;
import net.mcreator.thedeepvoid.block.DeepslateSarcophagusBlockBlock;
import net.mcreator.thedeepvoid.block.DeepslateSarcophagusBlock;
import net.mcreator.thedeepvoid.block.DeepslateLavaGeyserBlock;
import net.mcreator.thedeepvoid.block.DeepVoidRedstoneOreBlock;
import net.mcreator.thedeepvoid.block.DeepVoidLapisLazuliOreBlock;
import net.mcreator.thedeepvoid.block.DeepVoidIronOreBlock;
import net.mcreator.thedeepvoid.block.DeepVoidGoldOreBlock;
import net.mcreator.thedeepvoid.block.DeepVoidDiamondOreBlock;
import net.mcreator.thedeepvoid.block.DeepVoidCopperOreBlock;
import net.mcreator.thedeepvoid.block.DeadFerrymanBlock;
import net.mcreator.thedeepvoid.block.DarkSteelDepositBlock;
import net.mcreator.thedeepvoid.block.DarkSteelChainBlock;
import net.mcreator.thedeepvoid.block.DarkSteelBarsBlock;
import net.mcreator.thedeepvoid.block.CyanCandlestickBlock;
import net.mcreator.thedeepvoid.block.CyanCandelabraBlock;
import net.mcreator.thedeepvoid.block.CutRottenBoneBlockStairsBlock;
import net.mcreator.thedeepvoid.block.CutRottenBoneBlockSlabBlock;
import net.mcreator.thedeepvoid.block.CutRottenBoneBlockBlock;
import net.mcreator.thedeepvoid.block.CrystallizedIchorBlock;
import net.mcreator.thedeepvoid.block.CrumblingMonolithicStoneBlock;
import net.mcreator.thedeepvoid.block.CrumblingDeepslateBlock;
import net.mcreator.thedeepvoid.block.CrumblingBedrockBlock;
import net.mcreator.thedeepvoid.block.CrackedBedrockStairsBlock;
import net.mcreator.thedeepvoid.block.CrackedBedrockSlabBlock;
import net.mcreator.thedeepvoid.block.CrackedBedrockBlock;
import net.mcreator.thedeepvoid.block.CrackedAncientDeepslateBricksBlock;
import net.mcreator.thedeepvoid.block.CoveredSkullPileBlock;
import net.mcreator.thedeepvoid.block.CoveredCorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.CoveredCorpseBlock;
import net.mcreator.thedeepvoid.block.CoveredBonePileBlock;
import net.mcreator.thedeepvoid.block.CorpseSpawnGraveyardBlock;
import net.mcreator.thedeepvoid.block.CorpseSpawnBlock;
import net.mcreator.thedeepvoid.block.CorpsePileBlock;
import net.mcreator.thedeepvoid.block.CorpseInACageBlock;
import net.mcreator.thedeepvoid.block.CorpseChandelierBlock;
import net.mcreator.thedeepvoid.block.CorpseBlossomBlock;
import net.mcreator.thedeepvoid.block.CorpseBlock;
import net.mcreator.thedeepvoid.block.ConnectedMarrowBlock;
import net.mcreator.thedeepvoid.block.ConnectedHangingGooBlock;
import net.mcreator.thedeepvoid.block.ConnectedAmbrosiaStrandsBlock;
import net.mcreator.thedeepvoid.block.CompactBonePileStairsBlock;
import net.mcreator.thedeepvoid.block.CompactBonePileSlabBlock;
import net.mcreator.thedeepvoid.block.CompactBonePileBlock;
import net.mcreator.thedeepvoid.block.CobbledAncientDeepslateBlock;
import net.mcreator.thedeepvoid.block.CinnabarOreBlock;
import net.mcreator.thedeepvoid.block.CinnabarMonolithStoneWallBlock;
import net.mcreator.thedeepvoid.block.CinnabarMonolithStoneStairsBlock;
import net.mcreator.thedeepvoid.block.CinnabarMonolithStoneSlabBlock;
import net.mcreator.thedeepvoid.block.CinnabarMonolithStoneBlock;
import net.mcreator.thedeepvoid.block.CinnabarLanternBlock;
import net.mcreator.thedeepvoid.block.CinnabarGlassPaneBlock;
import net.mcreator.thedeepvoid.block.CinnabarGlassBlock;
import net.mcreator.thedeepvoid.block.CinnabarChainBlock;
import net.mcreator.thedeepvoid.block.ChiseledVoidlightBlock;
import net.mcreator.thedeepvoid.block.ChiseledSolidVoidBlockBlock;
import net.mcreator.thedeepvoid.block.ChiseledDesolateBricksBlock;
import net.mcreator.thedeepvoid.block.ChiseledCutRottenBoneBlockBlock;
import net.mcreator.thedeepvoid.block.ChiseledAncientDeepslateBricksBlock;
import net.mcreator.thedeepvoid.block.CaveGrowthBlock;
import net.mcreator.thedeepvoid.block.CarrionBlock;
import net.mcreator.thedeepvoid.block.CanopyRottenGrassBlock;
import net.mcreator.thedeepvoid.block.CanopyBoneMarrowBlock;
import net.mcreator.thedeepvoid.block.CandlestickBlock;
import net.mcreator.thedeepvoid.block.CandelabraFootBlock;
import net.mcreator.thedeepvoid.block.CandelabraBlock;
import net.mcreator.thedeepvoid.block.CageBlock;
import net.mcreator.thedeepvoid.block.BrownEyeVineBlock;
import net.mcreator.thedeepvoid.block.BrownCandlestickBlock;
import net.mcreator.thedeepvoid.block.BrownCandelabraBlock;
import net.mcreator.thedeepvoid.block.BoneSpikesBlock;
import net.mcreator.thedeepvoid.block.BonePileBricksBlock;
import net.mcreator.thedeepvoid.block.BonePileBrickWallBlock;
import net.mcreator.thedeepvoid.block.BonePileBrickStairsBlock;
import net.mcreator.thedeepvoid.block.BonePileBrickSlabBlock;
import net.mcreator.thedeepvoid.block.BoneMarrowBlock;
import net.mcreator.thedeepvoid.block.BoneCrawlerEggGenerateBlock;
import net.mcreator.thedeepvoid.block.BoneCrawlerEggBlock;
import net.mcreator.thedeepvoid.block.BlueFireBlock;
import net.mcreator.thedeepvoid.block.BlueCandlestickBlock;
import net.mcreator.thedeepvoid.block.BlueCandelabraBlock;
import net.mcreator.thedeepvoid.block.BlossomingDesolateLichenBlock;
import net.mcreator.thedeepvoid.block.BloodstoneOreBlock;
import net.mcreator.thedeepvoid.block.BloodLanternBlock;
import net.mcreator.thedeepvoid.block.BlockOfVisceraBlock;
import net.mcreator.thedeepvoid.block.BlockOfUmbriumBlock;
import net.mcreator.thedeepvoid.block.BlockOfSulfurBlock;
import net.mcreator.thedeepvoid.block.BlockOfSoulFusedIngotsBlock;
import net.mcreator.thedeepvoid.block.BlockOfSkullPileBlock;
import net.mcreator.thedeepvoid.block.BlockOfShatteredBoneBlock;
import net.mcreator.thedeepvoid.block.BlockOfRottenShatteredBoneBlock;
import net.mcreator.thedeepvoid.block.BlockOfRottenBonePileBlock;
import net.mcreator.thedeepvoid.block.BlockOfRottenBoneMarrowBlock;
import net.mcreator.thedeepvoid.block.BlockOfRefinedOnyxBlock;
import net.mcreator.thedeepvoid.block.BlockOfRefinedBismuthBlock;
import net.mcreator.thedeepvoid.block.BlockOfRawSulfurBlock;
import net.mcreator.thedeepvoid.block.BlockOfRawCinnabarBlock;
import net.mcreator.thedeepvoid.block.BlockOfOnyxBlock;
import net.mcreator.thedeepvoid.block.BlockOfOldShatteredBoneBlock;
import net.mcreator.thedeepvoid.block.BlockOfMistedBonePileBlock;
import net.mcreator.thedeepvoid.block.BlockOfMarrowBlock;
import net.mcreator.thedeepvoid.block.BlockOfLavenditeBlock;
import net.mcreator.thedeepvoid.block.BlockOfHardFleshBlock;
import net.mcreator.thedeepvoid.block.BlockOfGooBlock;
import net.mcreator.thedeepvoid.block.BlockOfDarkSteelBlock;
import net.mcreator.thedeepvoid.block.BlockOfCinnabarBlock;
import net.mcreator.thedeepvoid.block.BlockOfBonePileBlock;
import net.mcreator.thedeepvoid.block.BlockOfBoneMarrowBlock;
import net.mcreator.thedeepvoid.block.BlockOfBoneBlock;
import net.mcreator.thedeepvoid.block.BlockOfBloodstoneBlock;
import net.mcreator.thedeepvoid.block.BlockOfBlackMossBlock;
import net.mcreator.thedeepvoid.block.BlockOfBismuthBlock;
import net.mcreator.thedeepvoid.block.BlockOfAncientOnyxBlock;
import net.mcreator.thedeepvoid.block.BlockOfAncientFleshBlock;
import net.mcreator.thedeepvoid.block.BlackCandlestickBlock;
import net.mcreator.thedeepvoid.block.BlackCandelabraBlock;
import net.mcreator.thedeepvoid.block.BismuthOreBlock;
import net.mcreator.thedeepvoid.block.BismuthLanternBlock;
import net.mcreator.thedeepvoid.block.BismuthGlassPaneBlock;
import net.mcreator.thedeepvoid.block.BismuthGlassBlock;
import net.mcreator.thedeepvoid.block.BismuthBricksBlock;
import net.mcreator.thedeepvoid.block.BismuthBrickStairsBlock;
import net.mcreator.thedeepvoid.block.BismuthBrickSlabBlock;
import net.mcreator.thedeepvoid.block.BigYellowEyeBlock;
import net.mcreator.thedeepvoid.block.BigToothBlock;
import net.mcreator.thedeepvoid.block.BigTeethBlock;
import net.mcreator.thedeepvoid.block.BigSmokeVentCornerBlock;
import net.mcreator.thedeepvoid.block.BigSmokeVentBlock;
import net.mcreator.thedeepvoid.block.BigRedEyeBlock;
import net.mcreator.thedeepvoid.block.BigPurpleEyeBlock;
import net.mcreator.thedeepvoid.block.BigGreenEyeBlock;
import net.mcreator.thedeepvoid.block.BigBrownEyeBlock;
import net.mcreator.thedeepvoid.block.BigBlueEyeBlock;
import net.mcreator.thedeepvoid.block.AttractorOnBlock;
import net.mcreator.thedeepvoid.block.AttractorBlock;
import net.mcreator.thedeepvoid.block.AshenVoidFernBlock;
import net.mcreator.thedeepvoid.block.AshPileBlock;
import net.mcreator.thedeepvoid.block.AshBricksBlock;
import net.mcreator.thedeepvoid.block.AshBrickWallBlock;
import net.mcreator.thedeepvoid.block.AshBrickStairsBlock;
import net.mcreator.thedeepvoid.block.AshBrickSlabBlock;
import net.mcreator.thedeepvoid.block.AshBlockBlock;
import net.mcreator.thedeepvoid.block.AncientUrnsGenerateBlock;
import net.mcreator.thedeepvoid.block.AncientUrnsBlock;
import net.mcreator.thedeepvoid.block.AncientPotBlockBlock;
import net.mcreator.thedeepvoid.block.AncientPotBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateWallBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateStairsBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateSpikeTrapBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateSlabBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateSawTrapTrackBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateSawTrapBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateDartTrapBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateBricksBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateBrickWallBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateBrickStairsBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateBrickSlabBlock;
import net.mcreator.thedeepvoid.block.AncientDeepslateBlock;
import net.mcreator.thedeepvoid.block.AncientBookshelfBlock;
import net.mcreator.thedeepvoid.block.AmbrosialFleshBlockBlock;
import net.mcreator.thedeepvoid.block.AmbrosiaStrandsBlock;
import net.mcreator.thedeepvoid.block.ActiveFleshBlockBlock;
import net.mcreator.thedeepvoid.TheDeepVoidMod;

public class TheDeepVoidModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TheDeepVoidMod.MODID);
	public static final RegistryObject<Block> BLOCK_OF_BONE_PILE = REGISTRY.register("block_of_bone_pile", () -> new BlockOfBonePileBlock());
	public static final RegistryObject<Block> PILE_OF_BONES = REGISTRY.register("pile_of_bones", () -> new PileOfBonesBlock());
	public static final RegistryObject<Block> ROTTEN_BONE_BLOCK = REGISTRY.register("rotten_bone_block", () -> new RottenBoneBlockBlock());
	public static final RegistryObject<Block> BONE_MARROW = REGISTRY.register("bone_marrow", () -> new BoneMarrowBlock());
	public static final RegistryObject<Block> CORPSE = REGISTRY.register("corpse", () -> new CorpseBlock());
	public static final RegistryObject<Block> CORPSE_SPAWN = REGISTRY.register("corpse_spawn", () -> new CorpseSpawnBlock());
	public static final RegistryObject<Block> ROTTEN_GRASS = REGISTRY.register("rotten_grass", () -> new RottenGrassBlock());
	public static final RegistryObject<Block> MOSSY_BONE_PILE = REGISTRY.register("mossy_bone_pile", () -> new MossyBonePileBlock());
	public static final RegistryObject<Block> ONYX_ORE = REGISTRY.register("onyx_ore", () -> new OnyxOreBlock());
	public static final RegistryObject<Block> FERRYMAN_LANTERN = REGISTRY.register("ferryman_lantern", () -> new FerrymanLanternBlock());
	public static final RegistryObject<Block> BLOCK_OF_ONYX = REGISTRY.register("block_of_onyx", () -> new BlockOfOnyxBlock());
	public static final RegistryObject<Block> CAVE_GROWTH = REGISTRY.register("cave_growth", () -> new CaveGrowthBlock());
	public static final RegistryObject<Block> VOID_CORE = REGISTRY.register("void_core", () -> new VoidCoreBlock());
	public static final RegistryObject<Block> ANCIENT_BOOKSHELF = REGISTRY.register("ancient_bookshelf", () -> new AncientBookshelfBlock());
	public static final RegistryObject<Block> CUT_ROTTEN_BONE_BLOCK = REGISTRY.register("cut_rotten_bone_block", () -> new CutRottenBoneBlockBlock());
	public static final RegistryObject<Block> CUT_ROTTEN_BONE_BLOCK_STAIRS = REGISTRY.register("cut_rotten_bone_block_stairs", () -> new CutRottenBoneBlockStairsBlock());
	public static final RegistryObject<Block> CUT_ROTTEN_BONE_BLOCK_SLAB = REGISTRY.register("cut_rotten_bone_block_slab", () -> new CutRottenBoneBlockSlabBlock());
	public static final RegistryObject<Block> CHISELED_CUT_ROTTEN_BONE_BLOCK = REGISTRY.register("chiseled_cut_rotten_bone_block", () -> new ChiseledCutRottenBoneBlockBlock());
	public static final RegistryObject<Block> ROTTEN_LOG = REGISTRY.register("rotten_log", () -> new RottenLogBlock());
	public static final RegistryObject<Block> ROTTEN_WOOD = REGISTRY.register("rotten_wood", () -> new RottenWoodBlock());
	public static final RegistryObject<Block> GLUTTON_BLOCK = REGISTRY.register("glutton_block", () -> new GluttonBlockBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE = REGISTRY.register("ancient_deepslate", () -> new AncientDeepslateBlock());
	public static final RegistryObject<Block> LAVENDITE_ORE = REGISTRY.register("lavendite_ore", () -> new LavenditeOreBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_STAIRS = REGISTRY.register("ancient_deepslate_stairs", () -> new AncientDeepslateStairsBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_SLAB = REGISTRY.register("ancient_deepslate_slab", () -> new AncientDeepslateSlabBlock());
	public static final RegistryObject<Block> BLOCK_OF_LAVENDITE = REGISTRY.register("block_of_lavendite", () -> new BlockOfLavenditeBlock());
	public static final RegistryObject<Block> HANGING_MARROW = REGISTRY.register("hanging_marrow", () -> new HangingMarrowBlock());
	public static final RegistryObject<Block> FLESH_BLOCK = REGISTRY.register("flesh_block", () -> new FleshBlockBlock());
	public static final RegistryObject<Block> PUSTULENT_FLESH_BLOCK = REGISTRY.register("pustulent_flesh_block", () -> new PustulentFleshBlockBlock());
	public static final RegistryObject<Block> PUS_FLOWER = REGISTRY.register("pus_flower", () -> new PusFlowerBlock());
	public static final RegistryObject<Block> TENDRILS = REGISTRY.register("tendrils", () -> new TendrilsBlock());
	public static final RegistryObject<Block> TEETH = REGISTRY.register("teeth", () -> new TeethBlock());
	public static final RegistryObject<Block> EYE_VINE_STEM = REGISTRY.register("eye_vine_stem", () -> new EyeVineStemBlock());
	public static final RegistryObject<Block> EYE_VINE = REGISTRY.register("eye_vine", () -> new EyeVineBlock());
	public static final RegistryObject<Block> PUS_SACK = REGISTRY.register("pus_sack", () -> new PusSackBlock());
	public static final RegistryObject<Block> GREEN_EYE_VINE = REGISTRY.register("green_eye_vine", () -> new GreenEyeVineBlock());
	public static final RegistryObject<Block> RED_EYE_VINE = REGISTRY.register("red_eye_vine", () -> new RedEyeVineBlock());
	public static final RegistryObject<Block> YELLOW_EYE_VINE = REGISTRY.register("yellow_eye_vine", () -> new YellowEyeVineBlock());
	public static final RegistryObject<Block> DESOLATE_SOIL = REGISTRY.register("desolate_soil", () -> new DesolateSoilBlock());
	public static final RegistryObject<Block> DESOLATE_GROWTH = REGISTRY.register("desolate_growth", () -> new DesolateGrowthBlock());
	public static final RegistryObject<Block> DESOLATE_STEM = REGISTRY.register("desolate_stem", () -> new DesolateStemBlock());
	public static final RegistryObject<Block> VOIDLIGHT = REGISTRY.register("voidlight", () -> new VoidlightBlock());
	public static final RegistryObject<Block> DESOLATE_LICHEN = REGISTRY.register("desolate_lichen", () -> new DesolateLichenBlock());
	public static final RegistryObject<Block> CRACKED_BEDROCK = REGISTRY.register("cracked_bedrock", () -> new CrackedBedrockBlock());
	public static final RegistryObject<Block> DEEPSLATE_SERRATED_STALAGMITE = REGISTRY.register("deepslate_serrated_stalagmite", () -> new DeepslateSerratedStalagmiteBlock());
	public static final RegistryObject<Block> DEEPSLATE_SERRATED_STALAGMITE_BASE = REGISTRY.register("deepslate_serrated_stalagmite_base", () -> new DeepslateSerratedStalagmiteBaseBlock());
	public static final RegistryObject<Block> DEEPSLATE_SERRATED_STALAGMITE_MIDDLE = REGISTRY.register("deepslate_serrated_stalagmite_middle", () -> new DeepslateSerratedStalagmiteMiddleBlock());
	public static final RegistryObject<Block> DEEPSLATE_SERRATED_STALAGMITE_FRUSTUM = REGISTRY.register("deepslate_serrated_stalagmite_frustum", () -> new DeepslateSerratedStalagmiteFrustumBlock());
	public static final RegistryObject<Block> LIQUID_VOID = REGISTRY.register("liquid_void", () -> new LiquidVoidBlock());
	public static final RegistryObject<Block> VOID_FILLED_SPONGE = REGISTRY.register("void_filled_sponge", () -> new VoidFilledSpongeBlock());
	public static final RegistryObject<Block> DEEPSLATE_SARCOPHAGUS = REGISTRY.register("deepslate_sarcophagus", () -> new DeepslateSarcophagusBlock());
	public static final RegistryObject<Block> VOID_ROOTS = REGISTRY.register("void_roots", () -> new VoidRootsBlock());
	public static final RegistryObject<Block> VOID_ROSE = REGISTRY.register("void_rose", () -> new VoidRoseBlock());
	public static final RegistryObject<Block> VOID_FERN = REGISTRY.register("void_fern", () -> new VoidFernBlock());
	public static final RegistryObject<Block> ROTTEN_PLANKS = REGISTRY.register("rotten_planks", () -> new RottenPlanksBlock());
	public static final RegistryObject<Block> ROTTEN_STAIRS = REGISTRY.register("rotten_stairs", () -> new RottenStairsBlock());
	public static final RegistryObject<Block> ROTTEN_SLAB = REGISTRY.register("rotten_slab", () -> new RottenSlabBlock());
	public static final RegistryObject<Block> FLESH_BRICKS = REGISTRY.register("flesh_bricks", () -> new FleshBricksBlock());
	public static final RegistryObject<Block> FLESH_BRICK_STAIRS = REGISTRY.register("flesh_brick_stairs", () -> new FleshBrickStairsBlock());
	public static final RegistryObject<Block> FLESH_BRICK_SLAB = REGISTRY.register("flesh_brick_slab", () -> new FleshBrickSlabBlock());
	public static final RegistryObject<Block> PUSTULENT_FLESH_BRICKS = REGISTRY.register("pustulent_flesh_bricks", () -> new PustulentFleshBricksBlock());
	public static final RegistryObject<Block> ROTTEN_DOOR = REGISTRY.register("rotten_door", () -> new RottenDoorBlock());
	public static final RegistryObject<Block> ROTTEN_TRAPDOOR = REGISTRY.register("rotten_trapdoor", () -> new RottenTrapdoorBlock());
	public static final RegistryObject<Block> WALL_CORPSE = REGISTRY.register("wall_corpse", () -> new WallCorpseBlock());
	public static final RegistryObject<Block> CANOPY_ROTTEN_GRASS = REGISTRY.register("canopy_rotten_grass", () -> new CanopyRottenGrassBlock());
	public static final RegistryObject<Block> CANOPY_BONE_MARROW = REGISTRY.register("canopy_bone_marrow", () -> new CanopyBoneMarrowBlock());
	public static final RegistryObject<Block> ASH_PILE = REGISTRY.register("ash_pile", () -> new AshPileBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_BRICKS = REGISTRY.register("ancient_deepslate_bricks", () -> new AncientDeepslateBricksBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_BRICK_STAIRS = REGISTRY.register("ancient_deepslate_brick_stairs", () -> new AncientDeepslateBrickStairsBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_BRICK_SLAB = REGISTRY.register("ancient_deepslate_brick_slab", () -> new AncientDeepslateBrickSlabBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_WALL = REGISTRY.register("ancient_deepslate_wall", () -> new AncientDeepslateWallBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_BRICK_WALL = REGISTRY.register("ancient_deepslate_brick_wall", () -> new AncientDeepslateBrickWallBlock());
	public static final RegistryObject<Block> COBBLED_ANCIENT_DEEPSLATE = REGISTRY.register("cobbled_ancient_deepslate", () -> new CobbledAncientDeepslateBlock());
	public static final RegistryObject<Block> SMOOTH_ANCIENT_DEEPSLATE = REGISTRY.register("smooth_ancient_deepslate", () -> new SmoothAncientDeepslateBlock());
	public static final RegistryObject<Block> SMOOTH_ANCIENT_DEEPSLATE_SLAB = REGISTRY.register("smooth_ancient_deepslate_slab", () -> new SmoothAncientDeepslateSlabBlock());
	public static final RegistryObject<Block> PUSTULENT_FLESH_BRICK_STAIRS = REGISTRY.register("pustulent_flesh_brick_stairs", () -> new PustulentFleshBrickStairsBlock());
	public static final RegistryObject<Block> PUSTULENT_FLESH_BRICK_SLAB = REGISTRY.register("pustulent_flesh_brick_slab", () -> new PustulentFleshBrickSlabBlock());
	public static final RegistryObject<Block> DESOLATE_BRICKS = REGISTRY.register("desolate_bricks", () -> new DesolateBricksBlock());
	public static final RegistryObject<Block> DESOLATE_BRICK_STAIRS = REGISTRY.register("desolate_brick_stairs", () -> new DesolateBrickStairsBlock());
	public static final RegistryObject<Block> DESOLATE_BRICK_SLAB = REGISTRY.register("desolate_brick_slab", () -> new DesolateBrickSlabBlock());
	public static final RegistryObject<Block> FLESH_BRICK_WALL = REGISTRY.register("flesh_brick_wall", () -> new FleshBrickWallBlock());
	public static final RegistryObject<Block> DESOLATE_BRICK_WALL = REGISTRY.register("desolate_brick_wall", () -> new DesolateBrickWallBlock());
	public static final RegistryObject<Block> BISMUTH_ORE = REGISTRY.register("bismuth_ore", () -> new BismuthOreBlock());
	public static final RegistryObject<Block> TEETH_TRAP = REGISTRY.register("teeth_trap", () -> new TeethTrapBlock());
	public static final RegistryObject<Block> TEETH_BLOCK = REGISTRY.register("teeth_block", () -> new TeethBlockBlock());
	public static final RegistryObject<Block> ASH_BLOCK = REGISTRY.register("ash_block", () -> new AshBlockBlock());
	public static final RegistryObject<Block> CORPSE_SPAWN_GRAVEYARD = REGISTRY.register("corpse_spawn_graveyard", () -> new CorpseSpawnGraveyardBlock());
	public static final RegistryObject<Block> EYE_LANTERN = REGISTRY.register("eye_lantern", () -> new EyeLanternBlock());
	public static final RegistryObject<Block> BLOCK_OF_BISMUTH = REGISTRY.register("block_of_bismuth", () -> new BlockOfBismuthBlock());
	public static final RegistryObject<Block> BLOCK_OF_REFINED_BISMUTH = REGISTRY.register("block_of_refined_bismuth", () -> new BlockOfRefinedBismuthBlock());
	public static final RegistryObject<Block> ROTTEN_FOSSIL = REGISTRY.register("rotten_fossil", () -> new RottenFossilBlock());
	public static final RegistryObject<Block> SMOKE_VENT = REGISTRY.register("smoke_vent", () -> new SmokeVentBlock());
	public static final RegistryObject<Block> BISMUTH_LANTERN = REGISTRY.register("bismuth_lantern", () -> new BismuthLanternBlock());
	public static final RegistryObject<Block> ROTTEN_MOSS = REGISTRY.register("rotten_moss", () -> new RottenMossBlock());
	public static final RegistryObject<Block> BISMUTH_GLASS = REGISTRY.register("bismuth_glass", () -> new BismuthGlassBlock());
	public static final RegistryObject<Block> CONNECTED_MARROW = REGISTRY.register("connected_marrow", () -> new ConnectedMarrowBlock());
	public static final RegistryObject<Block> SULFUR_ORE = REGISTRY.register("sulfur_ore", () -> new SulfurOreBlock());
	public static final RegistryObject<Block> SULFUR_TNT = REGISTRY.register("sulfur_tnt", () -> new SulfurTntBlock());
	public static final RegistryObject<Block> SULFUR_POWDER = REGISTRY.register("sulfur_powder", () -> new SulfurPowderBlock());
	public static final RegistryObject<Block> BLOCK_OF_SULFUR = REGISTRY.register("block_of_sulfur", () -> new BlockOfSulfurBlock());
	public static final RegistryObject<Block> BLUE_FIRE = REGISTRY.register("blue_fire", () -> new BlueFireBlock());
	public static final RegistryObject<Block> BLOCK_OF_RAW_SULFUR = REGISTRY.register("block_of_raw_sulfur", () -> new BlockOfRawSulfurBlock());
	public static final RegistryObject<Block> SULFUR_GLASS = REGISTRY.register("sulfur_glass", () -> new SulfurGlassBlock());
	public static final RegistryObject<Block> SULFUR_LANTERN = REGISTRY.register("sulfur_lantern", () -> new SulfurLanternBlock());
	public static final RegistryObject<Block> INFESTED_ROTTEN_LOG = REGISTRY.register("infested_rotten_log", () -> new InfestedRottenLogBlock());
	public static final RegistryObject<Block> WATCHING_WILLOW_SAPLING = REGISTRY.register("watching_willow_sapling", () -> new WatchingWillowSaplingBlock());
	public static final RegistryObject<Block> VOIDRIUM_ORE = REGISTRY.register("voidrium_ore", () -> new UmbriumOreBlock());
	public static final RegistryObject<Block> BLOCK_OF_VOIDRIUM = REGISTRY.register("block_of_voidrium", () -> new BlockOfUmbriumBlock());
	public static final RegistryObject<Block> GRIM_BLOCK = REGISTRY.register("grim_block", () -> new GrimBlockBlock());
	public static final RegistryObject<Block> BIG_TEETH = REGISTRY.register("big_teeth", () -> new BigTeethBlock());
	public static final RegistryObject<Block> TEETH_TRAP_BLOCK = REGISTRY.register("teeth_trap_block", () -> new TeethTrapBlockBlock());
	public static final RegistryObject<Block> PEEPING_ROOTS = REGISTRY.register("peeping_roots", () -> new PeepingRootsBlock());
	public static final RegistryObject<Block> INACTIVE_PEEPING_ROOTS = REGISTRY.register("inactive_peeping_roots", () -> new InactivePeepingRootsBlock());
	public static final RegistryObject<Block> PILE_OF_BONES_BLOCK = REGISTRY.register("pile_of_bones_block", () -> new PileOfBonesBlockBlock());
	public static final RegistryObject<Block> FLESHY_BONE_BLOCK = REGISTRY.register("fleshy_bone_block", () -> new FleshyBoneBlockBlock());
	public static final RegistryObject<Block> HARD_FLESH_BLOCK = REGISTRY.register("hard_flesh_block", () -> new HardFleshBlockBlock());
	public static final RegistryObject<Block> HARD_FLESH_STAIRS = REGISTRY.register("hard_flesh_stairs", () -> new HardFleshStairsBlock());
	public static final RegistryObject<Block> HARD_FLESH_SLAB = REGISTRY.register("hard_flesh_slab", () -> new HardFleshSlabBlock());
	public static final RegistryObject<Block> CRACKED_BEDROCK_STAIRS = REGISTRY.register("cracked_bedrock_stairs", () -> new CrackedBedrockStairsBlock());
	public static final RegistryObject<Block> CRACKED_BEDROCK_SLAB = REGISTRY.register("cracked_bedrock_slab", () -> new CrackedBedrockSlabBlock());
	public static final RegistryObject<Block> FAKE_BEDROCK = REGISTRY.register("fake_bedrock", () -> new FakeBedrockBlock());
	public static final RegistryObject<Block> FAKE_BEDROCK_STAIRS = REGISTRY.register("fake_bedrock_stairs", () -> new FakeBedrockStairsBlock());
	public static final RegistryObject<Block> FAKE_BEDROCK_SLAB = REGISTRY.register("fake_bedrock_slab", () -> new FakeBedrockSlabBlock());
	public static final RegistryObject<Block> GORE_STEMS = REGISTRY.register("gore_stems", () -> new GoreStemsBlock());
	public static final RegistryObject<Block> GROUND_BONES = REGISTRY.register("ground_bones", () -> new GroundBonesBlock());
	public static final RegistryObject<Block> GROUND_BONES_PLANT = REGISTRY.register("ground_bones_plant", () -> new GroundBonesPlantBlock());
	public static final RegistryObject<Block> FOSSILIZED_FLESH = REGISTRY.register("fossilized_flesh", () -> new FossilizedFleshBlock());
	public static final RegistryObject<Block> BONE_PILE_BRICKS = REGISTRY.register("bone_pile_bricks", () -> new BonePileBricksBlock());
	public static final RegistryObject<Block> BONE_PILE_BRICK_STAIRS = REGISTRY.register("bone_pile_brick_stairs", () -> new BonePileBrickStairsBlock());
	public static final RegistryObject<Block> BONE_PILE_BRICK_SLAB = REGISTRY.register("bone_pile_brick_slab", () -> new BonePileBrickSlabBlock());
	public static final RegistryObject<Block> BONE_PILE_BRICK_WALL = REGISTRY.register("bone_pile_brick_wall", () -> new BonePileBrickWallBlock());
	public static final RegistryObject<Block> COMPACT_BONE_PILE = REGISTRY.register("compact_bone_pile", () -> new CompactBonePileBlock());
	public static final RegistryObject<Block> COMPACT_BONE_PILE_STAIRS = REGISTRY.register("compact_bone_pile_stairs", () -> new CompactBonePileStairsBlock());
	public static final RegistryObject<Block> COMPACT_BONE_PILE_SLAB = REGISTRY.register("compact_bone_pile_slab", () -> new CompactBonePileSlabBlock());
	public static final RegistryObject<Block> BISMUTH_GLASS_PANE = REGISTRY.register("bismuth_glass_pane", () -> new BismuthGlassPaneBlock());
	public static final RegistryObject<Block> SULFUR_GLASS_PANE = REGISTRY.register("sulfur_glass_pane", () -> new SulfurGlassPaneBlock());
	public static final RegistryObject<Block> ASHEN_VOID_FERN = REGISTRY.register("ashen_void_fern", () -> new AshenVoidFernBlock());
	public static final RegistryObject<Block> DEEPSLATE_SARCOPHAGUS_BLOCK = REGISTRY.register("deepslate_sarcophagus_block", () -> new DeepslateSarcophagusBlockBlock());
	public static final RegistryObject<Block> SMOOTH_ANCIENT_DEEPSLATE_STAIRS = REGISTRY.register("smooth_ancient_deepslate_stairs", () -> new SmoothAncientDeepslateStairsBlock());
	public static final RegistryObject<Block> ASH_BRICKS = REGISTRY.register("ash_bricks", () -> new AshBricksBlock());
	public static final RegistryObject<Block> ASH_BRICK_STAIRS = REGISTRY.register("ash_brick_stairs", () -> new AshBrickStairsBlock());
	public static final RegistryObject<Block> ASH_BRICK_SLAB = REGISTRY.register("ash_brick_slab", () -> new AshBrickSlabBlock());
	public static final RegistryObject<Block> ASH_BRICK_WALL = REGISTRY.register("ash_brick_wall", () -> new AshBrickWallBlock());
	public static final RegistryObject<Block> DEEPSLATE_LAVA_GEYSER = REGISTRY.register("deepslate_lava_geyser", () -> new DeepslateLavaGeyserBlock());
	public static final RegistryObject<Block> MONOLITHIC_STONE = REGISTRY.register("monolithic_stone", () -> new MonolithicStoneBlock());
	public static final RegistryObject<Block> SEER = REGISTRY.register("seer", () -> new SeerBlock());
	public static final RegistryObject<Block> CINNABAR_ORE = REGISTRY.register("cinnabar_ore", () -> new CinnabarOreBlock());
	public static final RegistryObject<Block> MONOLITHIC_STONE_STAIRS = REGISTRY.register("monolithic_stone_stairs", () -> new MonolithicStoneStairsBlock());
	public static final RegistryObject<Block> MONOLITHIC_STONE_SLAB = REGISTRY.register("monolithic_stone_slab", () -> new MonolithicStoneSlabBlock());
	public static final RegistryObject<Block> MONOLITHIC_STONE_WALL = REGISTRY.register("monolithic_stone_wall", () -> new MonolithicStoneWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_CINNABAR = REGISTRY.register("block_of_cinnabar", () -> new BlockOfCinnabarBlock());
	public static final RegistryObject<Block> MONOLITHIC_BRICKS = REGISTRY.register("monolithic_bricks", () -> new MonolithicBricksBlock());
	public static final RegistryObject<Block> MONOLITHIC_BRICK_STAIRS = REGISTRY.register("monolithic_brick_stairs", () -> new MonolithicBrickStairsBlock());
	public static final RegistryObject<Block> MONOLITHIC_BRICK_SLAB = REGISTRY.register("monolithic_brick_slab", () -> new MonolithicBrickSlabBlock());
	public static final RegistryObject<Block> MONOLITHIC_BRICK_WALL = REGISTRY.register("monolithic_brick_wall", () -> new MonolithicBrickWallBlock());
	public static final RegistryObject<Block> BLOSSOMING_DESOLATE_LICHEN = REGISTRY.register("blossoming_desolate_lichen", () -> new BlossomingDesolateLichenBlock());
	public static final RegistryObject<Block> SMOOTH_MONOLITHIC_STONE = REGISTRY.register("smooth_monolithic_stone", () -> new SmoothMonolithicStoneBlock());
	public static final RegistryObject<Block> SMOOTH_MONOLITHIC_STONE_STAIRS = REGISTRY.register("smooth_monolithic_stone_stairs", () -> new SmoothMonolithicStoneStairsBlock());
	public static final RegistryObject<Block> SMOOTH_MONOLITHIC_STONE_SLAB = REGISTRY.register("smooth_monolithic_stone_slab", () -> new SmoothMonolithicStoneSlabBlock());
	public static final RegistryObject<Block> TRANSFORMED_SEER = REGISTRY.register("transformed_seer", () -> new TransformedSeerBlock());
	public static final RegistryObject<Block> ROTTEN_FENCE = REGISTRY.register("rotten_fence", () -> new RottenFenceBlock());
	public static final RegistryObject<Block> ROTTEN_FENCE_GATE = REGISTRY.register("rotten_fence_gate", () -> new RottenFenceGateBlock());
	public static final RegistryObject<Block> ROTTEN_PRESSURE_PLATE = REGISTRY.register("rotten_pressure_plate", () -> new RottenPressurePlateBlock());
	public static final RegistryObject<Block> ROTTEN_BUTTON = REGISTRY.register("rotten_button", () -> new RottenButtonBlock());
	public static final RegistryObject<Block> BLOCK_OF_ANCIENT_FLESH = REGISTRY.register("block_of_ancient_flesh", () -> new BlockOfAncientFleshBlock());
	public static final RegistryObject<Block> CINNABAR_MONOLITH_STONE = REGISTRY.register("cinnabar_monolith_stone", () -> new CinnabarMonolithStoneBlock());
	public static final RegistryObject<Block> CINNABAR_MONOLITH_STONE_STAIRS = REGISTRY.register("cinnabar_monolith_stone_stairs", () -> new CinnabarMonolithStoneStairsBlock());
	public static final RegistryObject<Block> CINNABAR_MONOLITH_STONE_SLAB = REGISTRY.register("cinnabar_monolith_stone_slab", () -> new CinnabarMonolithStoneSlabBlock());
	public static final RegistryObject<Block> CINNABAR_MONOLITH_STONE_WALL = REGISTRY.register("cinnabar_monolith_stone_wall", () -> new CinnabarMonolithStoneWallBlock());
	public static final RegistryObject<Block> ATTRACTOR = REGISTRY.register("attractor", () -> new AttractorBlock());
	public static final RegistryObject<Block> ATTRACTOR_ON = REGISTRY.register("attractor_on", () -> new AttractorOnBlock());
	public static final RegistryObject<Block> EYE_FLESH_BLOCK = REGISTRY.register("eye_flesh_block", () -> new EyeFleshBlockBlock());
	public static final RegistryObject<Block> EYE_FLESH_BRICKS = REGISTRY.register("eye_flesh_bricks", () -> new EyeFleshBricksBlock());
	public static final RegistryObject<Block> EYE_FLESH_BRICK_STAIRS = REGISTRY.register("eye_flesh_brick_stairs", () -> new EyeFleshBrickStairsBlock());
	public static final RegistryObject<Block> EYE_FLESH_BRICK_SLAB = REGISTRY.register("eye_flesh_brick_slab", () -> new EyeFleshBrickSlabBlock());
	public static final RegistryObject<Block> PRIMORDIAL_STONE = REGISTRY.register("primordial_stone", () -> new PrimordialStoneBlock());
	public static final RegistryObject<Block> PRIMORDIAL_STONE_REPLICA = REGISTRY.register("primordial_stone_replica", () -> new PrimordialStoneReplicaBlock());
	public static final RegistryObject<Block> PRIMORDIAL_STONE_STAIRS = REGISTRY.register("primordial_stone_stairs", () -> new PrimordialStoneStairsBlock());
	public static final RegistryObject<Block> PRIMORDIAL_STONE_SLAB = REGISTRY.register("primordial_stone_slab", () -> new PrimordialStoneSlabBlock());
	public static final RegistryObject<Block> ROOTER = REGISTRY.register("rooter", () -> new RooterBlock());
	public static final RegistryObject<Block> ROOTER_ON = REGISTRY.register("rooter_on", () -> new RooterOnBlock());
	public static final RegistryObject<Block> SHORT_CIRCUIT_ROOTER = REGISTRY.register("short_circuit_rooter", () -> new ShortCircuitRooterBlock());
	public static final RegistryObject<Block> INFESTED_ROTTEN_ROOTS = REGISTRY.register("infested_rotten_roots", () -> new InfestedRottenRootsBlock());
	public static final RegistryObject<Block> INACTIVE_INFESTED_ROTTEN_ROOTS = REGISTRY.register("inactive_infested_rotten_roots", () -> new InactiveInfestedRottenRootsBlock());
	public static final RegistryObject<Block> CHISELED_ANCIENT_DEEPSLATE_BRICKS = REGISTRY.register("chiseled_ancient_deepslate_bricks", () -> new ChiseledAncientDeepslateBricksBlock());
	public static final RegistryObject<Block> CHISELED_DESOLATE_BRICKS = REGISTRY.register("chiseled_desolate_bricks", () -> new ChiseledDesolateBricksBlock());
	public static final RegistryObject<Block> ROTTEN_ROOTS = REGISTRY.register("rotten_roots", () -> new RottenRootsBlock());
	public static final RegistryObject<Block> POWERED_LAVA_GEYSER = REGISTRY.register("powered_lava_geyser", () -> new PoweredLavaGeyserBlock());
	public static final RegistryObject<Block> POWERED_LAVA_GEYSER_ON = REGISTRY.register("powered_lava_geyser_on", () -> new PoweredLavaGeyserOnBlock());
	public static final RegistryObject<Block> CRUMBLING_DEEPSLATE = REGISTRY.register("crumbling_deepslate", () -> new CrumblingDeepslateBlock());
	public static final RegistryObject<Block> CRUMBLING_BEDROCK = REGISTRY.register("crumbling_bedrock", () -> new CrumblingBedrockBlock());
	public static final RegistryObject<Block> COVERED_CORPSE = REGISTRY.register("covered_corpse", () -> new CoveredCorpseBlock());
	public static final RegistryObject<Block> COVERED_CORPSE_SPAWN = REGISTRY.register("covered_corpse_spawn", () -> new CoveredCorpseSpawnBlock());
	public static final RegistryObject<Block> CORPSE_CHANDELIER = REGISTRY.register("corpse_chandelier", () -> new CorpseChandelierBlock());
	public static final RegistryObject<Block> JACK_O_CORPSE = REGISTRY.register("jack_o_corpse", () -> new JackOCorpseBlock());
	public static final RegistryObject<Block> JACK_O_COVERED_CORPSE = REGISTRY.register("jack_o_covered_corpse", () -> new JackOCoveredCorpseBlock());
	public static final RegistryObject<Block> JACK_O_WALL_CORPSE = REGISTRY.register("jack_o_wall_corpse", () -> new JackOWallCorpseBlock());
	public static final RegistryObject<Block> LURKER_HEAD = REGISTRY.register("lurker_head", () -> new LurkerHeadBlock());
	public static final RegistryObject<Block> VOIDLIGHT_BRICKS = REGISTRY.register("voidlight_bricks", () -> new VoidlightBricksBlock());
	public static final RegistryObject<Block> VOIDLIGHT_BRICK_STAIRS = REGISTRY.register("voidlight_brick_stairs", () -> new VoidlightBrickStairsBlock());
	public static final RegistryObject<Block> VOIDLIGHT_BRICK_SLAB = REGISTRY.register("voidlight_brick_slab", () -> new VoidlightBrickSlabBlock());
	public static final RegistryObject<Block> VOIDLIGHT_BRICK_WALL = REGISTRY.register("voidlight_brick_wall", () -> new VoidlightBrickWallBlock());
	public static final RegistryObject<Block> CHISELED_VOIDLIGHT = REGISTRY.register("chiseled_voidlight", () -> new ChiseledVoidlightBlock());
	public static final RegistryObject<Block> DEAD_FERRYMAN = REGISTRY.register("dead_ferryman", () -> new DeadFerrymanBlock());
	public static final RegistryObject<Block> HANGED_LURKER_HEAD = REGISTRY.register("hanged_lurker_head", () -> new HangedLurkerHeadBlock());
	public static final RegistryObject<Block> BLOCK_OF_SKULL_PILE = REGISTRY.register("block_of_skull_pile", () -> new BlockOfSkullPileBlock());
	public static final RegistryObject<Block> GRIM_SOIL = REGISTRY.register("grim_soil", () -> new GrimSoilBlock());
	public static final RegistryObject<Block> COVERED_SKULL_PILE = REGISTRY.register("covered_skull_pile", () -> new CoveredSkullPileBlock());
	public static final RegistryObject<Block> COVERED_BONE_PILE = REGISTRY.register("covered_bone_pile", () -> new CoveredBonePileBlock());
	public static final RegistryObject<Block> HANGING_GOO = REGISTRY.register("hanging_goo", () -> new HangingGooBlock());
	public static final RegistryObject<Block> GOO_COVER = REGISTRY.register("goo_cover", () -> new GooCoverBlock());
	public static final RegistryObject<Block> GOO_COVER_BLOCK = REGISTRY.register("goo_cover_block", () -> new GooCoverBlockBlock());
	public static final RegistryObject<Block> CONNECTED_HANGING_GOO = REGISTRY.register("connected_hanging_goo", () -> new ConnectedHangingGooBlock());
	public static final RegistryObject<Block> BLOCK_OF_GOO = REGISTRY.register("block_of_goo", () -> new BlockOfGooBlock());
	public static final RegistryObject<Block> BONE_CRAWLER_EGG = REGISTRY.register("bone_crawler_egg", () -> new BoneCrawlerEggBlock());
	public static final RegistryObject<Block> BONE_CRAWLER_EGG_GENERATE = REGISTRY.register("bone_crawler_egg_generate", () -> new BoneCrawlerEggGenerateBlock());
	public static final RegistryObject<Block> REGURGITATED_MATTER = REGISTRY.register("regurgitated_matter", () -> new RegurgitatedMatterBlock());
	public static final RegistryObject<Block> GOO_GROWTH = REGISTRY.register("goo_growth", () -> new GooGrowthBlock());
	public static final RegistryObject<Block> GOO_BRICKS = REGISTRY.register("goo_bricks", () -> new GooBricksBlock());
	public static final RegistryObject<Block> GOO_BRICK_STAIRS = REGISTRY.register("goo_brick_stairs", () -> new GooBrickStairsBlock());
	public static final RegistryObject<Block> GOO_BRICK_SLAB = REGISTRY.register("goo_brick_slab", () -> new GooBrickSlabBlock());
	public static final RegistryObject<Block> GOO_BRICK_WALL = REGISTRY.register("goo_brick_wall", () -> new GooBrickWallBlock());
	public static final RegistryObject<Block> GOO_WEB = REGISTRY.register("goo_web", () -> new GooWebBlock());
	public static final RegistryObject<Block> ROTTEN_FLESH_CHUNK = REGISTRY.register("rotten_flesh_chunk", () -> new RottenFleshChunkBlock());
	public static final RegistryObject<Block> HANGING_ROTTEN_FLESH = REGISTRY.register("hanging_rotten_flesh", () -> new HangingRottenFleshBlock());
	public static final RegistryObject<Block> ROTTEN_FLESH_STAIRS = REGISTRY.register("rotten_flesh_stairs", () -> new RottenFleshStairsBlock());
	public static final RegistryObject<Block> ROTTEN_FLESH_SLAB = REGISTRY.register("rotten_flesh_slab", () -> new RottenFleshSlabBlock());
	public static final RegistryObject<Block> MELTED_GOO = REGISTRY.register("melted_goo", () -> new MeltedGooBlock());
	public static final RegistryObject<Block> MELTED_GOO_STAIRS = REGISTRY.register("melted_goo_stairs", () -> new MeltedGooStairsBlock());
	public static final RegistryObject<Block> MELTED_GOO_SLAB = REGISTRY.register("melted_goo_slab", () -> new MeltedGooSlabBlock());
	public static final RegistryObject<Block> ROTTING_CORPSE = REGISTRY.register("rotting_corpse", () -> new RottingCorpseBlock());
	public static final RegistryObject<Block> ROTTING_CORPSE_SPAWN = REGISTRY.register("rotting_corpse_spawn", () -> new RottingCorpseSpawnBlock());
	public static final RegistryObject<Block> ROTTING_COVERED_CORPSE = REGISTRY.register("rotting_covered_corpse", () -> new RottingCoveredCorpseBlock());
	public static final RegistryObject<Block> ROTTING_COVERED_CORPSE_SPAWN = REGISTRY.register("rotting_covered_corpse_spawn", () -> new RottingCoveredCorpseSpawnBlock());
	public static final RegistryObject<Block> ROTTING_LAYING_CORPSE = REGISTRY.register("rotting_laying_corpse", () -> new RottingLayingCorpseBlock());
	public static final RegistryObject<Block> ROTTING_LAYING_CORPSE_SPAWN = REGISTRY.register("rotting_laying_corpse_spawn", () -> new RottingLayingCorpseSpawnBlock());
	public static final RegistryObject<Block> ROTTING_WALL_CORPSE = REGISTRY.register("rotting_wall_corpse", () -> new RottingWallCorpseBlock());
	public static final RegistryObject<Block> TRANSLUCENT_GOO = REGISTRY.register("translucent_goo", () -> new TranslucentGooBlock());
	public static final RegistryObject<Block> BIG_BLUE_EYE = REGISTRY.register("big_blue_eye", () -> new BigBlueEyeBlock());
	public static final RegistryObject<Block> BIG_GREEN_EYE = REGISTRY.register("big_green_eye", () -> new BigGreenEyeBlock());
	public static final RegistryObject<Block> BIG_RED_EYE = REGISTRY.register("big_red_eye", () -> new BigRedEyeBlock());
	public static final RegistryObject<Block> BIG_YELLOW_EYE = REGISTRY.register("big_yellow_eye", () -> new BigYellowEyeBlock());
	public static final RegistryObject<Block> HUGE_EYE_VINE_STEM = REGISTRY.register("huge_eye_vine_stem", () -> new HugeEyeVineStemBlock());
	public static final RegistryObject<Block> POROUS_FLESH = REGISTRY.register("porous_flesh", () -> new PorousFleshBlock());
	public static final RegistryObject<Block> VEINY_FLESH = REGISTRY.register("veiny_flesh", () -> new VeinyFleshBlock());
	public static final RegistryObject<Block> GAPING_POROUS_FLESH = REGISTRY.register("gaping_porous_flesh", () -> new GapingPorousFleshBlock());
	public static final RegistryObject<Block> CARRION = REGISTRY.register("carrion", () -> new CarrionBlock());
	public static final RegistryObject<Block> MESSY_FLESH = REGISTRY.register("messy_flesh", () -> new MessyFleshBlock());
	public static final RegistryObject<Block> VOIDRIUM_GLASS = REGISTRY.register("voidrium_glass", () -> new VoidriumGlassBlock());
	public static final RegistryObject<Block> BLOCK_OF_ROTTEN_BONE_PILE = REGISTRY.register("block_of_rotten_bone_pile", () -> new BlockOfRottenBonePileBlock());
	public static final RegistryObject<Block> CINNABAR_CHAIN = REGISTRY.register("cinnabar_chain", () -> new CinnabarChainBlock());
	public static final RegistryObject<Block> LAYING_CORPSE = REGISTRY.register("laying_corpse", () -> new LayingCorpseBlock());
	public static final RegistryObject<Block> JACK_O_LAYING_CORPSE = REGISTRY.register("jack_o_laying_corpse", () -> new JackOLayingCorpseBlock());
	public static final RegistryObject<Block> LAYING_CORPSE_SPAWN = REGISTRY.register("laying_corpse_spawn", () -> new LayingCorpseSpawnBlock());
	public static final RegistryObject<Block> BLOCK_OF_RAW_CINNABAR = REGISTRY.register("block_of_raw_cinnabar", () -> new BlockOfRawCinnabarBlock());
	public static final RegistryObject<Block> BISMUTH_BRICKS = REGISTRY.register("bismuth_bricks", () -> new BismuthBricksBlock());
	public static final RegistryObject<Block> BISMUTH_BRICK_STAIRS = REGISTRY.register("bismuth_brick_stairs", () -> new BismuthBrickStairsBlock());
	public static final RegistryObject<Block> BISMUTH_BRICK_SLAB = REGISTRY.register("bismuth_brick_slab", () -> new BismuthBrickSlabBlock());
	public static final RegistryObject<Block> BLOCK_OF_REFINED_ONYX = REGISTRY.register("block_of_refined_onyx", () -> new BlockOfRefinedOnyxBlock());
	public static final RegistryObject<Block> BLOCK_OF_ANCIENT_ONYX = REGISTRY.register("block_of_ancient_onyx", () -> new BlockOfAncientOnyxBlock());
	public static final RegistryObject<Block> REFINED_ONYX_STAIRS = REGISTRY.register("refined_onyx_stairs", () -> new RefinedOnyxStairsBlock());
	public static final RegistryObject<Block> REFINED_ONYX_SLAB = REGISTRY.register("refined_onyx_slab", () -> new RefinedOnyxSlabBlock());
	public static final RegistryObject<Block> DESOLATE_SOIL_ACTIVE = REGISTRY.register("desolate_soil_active", () -> new DesolateSoilActiveBlock());
	public static final RegistryObject<Block> SOUL_ORB_PILLAR = REGISTRY.register("soul_orb_pillar", () -> new SoulOrbPillarBlock());
	public static final RegistryObject<Block> SOUL_CONTAINER = REGISTRY.register("soul_container", () -> new SoulContainerBlock());
	public static final RegistryObject<Block> VOID_EFFIGY = REGISTRY.register("void_effigy", () -> new VoidEffigyBlock());
	public static final RegistryObject<Block> VOID_EFFIGY_OPEN = REGISTRY.register("void_effigy_open", () -> new VoidEffigyOpenBlock());
	public static final RegistryObject<Block> CINNABAR_GLASS = REGISTRY.register("cinnabar_glass", () -> new CinnabarGlassBlock());
	public static final RegistryObject<Block> CINNABAR_GLASS_PANE = REGISTRY.register("cinnabar_glass_pane", () -> new CinnabarGlassPaneBlock());
	public static final RegistryObject<Block> ROTTEN_MOSS_ACTIVE = REGISTRY.register("rotten_moss_active", () -> new RottenMossActiveBlock());
	public static final RegistryObject<Block> BIG_SMOKE_VENT = REGISTRY.register("big_smoke_vent", () -> new BigSmokeVentBlock());
	public static final RegistryObject<Block> BIG_SMOKE_VENT_CORNER = REGISTRY.register("big_smoke_vent_corner", () -> new BigSmokeVentCornerBlock());
	public static final RegistryObject<Block> VENT_STONE = REGISTRY.register("vent_stone", () -> new VentStoneBlock());
	public static final RegistryObject<Block> CORPSE_PILE = REGISTRY.register("corpse_pile", () -> new CorpsePileBlock());
	public static final RegistryObject<Block> BIG_TOOTH = REGISTRY.register("big_tooth", () -> new BigToothBlock());
	public static final RegistryObject<Block> SOUL_FORGE = REGISTRY.register("soul_forge", () -> new SoulForgeBlock());
	public static final RegistryObject<Block> RED_GATE = REGISTRY.register("red_gate", () -> new RedGateBlock());
	public static final RegistryObject<Block> RED_GATE_NON_SOLID = REGISTRY.register("red_gate_non_solid", () -> new RedGateNonSolidBlock());
	public static final RegistryObject<Block> BLOCK_OF_SOUL_FUSED_INGOTS = REGISTRY.register("block_of_soul_fused_ingots", () -> new BlockOfSoulFusedIngotsBlock());
	public static final RegistryObject<Block> VOID_GROWTH = REGISTRY.register("void_growth", () -> new VoidGrowthBlock());
	public static final RegistryObject<Block> FLESH_STAIRS = REGISTRY.register("flesh_stairs", () -> new FleshStairsBlock());
	public static final RegistryObject<Block> FLESH_SLAB = REGISTRY.register("flesh_slab", () -> new FleshSlabBlock());
	public static final RegistryObject<Block> TENDONS = REGISTRY.register("tendons", () -> new TendonsBlock());
	public static final RegistryObject<Block> OLD_CORPSE_PILE = REGISTRY.register("old_corpse_pile", () -> new OldCorpsePileBlock());
	public static final RegistryObject<Block> OLD_CORPSE = REGISTRY.register("old_corpse", () -> new OldCorpseBlock());
	public static final RegistryObject<Block> OLD_WALL_CORPSE = REGISTRY.register("old_wall_corpse", () -> new OldWallCorpseBlock());
	public static final RegistryObject<Block> OLD_COVERED_CORPSE = REGISTRY.register("old_covered_corpse", () -> new OldCoveredCorpseBlock());
	public static final RegistryObject<Block> OLD_LAYING_CORPSE = REGISTRY.register("old_laying_corpse", () -> new OldLayingCorpseBlock());
	public static final RegistryObject<Block> OLD_BONE_BLOCK = REGISTRY.register("old_bone_block", () -> new OldBoneBlockBlock());
	public static final RegistryObject<Block> FLESHY_ROTTEN_BONE_BLOCK = REGISTRY.register("fleshy_rotten_bone_block", () -> new FleshyRottenBoneBlockBlock());
	public static final RegistryObject<Block> FLESHY_OLD_BONE_BLOCK = REGISTRY.register("fleshy_old_bone_block", () -> new FleshyOldBoneBlockBlock());
	public static final RegistryObject<Block> EYE_TENDONS = REGISTRY.register("eye_tendons", () -> new EyeTendonsBlock());
	public static final RegistryObject<Block> PEEPING_STEM = REGISTRY.register("peeping_stem", () -> new PeepingStemBlock());
	public static final RegistryObject<Block> ACTIVE_FLESH_BLOCK = REGISTRY.register("active_flesh_block", () -> new ActiveFleshBlockBlock());
	public static final RegistryObject<Block> BROWN_EYE_VINE = REGISTRY.register("brown_eye_vine", () -> new BrownEyeVineBlock());
	public static final RegistryObject<Block> PURPLE_EYE_VINE = REGISTRY.register("purple_eye_vine", () -> new PurpleEyeVineBlock());
	public static final RegistryObject<Block> BIG_BROWN_EYE = REGISTRY.register("big_brown_eye", () -> new BigBrownEyeBlock());
	public static final RegistryObject<Block> BIG_PURPLE_EYE = REGISTRY.register("big_purple_eye", () -> new BigPurpleEyeBlock());
	public static final RegistryObject<Block> VOID_BLOSSOM = REGISTRY.register("void_blossom", () -> new VoidBlossomBlock());
	public static final RegistryObject<Block> LURKER_SHRINE = REGISTRY.register("lurker_shrine", () -> new LurkerShrineBlock());
	public static final RegistryObject<Block> POLISHED_LAVENDITE_BLOCK = REGISTRY.register("polished_lavendite_block", () -> new PolishedLavenditeBlockBlock());
	public static final RegistryObject<Block> POLISHED_LAVENDITE_STAIRS = REGISTRY.register("polished_lavendite_stairs", () -> new PolishedLavenditeStairsBlock());
	public static final RegistryObject<Block> POLISHED_LAVENDITE_SLAB = REGISTRY.register("polished_lavendite_slab", () -> new PolishedLavenditeSlabBlock());
	public static final RegistryObject<Block> VOID_STEM = REGISTRY.register("void_stem", () -> new VoidStemBlock());
	public static final RegistryObject<Block> ANCIENT_POT_BLOCK = REGISTRY.register("ancient_pot_block", () -> new AncientPotBlockBlock());
	public static final RegistryObject<Block> ANCIENT_POT = REGISTRY.register("ancient_pot", () -> new AncientPotBlock());
	public static final RegistryObject<Block> ANCIENT_URNS = REGISTRY.register("ancient_urns", () -> new AncientUrnsBlock());
	public static final RegistryObject<Block> ANCIENT_URNS_GENERATE = REGISTRY.register("ancient_urns_generate", () -> new AncientUrnsGenerateBlock());
	public static final RegistryObject<Block> CRUMBLING_MONOLITHIC_STONE = REGISTRY.register("crumbling_monolithic_stone", () -> new CrumblingMonolithicStoneBlock());
	public static final RegistryObject<Block> BONE_SPIKES = REGISTRY.register("bone_spikes", () -> new BoneSpikesBlock());
	public static final RegistryObject<Block> TWISTING_SPINE = REGISTRY.register("twisting_spine", () -> new TwistingSpineBlock());
	public static final RegistryObject<Block> FAKE_TORCH = REGISTRY.register("fake_torch", () -> new FakeTorchBlock());
	public static final RegistryObject<Block> MISTED_REMAINS = REGISTRY.register("misted_remains", () -> new MistedRemainsBlock());
	public static final RegistryObject<Block> BLOCK_OF_MISTED_BONE_PILE = REGISTRY.register("block_of_misted_bone_pile", () -> new BlockOfMistedBonePileBlock());
	public static final RegistryObject<Block> WATCHER_ON = REGISTRY.register("watcher_on", () -> new WatcherOnBlock());
	public static final RegistryObject<Block> WATCHER = REGISTRY.register("watcher", () -> new WatcherBlock());
	public static final RegistryObject<Block> HEART_OF_THE_MIND = REGISTRY.register("heart_of_the_mind", () -> new HeartOfTheMindBlock());
	public static final RegistryObject<Block> CORPSE_BLOSSOM = REGISTRY.register("corpse_blossom", () -> new CorpseBlossomBlock());
	public static final RegistryObject<Block> SOLID_AMBROSIA = REGISTRY.register("solid_ambrosia", () -> new SolidAmbrosiaBlock());
	public static final RegistryObject<Block> PACKED_FLESH = REGISTRY.register("packed_flesh", () -> new PackedFleshBlock());
	public static final RegistryObject<Block> BLOCK_OF_HARD_FLESH = REGISTRY.register("block_of_hard_flesh", () -> new BlockOfHardFleshBlock());
	public static final RegistryObject<Block> HEAD_OF_THE_HIVEMIND = REGISTRY.register("head_of_the_hivemind", () -> new HeadOfTheHivemindBlock());
	public static final RegistryObject<Block> HEAD_OF_THE_PRIMORDIAL_CRAWLER = REGISTRY.register("head_of_the_primordial_crawler", () -> new HeadOfThePrimordialCrawlerBlock());
	public static final RegistryObject<Block> HEAD_OF_THE_APOSTLE = REGISTRY.register("head_of_the_apostle", () -> new HeadOfTheApostleBlock());
	public static final RegistryObject<Block> HEAD_OF_THE_WEAVER = REGISTRY.register("head_of_the_weaver", () -> new HeadOfTheWeaverBlock());
	public static final RegistryObject<Block> CAGE = REGISTRY.register("cage", () -> new CageBlock());
	public static final RegistryObject<Block> CORPSE_IN_A_CAGE = REGISTRY.register("corpse_in_a_cage", () -> new CorpseInACageBlock());
	public static final RegistryObject<Block> JACK_O_CORPSE_IN_A_CAGE = REGISTRY.register("jack_o_corpse_in_a_cage", () -> new JackOCorpseInACageBlock());
	public static final RegistryObject<Block> OLD_CORPSE_IN_A_CAGE = REGISTRY.register("old_corpse_in_a_cage", () -> new OldCorpseInACageBlock());
	public static final RegistryObject<Block> ROTTING_CORPSE_IN_A_CAGE = REGISTRY.register("rotting_corpse_in_a_cage", () -> new RottingCorpseInACageBlock());
	public static final RegistryObject<Block> CRACKED_ANCIENT_DEEPSLATE_BRICKS = REGISTRY.register("cracked_ancient_deepslate_bricks", () -> new CrackedAncientDeepslateBricksBlock());
	public static final RegistryObject<Block> ROTTEN_ANCIENT_DEEPSLATE_BRICKS = REGISTRY.register("rotten_ancient_deepslate_bricks", () -> new RottenAncientDeepslateBricksBlock());
	public static final RegistryObject<Block> ROTTEN_ANCIENT_DEEPSLATE_BRICK_STAIRS = REGISTRY.register("rotten_ancient_deepslate_brick_stairs", () -> new RottenAncientDeepslateBrickStairsBlock());
	public static final RegistryObject<Block> ROTTEN_ANCIENT_DEEPSLATE_BRICK_SLAB = REGISTRY.register("rotten_ancient_deepslate_brick_slab", () -> new RottenAncientDeepslateBrickSlabBlock());
	public static final RegistryObject<Block> ROTTEN_ANCIENT_DEEPSLATE_BRICK_WALL = REGISTRY.register("rotten_ancient_deepslate_brick_wall", () -> new RottenAncientDeepslateBrickWallBlock());
	public static final RegistryObject<Block> BLOCK_OF_BLACK_MOSS = REGISTRY.register("block_of_black_moss", () -> new BlockOfBlackMossBlock());
	public static final RegistryObject<Block> INSCRIBED_ANCIENT_DEEPSLATE = REGISTRY.register("inscribed_ancient_deepslate", () -> new InscribedAncientDeepslateBlock());
	public static final RegistryObject<Block> TRAP_BONE_SPIKES = REGISTRY.register("trap_bone_spikes", () -> new TrapBoneSpikesBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_SPIKE_TRAP = REGISTRY.register("ancient_deepslate_spike_trap", () -> new AncientDeepslateSpikeTrapBlock());
	public static final RegistryObject<Block> PENITENT_IN_A_CAGE = REGISTRY.register("penitent_in_a_cage", () -> new PenitentInACageBlock());
	public static final RegistryObject<Block> DARK_STEEL_BARS = REGISTRY.register("dark_steel_bars", () -> new DarkSteelBarsBlock());
	public static final RegistryObject<Block> CANDELABRA = REGISTRY.register("candelabra", () -> new CandelabraBlock());
	public static final RegistryObject<Block> CANDELABRA_FOOT = REGISTRY.register("candelabra_foot", () -> new CandelabraFootBlock());
	public static final RegistryObject<Block> BLACK_CANDELABRA = REGISTRY.register("black_candelabra", () -> new BlackCandelabraBlock());
	public static final RegistryObject<Block> BLUE_CANDELABRA = REGISTRY.register("blue_candelabra", () -> new BlueCandelabraBlock());
	public static final RegistryObject<Block> BROWN_CANDELABRA = REGISTRY.register("brown_candelabra", () -> new BrownCandelabraBlock());
	public static final RegistryObject<Block> CYAN_CANDELABRA = REGISTRY.register("cyan_candelabra", () -> new CyanCandelabraBlock());
	public static final RegistryObject<Block> GRAY_CANDELABRA = REGISTRY.register("gray_candelabra", () -> new GrayCandelabraBlock());
	public static final RegistryObject<Block> GREEN_CANDELABRA = REGISTRY.register("green_candelabra", () -> new GreenCandelabraBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_CANDELABRA = REGISTRY.register("light_blue_candelabra", () -> new LightBlueCandelabraBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_CANDELABRA = REGISTRY.register("light_gray_candelabra", () -> new LightGrayCandelabraBlock());
	public static final RegistryObject<Block> LIME_CANDELABRA = REGISTRY.register("lime_candelabra", () -> new LimeCandelabraBlock());
	public static final RegistryObject<Block> MAGENTA_CANDELABRA = REGISTRY.register("magenta_candelabra", () -> new MagentaCandelabraBlock());
	public static final RegistryObject<Block> ORANGE_CANDELABRA = REGISTRY.register("orange_candelabra", () -> new OrangeCandelabraBlock());
	public static final RegistryObject<Block> PINK_CANDELABRA = REGISTRY.register("pink_candelabra", () -> new PinkCandelabraBlock());
	public static final RegistryObject<Block> PURPLE_CANDELABRA = REGISTRY.register("purple_candelabra", () -> new PurpleCandelabraBlock());
	public static final RegistryObject<Block> RED_CANDELABRA = REGISTRY.register("red_candelabra", () -> new RedCandelabraBlock());
	public static final RegistryObject<Block> WHITE_CANDELABRA = REGISTRY.register("white_candelabra", () -> new WhiteCandelabraBlock());
	public static final RegistryObject<Block> YELLOW_CANDELABRA = REGISTRY.register("yellow_candelabra", () -> new YellowCandelabraBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_SAW_TRAP = REGISTRY.register("ancient_deepslate_saw_trap", () -> new AncientDeepslateSawTrapBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_SAW_TRAP_TRACK = REGISTRY.register("ancient_deepslate_saw_trap_track", () -> new AncientDeepslateSawTrapTrackBlock());
	public static final RegistryObject<Block> SMOOTH_ANCIENT_DEEPSLATE_PRESSURE_PLATE = REGISTRY.register("smooth_ancient_deepslate_pressure_plate", () -> new SmoothAncientDeepslatePressurePlateBlock());
	public static final RegistryObject<Block> VOIDRIUM_SAW_TRAP = REGISTRY.register("voidrium_saw_trap", () -> new VoidriumSawTrapBlock());
	public static final RegistryObject<Block> SMOOTH_ANCIENT_DEEPSLATE_BUTTON = REGISTRY.register("smooth_ancient_deepslate_button", () -> new SmoothAncientDeepslateButtonBlock());
	public static final RegistryObject<Block> CANDLESTICK = REGISTRY.register("candlestick", () -> new CandlestickBlock());
	public static final RegistryObject<Block> BLACK_CANDLESTICK = REGISTRY.register("black_candlestick", () -> new BlackCandlestickBlock());
	public static final RegistryObject<Block> BLUE_CANDLESTICK = REGISTRY.register("blue_candlestick", () -> new BlueCandlestickBlock());
	public static final RegistryObject<Block> BROWN_CANDLESTICK = REGISTRY.register("brown_candlestick", () -> new BrownCandlestickBlock());
	public static final RegistryObject<Block> CYAN_CANDLESTICK = REGISTRY.register("cyan_candlestick", () -> new CyanCandlestickBlock());
	public static final RegistryObject<Block> GRAY_CANDLESTICK = REGISTRY.register("gray_candlestick", () -> new GrayCandlestickBlock());
	public static final RegistryObject<Block> GREEN_CANDLESTICK = REGISTRY.register("green_candlestick", () -> new GreenCandlestickBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_CANDLESTICK = REGISTRY.register("light_blue_candlestick", () -> new LightBlueCandlestickBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_CANDLESTICK = REGISTRY.register("light_gray_candlestick", () -> new LightGrayCandlestickBlock());
	public static final RegistryObject<Block> LIME_CANDLESTICK = REGISTRY.register("lime_candlestick", () -> new LimeCandlestickBlock());
	public static final RegistryObject<Block> MAGENTA_CANDLESTICK = REGISTRY.register("magenta_candlestick", () -> new MagentaCandlestickBlock());
	public static final RegistryObject<Block> ORANGE_CANDLESTICK = REGISTRY.register("orange_candlestick", () -> new OrangeCandlestickBlock());
	public static final RegistryObject<Block> PINK_CANDLESTICK = REGISTRY.register("pink_candlestick", () -> new PinkCandlestickBlock());
	public static final RegistryObject<Block> PURPLE_CANDLESTICK = REGISTRY.register("purple_candlestick", () -> new PurpleCandlestickBlock());
	public static final RegistryObject<Block> RED_CANDLESTICK = REGISTRY.register("red_candlestick", () -> new RedCandlestickBlock());
	public static final RegistryObject<Block> WHITE_CANDLESTICK = REGISTRY.register("white_candlestick", () -> new WhiteCandlestickBlock());
	public static final RegistryObject<Block> YELLOW_CANDLESTICK = REGISTRY.register("yellow_candlestick", () -> new YellowCandlestickBlock());
	public static final RegistryObject<Block> ANCIENT_DEEPSLATE_DART_TRAP = REGISTRY.register("ancient_deepslate_dart_trap", () -> new AncientDeepslateDartTrapBlock());
	public static final RegistryObject<Block> AMBROSIAL_FLESH_BLOCK = REGISTRY.register("ambrosial_flesh_block", () -> new AmbrosialFleshBlockBlock());
	public static final RegistryObject<Block> AMBROSIA_STRANDS = REGISTRY.register("ambrosia_strands", () -> new AmbrosiaStrandsBlock());
	public static final RegistryObject<Block> CONNECTED_AMBROSIA_STRANDS = REGISTRY.register("connected_ambrosia_strands", () -> new ConnectedAmbrosiaStrandsBlock());
	public static final RegistryObject<Block> BLOCK_OF_VISCERA = REGISTRY.register("block_of_viscera", () -> new BlockOfVisceraBlock());
	public static final RegistryObject<Block> BLOOD_LANTERN = REGISTRY.register("blood_lantern", () -> new BloodLanternBlock());
	public static final RegistryObject<Block> ICHOR_LANTERN = REGISTRY.register("ichor_lantern", () -> new IchorLanternBlock());
	public static final RegistryObject<Block> DARK_STEEL_DEPOSIT = REGISTRY.register("dark_steel_deposit", () -> new DarkSteelDepositBlock());
	public static final RegistryObject<Block> BLOCK_OF_DARK_STEEL = REGISTRY.register("block_of_dark_steel", () -> new BlockOfDarkSteelBlock());
	public static final RegistryObject<Block> EYE_OF_THE_HIVE_WATCHER = REGISTRY.register("eye_of_the_hive_watcher", () -> new EyeOfTheHiveWatcherBlock());
	public static final RegistryObject<Block> INTERTWINED_BLACK_MOSS = REGISTRY.register("intertwined_black_moss", () -> new IntertwinedBlackMossBlock());
	public static final RegistryObject<Block> STRIPPED_ROTTEN_LOG = REGISTRY.register("stripped_rotten_log", () -> new StrippedRottenLogBlock());
	public static final RegistryObject<Block> STRIPPED_ROTTEN_WOOD = REGISTRY.register("stripped_rotten_wood", () -> new StrippedRottenWoodBlock());
	public static final RegistryObject<Block> ROTTEN_CRATE = REGISTRY.register("rotten_crate", () -> new RottenCrateBlock());
	public static final RegistryObject<Block> GOLDEN_ROTTEN_CRATE = REGISTRY.register("golden_rotten_crate", () -> new GoldenRottenCrateBlock());
	public static final RegistryObject<Block> FLESH_CRATE = REGISTRY.register("flesh_crate", () -> new FleshCrateBlock());
	public static final RegistryObject<Block> GOLDEN_FLESH_CRATE = REGISTRY.register("golden_flesh_crate", () -> new GoldenFleshCrateBlock());
	public static final RegistryObject<Block> INFESTED_BONE_CRAWLER_EGG = REGISTRY.register("infested_bone_crawler_egg", () -> new InfestedBoneCrawlerEggBlock());
	public static final RegistryObject<Block> INFESTED_BONE_CRAWLER_EGG_GENERATE = REGISTRY.register("infested_bone_crawler_egg_generate", () -> new InfestedBoneCrawlerEggGenerateBlock());
	public static final RegistryObject<Block> GOLDEN_REGURGITATED_MATTER = REGISTRY.register("golden_regurgitated_matter", () -> new GoldenRegurgitatedMatterBlock());
	public static final RegistryObject<Block> SOLID_VOID_BRICKS = REGISTRY.register("solid_void_bricks", () -> new SolidVoidBricksBlock());
	public static final RegistryObject<Block> SMOOTH_SOLID_VOID = REGISTRY.register("smooth_solid_void", () -> new SmoothSolidVoidBlock());
	public static final RegistryObject<Block> SOLID_VOID_BLOCK = REGISTRY.register("solid_void_block", () -> new SolidVoidBlockBlock());
	public static final RegistryObject<Block> CHISELED_SOLID_VOID_BLOCK = REGISTRY.register("chiseled_solid_void_block", () -> new ChiseledSolidVoidBlockBlock());
	public static final RegistryObject<Block> SOLID_VOID_BRICK_STAIRS = REGISTRY.register("solid_void_brick_stairs", () -> new SolidVoidBrickStairsBlock());
	public static final RegistryObject<Block> SOLID_VOID_BRICK_SLAB = REGISTRY.register("solid_void_brick_slab", () -> new SolidVoidBrickSlabBlock());
	public static final RegistryObject<Block> SOLID_VOID_BRICK_WALL = REGISTRY.register("solid_void_brick_wall", () -> new SolidVoidBrickWallBlock());
	public static final RegistryObject<Block> SOLID_VOID_STAIRS = REGISTRY.register("solid_void_stairs", () -> new SolidVoidStairsBlock());
	public static final RegistryObject<Block> SOLID_VOID_SLAB = REGISTRY.register("solid_void_slab", () -> new SolidVoidSlabBlock());
	public static final RegistryObject<Block> DARK_STEEL_CHAIN = REGISTRY.register("dark_steel_chain", () -> new DarkSteelChainBlock());
	public static final RegistryObject<Block> FRAMED_GLASS = REGISTRY.register("framed_glass", () -> new FramedGlassBlock());
	public static final RegistryObject<Block> FRAMED_GLASS_PANE = REGISTRY.register("framed_glass_pane", () -> new FramedGlassPaneBlock());
	public static final RegistryObject<Block> FRAMED_SULFUR_GLASS = REGISTRY.register("framed_sulfur_glass", () -> new FramedSulfurGlassBlock());
	public static final RegistryObject<Block> FRAMED_SULFUR_GLASS_PANE = REGISTRY.register("framed_sulfur_glass_pane", () -> new FramedSulfurGlassPaneBlock());
	public static final RegistryObject<Block> FRAMED_BISMUTH_GLASS = REGISTRY.register("framed_bismuth_glass", () -> new FramedBismuthGlassBlock());
	public static final RegistryObject<Block> FRAMED_BISMUTH_GLASS_PANE = REGISTRY.register("framed_bismuth_glass_pane", () -> new FramedBismuthGlassPaneBlock());
	public static final RegistryObject<Block> FRAMED_CINNABAR_GLASS = REGISTRY.register("framed_cinnabar_glass", () -> new FramedCinnabarGlassBlock());
	public static final RegistryObject<Block> FRAMED_CINNABAR_GLASS_PANE = REGISTRY.register("framed_cinnabar_glass_pane", () -> new FramedCinnabarGlassPaneBlock());
	public static final RegistryObject<Block> CINNABAR_LANTERN = REGISTRY.register("cinnabar_lantern", () -> new CinnabarLanternBlock());
	public static final RegistryObject<Block> MADNESS_LANTERN = REGISTRY.register("madness_lantern", () -> new MadnessLanternBlock());
	public static final RegistryObject<Block> EYE_CAKE = REGISTRY.register("eye_cake", () -> new EyeCakeBlock());
	public static final RegistryObject<Block> EMPTY_SOLID_AMBROSIA = REGISTRY.register("empty_solid_ambrosia", () -> new EmptySolidAmbrosiaBlock());
	public static final RegistryObject<Block> DEEP_VOID_IRON_ORE = REGISTRY.register("deep_void_iron_ore", () -> new DeepVoidIronOreBlock());
	public static final RegistryObject<Block> DEEP_VOID_COPPER_ORE = REGISTRY.register("deep_void_copper_ore", () -> new DeepVoidCopperOreBlock());
	public static final RegistryObject<Block> DEEP_VOID_LAPIS_LAZULI_ORE = REGISTRY.register("deep_void_lapis_lazuli_ore", () -> new DeepVoidLapisLazuliOreBlock());
	public static final RegistryObject<Block> DEEP_VOID_REDSTONE_ORE = REGISTRY.register("deep_void_redstone_ore", () -> new DeepVoidRedstoneOreBlock());
	public static final RegistryObject<Block> DEEP_VOID_DIAMOND_ORE = REGISTRY.register("deep_void_diamond_ore", () -> new DeepVoidDiamondOreBlock());
	public static final RegistryObject<Block> DEEP_VOID_GOLD_ORE = REGISTRY.register("deep_void_gold_ore", () -> new DeepVoidGoldOreBlock());
	public static final RegistryObject<Block> HEAD_OF_THE_HUNTER = REGISTRY.register("head_of_the_hunter", () -> new HeadOfTheHunterBlock());
	public static final RegistryObject<Block> LIQUID_ICHOR = REGISTRY.register("liquid_ichor", () -> new LiquidIchorBlock());
	public static final RegistryObject<Block> CRYSTALLIZED_ICHOR = REGISTRY.register("crystallized_ichor", () -> new CrystallizedIchorBlock());
	public static final RegistryObject<Block> ROTTEN_GROWTH = REGISTRY.register("rotten_growth", () -> new RottenGrowthBlock());
	public static final RegistryObject<Block> PROTRUDING_MARROW = REGISTRY.register("protruding_marrow", () -> new ProtrudingMarrowBlock());
	public static final RegistryObject<Block> BLOCK_OF_BONE_MARROW = REGISTRY.register("block_of_bone_marrow", () -> new BlockOfBoneMarrowBlock());
	public static final RegistryObject<Block> BLOCK_OF_ROTTEN_BONE_MARROW = REGISTRY.register("block_of_rotten_bone_marrow", () -> new BlockOfRottenBoneMarrowBlock());
	public static final RegistryObject<Block> BLOCK_OF_MARROW = REGISTRY.register("block_of_marrow", () -> new BlockOfMarrowBlock());
	public static final RegistryObject<Block> BLOCK_OF_BONE = REGISTRY.register("block_of_bone", () -> new BlockOfBoneBlock());
	public static final RegistryObject<Block> BLOODSTONE_ORE = REGISTRY.register("bloodstone_ore", () -> new BloodstoneOreBlock());
	public static final RegistryObject<Block> BLOCK_OF_BLOODSTONE = REGISTRY.register("block_of_bloodstone", () -> new BlockOfBloodstoneBlock());
	public static final RegistryObject<Block> FLESH_BLOODSTONE_ORE = REGISTRY.register("flesh_bloodstone_ore", () -> new FleshBloodstoneOreBlock());
	public static final RegistryObject<Block> BLOCK_OF_SHATTERED_BONE = REGISTRY.register("block_of_shattered_bone", () -> new BlockOfShatteredBoneBlock());
	public static final RegistryObject<Block> BLOCK_OF_OLD_SHATTERED_BONE = REGISTRY.register("block_of_old_shattered_bone", () -> new BlockOfOldShatteredBoneBlock());
	public static final RegistryObject<Block> BLOCK_OF_ROTTEN_SHATTERED_BONE = REGISTRY.register("block_of_rotten_shattered_bone", () -> new BlockOfRottenShatteredBoneBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
