
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedeepvoid.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.thedeepvoid.item.WitherNeedleItem;
import net.mcreator.thedeepvoid.item.WeaverRobeItem;
import net.mcreator.thedeepvoid.item.WeaverOfSoulsTreasureBagItem;
import net.mcreator.thedeepvoid.item.WeaverMaskItem;
import net.mcreator.thedeepvoid.item.WeaverLeggingsItem;
import net.mcreator.thedeepvoid.item.WeaverBootsItem;
import net.mcreator.thedeepvoid.item.VultureMuzzleItem;
import net.mcreator.thedeepvoid.item.VoodooDollItem;
import net.mcreator.thedeepvoid.item.VoidriumSwordItem;
import net.mcreator.thedeepvoid.item.VoidriumShovelItem;
import net.mcreator.thedeepvoid.item.VoidriumPickaxeItem;
import net.mcreator.thedeepvoid.item.VoidriumItem;
import net.mcreator.thedeepvoid.item.VoidriumHoeItem;
import net.mcreator.thedeepvoid.item.VoidriumBulwarkItem;
import net.mcreator.thedeepvoid.item.VoidriumAxeItem;
import net.mcreator.thedeepvoid.item.VoidPendantItem;
import net.mcreator.thedeepvoid.item.VoidMirrorItem;
import net.mcreator.thedeepvoid.item.VoidMatterItem;
import net.mcreator.thedeepvoid.item.VoidLensItem;
import net.mcreator.thedeepvoid.item.VoidDaggerItem;
import net.mcreator.thedeepvoid.item.VoidCloakItem;
import net.mcreator.thedeepvoid.item.UmbriumGemItem;
import net.mcreator.thedeepvoid.item.TombstoneItem;
import net.mcreator.thedeepvoid.item.TheHarvestItem;
import net.mcreator.thedeepvoid.item.SulfurItem;
import net.mcreator.thedeepvoid.item.SulfurBombItem;
import net.mcreator.thedeepvoid.item.StalkerTreatItem;
import net.mcreator.thedeepvoid.item.StalkerScytheClawItem;
import net.mcreator.thedeepvoid.item.SpyglassDummyItem;
import net.mcreator.thedeepvoid.item.SpeedNeedleItem;
import net.mcreator.thedeepvoid.item.SoulShardItem;
import net.mcreator.thedeepvoid.item.SoulFusedIngotItem;
import net.mcreator.thedeepvoid.item.SoulCleaverItem;
import net.mcreator.thedeepvoid.item.SorrowArmorTrimItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateRotItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateOnyxItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateLavenditeItem;
import net.mcreator.thedeepvoid.item.SmithingTemplateGrimItem;
import net.mcreator.thedeepvoid.item.SinsAndSinnersItem;
import net.mcreator.thedeepvoid.item.ShadestormItem;
import net.mcreator.thedeepvoid.item.ScavengerArmorTrimItem;
import net.mcreator.thedeepvoid.item.ScareArmorTrimItem;
import net.mcreator.thedeepvoid.item.SaturationNeedleItem;
import net.mcreator.thedeepvoid.item.SacredVoidriumItem;
import net.mcreator.thedeepvoid.item.SacredCinnabarItem;
import net.mcreator.thedeepvoid.item.RoughVoidriumItem;
import net.mcreator.thedeepvoid.item.RottenWoodenSwordItem;
import net.mcreator.thedeepvoid.item.RottenTongueHookItem;
import net.mcreator.thedeepvoid.item.RottenStoneSwordItem;
import net.mcreator.thedeepvoid.item.RottenNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.RottenIronSwordItem;
import net.mcreator.thedeepvoid.item.RottenGoldenSwordItem;
import net.mcreator.thedeepvoid.item.RottenDiamondSwordItem;
import net.mcreator.thedeepvoid.item.RottenDelightItem;
import net.mcreator.thedeepvoid.item.RottenDartItem;
import net.mcreator.thedeepvoid.item.RottenBoneItem;
import net.mcreator.thedeepvoid.item.RottenBoneArmorItem;
import net.mcreator.thedeepvoid.item.RottenAllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.RotNeedleItem;
import net.mcreator.thedeepvoid.item.RootingTomeItem;
import net.mcreator.thedeepvoid.item.RidingCropItem;
import net.mcreator.thedeepvoid.item.ResistanceNeedleItem;
import net.mcreator.thedeepvoid.item.ReinforcedPickaxeItem;
import net.mcreator.thedeepvoid.item.RegenerationNeedleItem;
import net.mcreator.thedeepvoid.item.RefinedOnyxItem;
import net.mcreator.thedeepvoid.item.RefinedCinnabarItem;
import net.mcreator.thedeepvoid.item.RefinedBismuthItem;
import net.mcreator.thedeepvoid.item.ReapingHookItem;
import net.mcreator.thedeepvoid.item.PusBallItem;
import net.mcreator.thedeepvoid.item.PoisonNeedleItem;
import net.mcreator.thedeepvoid.item.PitchBlackItem;
import net.mcreator.thedeepvoid.item.OnyxSwordItem;
import net.mcreator.thedeepvoid.item.OnyxShovelItem;
import net.mcreator.thedeepvoid.item.OnyxPickaxeItem;
import net.mcreator.thedeepvoid.item.OnyxNeedleItem;
import net.mcreator.thedeepvoid.item.OnyxItem;
import net.mcreator.thedeepvoid.item.OnyxHoeItem;
import net.mcreator.thedeepvoid.item.OnyxFlareGunItem;
import net.mcreator.thedeepvoid.item.OnyxAxeItem;
import net.mcreator.thedeepvoid.item.OnyxArmorItem;
import net.mcreator.thedeepvoid.item.OffHandVoidDaggerItem;
import net.mcreator.thedeepvoid.item.MournerHideItem;
import net.mcreator.thedeepvoid.item.MisanthropicHivemindTreasureBagItem;
import net.mcreator.thedeepvoid.item.LurkingMusicDiscItem;
import net.mcreator.thedeepvoid.item.LiquidVoidItem;
import net.mcreator.thedeepvoid.item.LickerHookItem;
import net.mcreator.thedeepvoid.item.LavenditeWoodenSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeVoidriumSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeStoneSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeShovelItem;
import net.mcreator.thedeepvoid.item.LavenditeShieldItem;
import net.mcreator.thedeepvoid.item.LavenditeShardItem;
import net.mcreator.thedeepvoid.item.LavenditePickaxeItem;
import net.mcreator.thedeepvoid.item.LavenditeOnyxSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeItem;
import net.mcreator.thedeepvoid.item.LavenditeIronSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeHoeItem;
import net.mcreator.thedeepvoid.item.LavenditeGoldenSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeDiamondSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeDevourerHookItem;
import net.mcreator.thedeepvoid.item.LavenditeBoneSwordItem;
import net.mcreator.thedeepvoid.item.LavenditeAxeItem;
import net.mcreator.thedeepvoid.item.LavenditeArmorItem;
import net.mcreator.thedeepvoid.item.LavenditeAllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.KnifeGloveItem;
import net.mcreator.thedeepvoid.item.JumpBoostNeedleItem;
import net.mcreator.thedeepvoid.item.JudgementItem;
import net.mcreator.thedeepvoid.item.HexedNeedleItem;
import net.mcreator.thedeepvoid.item.HexedDollItem;
import net.mcreator.thedeepvoid.item.HeresyItem;
import net.mcreator.thedeepvoid.item.HealthBoostNeedleItem;
import net.mcreator.thedeepvoid.item.HatchingEnzymeItem;
import net.mcreator.thedeepvoid.item.HarvesterMaskItem;
import net.mcreator.thedeepvoid.item.HardFleshSwordItem;
import net.mcreator.thedeepvoid.item.HardFleshIngotItem;
import net.mcreator.thedeepvoid.item.GrimberryPieItem;
import net.mcreator.thedeepvoid.item.GrimberryJuiceItem;
import net.mcreator.thedeepvoid.item.GrimberryItem;
import net.mcreator.thedeepvoid.item.GrimSickleItem;
import net.mcreator.thedeepvoid.item.GrimShardItem;
import net.mcreator.thedeepvoid.item.GrimScytheItem;
import net.mcreator.thedeepvoid.item.GrimRottenBoneItem;
import net.mcreator.thedeepvoid.item.GrimLavenditeItem;
import net.mcreator.thedeepvoid.item.GrimGemItem;
import net.mcreator.thedeepvoid.item.GrimCrawlerItem;
import net.mcreator.thedeepvoid.item.GravediggerShovelItem;
import net.mcreator.thedeepvoid.item.GooSwordItem;
import net.mcreator.thedeepvoid.item.GooBallItem;
import net.mcreator.thedeepvoid.item.GoldenEyeballItem;
import net.mcreator.thedeepvoid.item.GlowingNeedleItem;
import net.mcreator.thedeepvoid.item.ForgottenTokenItem;
import net.mcreator.thedeepvoid.item.ForbiddenTomeItem;
import net.mcreator.thedeepvoid.item.FleshGloveItem;
import net.mcreator.thedeepvoid.item.FleshChunkItem;
import net.mcreator.thedeepvoid.item.FleshBoneItem;
import net.mcreator.thedeepvoid.item.FleshArmorItem;
import net.mcreator.thedeepvoid.item.FireResistanceNeedleItem;
import net.mcreator.thedeepvoid.item.EyekinSaddleItem;
import net.mcreator.thedeepvoid.item.EyeballSoupItem;
import net.mcreator.thedeepvoid.item.EyeballItem;
import net.mcreator.thedeepvoid.item.EyeShieldItem;
import net.mcreator.thedeepvoid.item.EndlessQuiverItem;
import net.mcreator.thedeepvoid.item.ElytraPieceItem;
import net.mcreator.thedeepvoid.item.DisturbingRootItem;
import net.mcreator.thedeepvoid.item.DevourerTendrilItem;
import net.mcreator.thedeepvoid.item.DevourerShieldItem;
import net.mcreator.thedeepvoid.item.DevourerHookItem;
import net.mcreator.thedeepvoid.item.DarkmareItem;
import net.mcreator.thedeepvoid.item.CultItem;
import net.mcreator.thedeepvoid.item.CruelStilettoItem;
import net.mcreator.thedeepvoid.item.CreepOMeterItem;
import net.mcreator.thedeepvoid.item.CrawlerOmeletteItem;
import net.mcreator.thedeepvoid.item.CrawlerItem;
import net.mcreator.thedeepvoid.item.CookedCrawlerEggItem;
import net.mcreator.thedeepvoid.item.CinnabarRollItem;
import net.mcreator.thedeepvoid.item.CinnabarItem;
import net.mcreator.thedeepvoid.item.ChasmsMusicDiscItem;
import net.mcreator.thedeepvoid.item.ChainsawItem;
import net.mcreator.thedeepvoid.item.BoneSwordItem;
import net.mcreator.thedeepvoid.item.BoneShovelItem;
import net.mcreator.thedeepvoid.item.BonePickaxeItem;
import net.mcreator.thedeepvoid.item.BoneNeedleItem;
import net.mcreator.thedeepvoid.item.BoneMushItem;
import net.mcreator.thedeepvoid.item.BoneLoafItem;
import net.mcreator.thedeepvoid.item.BoneHoeItem;
import net.mcreator.thedeepvoid.item.BoneCrawlerChitinItem;
import net.mcreator.thedeepvoid.item.BoneBallItem;
import net.mcreator.thedeepvoid.item.BoneAxeItem;
import net.mcreator.thedeepvoid.item.BloodyTongueItem;
import net.mcreator.thedeepvoid.item.BloodyRibCageItem;
import net.mcreator.thedeepvoid.item.BlackMossItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteSwordItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteShovelItem;
import net.mcreator.thedeepvoid.item.BismuthNetheritePickaxeItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteHoeItem;
import net.mcreator.thedeepvoid.item.BismuthNetheriteAxeItem;
import net.mcreator.thedeepvoid.item.BismuthItem;
import net.mcreator.thedeepvoid.item.ApostleOfCatastropheTreasureBagItem;
import net.mcreator.thedeepvoid.item.AnimosityItem;
import net.mcreator.thedeepvoid.item.AnimosityHiddenItem;
import net.mcreator.thedeepvoid.item.AncientOnyxItem;
import net.mcreator.thedeepvoid.item.AmbrosiaItem;
import net.mcreator.thedeepvoid.item.AllSeeingSwordItem;
import net.mcreator.thedeepvoid.item.AllSeeingShovelItem;
import net.mcreator.thedeepvoid.item.AllSeeingPickaxeItem;
import net.mcreator.thedeepvoid.item.AllSeeingItem;
import net.mcreator.thedeepvoid.item.AllSeeingHoeItem;
import net.mcreator.thedeepvoid.item.AllSeeingAxeItem;
import net.mcreator.thedeepvoid.item.AbsorptionNeedleItem;
import net.mcreator.thedeepvoid.TheDeepVoidMod;

public class TheDeepVoidModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, TheDeepVoidMod.MODID);
	public static final DeferredHolder<Item, Item> BLOCK_OF_BONE_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_BONE_PILE);
	public static final DeferredHolder<Item, Item> PILE_OF_BONES = block(TheDeepVoidModBlocks.PILE_OF_BONES);
	public static final DeferredHolder<Item, Item> STALKER_SCYTHE_CLAW = REGISTRY.register("stalker_scythe_claw", StalkerScytheClawItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.ROTTEN_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE = REGISTRY.register("rotten_bone", RottenBoneItem::new);
	public static final DeferredHolder<Item, Item> BONE_MARROW = block(TheDeepVoidModBlocks.BONE_MARROW);
	public static final DeferredHolder<Item, Item> BONE_MUSH = REGISTRY.register("bone_mush", BoneMushItem::new);
	public static final DeferredHolder<Item, Item> CORPSE = block(TheDeepVoidModBlocks.CORPSE);
	public static final DeferredHolder<Item, Item> CORPSE_SPAWN = block(TheDeepVoidModBlocks.CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> BONE_SWORD = REGISTRY.register("bone_sword", BoneSwordItem::new);
	public static final DeferredHolder<Item, Item> BONE_PICKAXE = REGISTRY.register("bone_pickaxe", BonePickaxeItem::new);
	public static final DeferredHolder<Item, Item> BONE_AXE = REGISTRY.register("bone_axe", BoneAxeItem::new);
	public static final DeferredHolder<Item, Item> BONE_SHOVEL = REGISTRY.register("bone_shovel", BoneShovelItem::new);
	public static final DeferredHolder<Item, Item> BONE_HOE = REGISTRY.register("bone_hoe", BoneHoeItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE_ARMOR_HELMET = REGISTRY.register("rotten_bone_armor_helmet", RottenBoneArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE_ARMOR_CHESTPLATE = REGISTRY.register("rotten_bone_armor_chestplate", RottenBoneArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE_ARMOR_LEGGINGS = REGISTRY.register("rotten_bone_armor_leggings", RottenBoneArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BONE_ARMOR_BOOTS = REGISTRY.register("rotten_bone_armor_boots", RottenBoneArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> MOURNER_HIDE = REGISTRY.register("mourner_hide", MournerHideItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_GRASS = doubleBlock(TheDeepVoidModBlocks.ROTTEN_GRASS);
	public static final DeferredHolder<Item, Item> MOSSY_BONE_PILE = block(TheDeepVoidModBlocks.MOSSY_BONE_PILE);
	public static final DeferredHolder<Item, Item> ONYX = REGISTRY.register("onyx", OnyxItem::new);
	public static final DeferredHolder<Item, Item> ONYX_ORE = block(TheDeepVoidModBlocks.ONYX_ORE);
	public static final DeferredHolder<Item, Item> SMITHING_TEMPLATE_ONYX = REGISTRY.register("smithing_template_onyx", SmithingTemplateOnyxItem::new);
	public static final DeferredHolder<Item, Item> FERRYMAN_LANTERN = block(TheDeepVoidModBlocks.FERRYMAN_LANTERN);
	public static final DeferredHolder<Item, Item> FERRYMAN_LANTERN_HANGED = block(TheDeepVoidModBlocks.FERRYMAN_LANTERN_HANGED);
	public static final DeferredHolder<Item, Item> ONYX_ARMOR_HELMET = REGISTRY.register("onyx_armor_helmet", OnyxArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> ONYX_ARMOR_CHESTPLATE = REGISTRY.register("onyx_armor_chestplate", OnyxArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> ONYX_ARMOR_LEGGINGS = REGISTRY.register("onyx_armor_leggings", OnyxArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> ONYX_ARMOR_BOOTS = REGISTRY.register("onyx_armor_boots", OnyxArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> VOID_PENDANT = REGISTRY.register("void_pendant", VoidPendantItem::new);
	public static final DeferredHolder<Item, Item> FORGOTTEN_TOKEN = REGISTRY.register("forgotten_token", ForgottenTokenItem::new);
	public static final DeferredHolder<Item, Item> ONYX_SWORD = REGISTRY.register("onyx_sword", OnyxSwordItem::new);
	public static final DeferredHolder<Item, Item> ONYX_PICKAXE = REGISTRY.register("onyx_pickaxe", OnyxPickaxeItem::new);
	public static final DeferredHolder<Item, Item> ONYX_AXE = REGISTRY.register("onyx_axe", OnyxAxeItem::new);
	public static final DeferredHolder<Item, Item> ONYX_SHOVEL = REGISTRY.register("onyx_shovel", OnyxShovelItem::new);
	public static final DeferredHolder<Item, Item> ONYX_HOE = REGISTRY.register("onyx_hoe", OnyxHoeItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_ONYX);
	public static final DeferredHolder<Item, Item> VOID_DAGGER = REGISTRY.register("void_dagger", VoidDaggerItem::new);
	public static final DeferredHolder<Item, Item> OFF_HAND_VOID_DAGGER = REGISTRY.register("off_hand_void_dagger", OffHandVoidDaggerItem::new);
	public static final DeferredHolder<Item, Item> STALKER_TREAT = REGISTRY.register("stalker_treat", StalkerTreatItem::new);
	public static final DeferredHolder<Item, Item> REFINED_ONYX = REGISTRY.register("refined_onyx", RefinedOnyxItem::new);
	public static final DeferredHolder<Item, Item> BONE_BALL = REGISTRY.register("bone_ball", BoneBallItem::new);
	public static final DeferredHolder<Item, Item> CAVE_GROWTH = block(TheDeepVoidModBlocks.CAVE_GROWTH);
	public static final DeferredHolder<Item, Item> VOID_CORE = block(TheDeepVoidModBlocks.VOID_CORE);
	public static final DeferredHolder<Item, Item> ANCIENT_BOOKSHELF = block(TheDeepVoidModBlocks.ANCIENT_BOOKSHELF);
	public static final DeferredHolder<Item, Item> CUT_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> CUT_ROTTEN_BONE_BLOCK_STAIRS = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK_STAIRS);
	public static final DeferredHolder<Item, Item> CUT_ROTTEN_BONE_BLOCK_SLAB = block(TheDeepVoidModBlocks.CUT_ROTTEN_BONE_BLOCK_SLAB);
	public static final DeferredHolder<Item, Item> CHISELED_CUT_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.CHISELED_CUT_ROTTEN_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> ROTTEN_LOG = block(TheDeepVoidModBlocks.ROTTEN_LOG);
	public static final DeferredHolder<Item, Item> ROTTEN_WOOD = block(TheDeepVoidModBlocks.ROTTEN_WOOD);
	public static final DeferredHolder<Item, Item> GLUTTON_BLOCK = block(TheDeepVoidModBlocks.GLUTTON_BLOCK);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE);
	public static final DeferredHolder<Item, Item> ROTTEN_DART = REGISTRY.register("rotten_dart", RottenDartItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE = REGISTRY.register("lavendite", LavenditeItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ORE = block(TheDeepVoidModBlocks.LAVENDITE_ORE);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_STAIRS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_STAIRS);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_SLAB = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_SLAB);
	public static final DeferredHolder<Item, Item> SMITHING_TEMPLATE_LAVENDITE = REGISTRY.register("smithing_template_lavendite", SmithingTemplateLavenditeItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_IRON_SWORD = REGISTRY.register("lavendite_iron_sword", LavenditeIronSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_DIAMOND_SWORD = REGISTRY.register("lavendite_diamond_sword", LavenditeDiamondSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_NETHERITE_SWORD = REGISTRY.register("lavendite_netherite_sword", LavenditeNetheriteSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ONYX_SWORD = REGISTRY.register("lavendite_onyx_sword", LavenditeOnyxSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_BONE_SWORD = REGISTRY.register("lavendite_bone_sword", LavenditeBoneSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_GOLDEN_SWORD = REGISTRY.register("lavendite_golden_sword", LavenditeGoldenSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_STONE_SWORD = REGISTRY.register("lavendite_stone_sword", LavenditeStoneSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_WOODEN_SWORD = REGISTRY.register("lavendite_wooden_sword", LavenditeWoodenSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_SHIELD = REGISTRY.register("lavendite_shield", LavenditeShieldItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_LAVENDITE = block(TheDeepVoidModBlocks.BLOCK_OF_LAVENDITE);
	public static final DeferredHolder<Item, Item> SMITHING_TEMPLATE_ROT = REGISTRY.register("smithing_template_rot", SmithingTemplateRotItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_WOODEN_SWORD = REGISTRY.register("rotten_wooden_sword", RottenWoodenSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_STONE_SWORD = REGISTRY.register("rotten_stone_sword", RottenStoneSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_GOLDEN_SWORD = REGISTRY.register("rotten_golden_sword", RottenGoldenSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_IRON_SWORD = REGISTRY.register("rotten_iron_sword", RottenIronSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_DIAMOND_SWORD = REGISTRY.register("rotten_diamond_sword", RottenDiamondSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_NETHERITE_SWORD = REGISTRY.register("rotten_netherite_sword", RottenNetheriteSwordItem::new);
	public static final DeferredHolder<Item, Item> ONYX_NEEDLE = REGISTRY.register("onyx_needle", OnyxNeedleItem::new);
	public static final DeferredHolder<Item, Item> LICKER_HOOK = REGISTRY.register("licker_hook", LickerHookItem::new);
	public static final DeferredHolder<Item, Item> BLOODY_TONGUE = REGISTRY.register("bloody_tongue", BloodyTongueItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_TONGUE_HOOK = REGISTRY.register("rotten_tongue_hook", RottenTongueHookItem::new);
	public static final DeferredHolder<Item, Item> VOID_CLOAK_CHESTPLATE = REGISTRY.register("void_cloak_chestplate", VoidCloakItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> VOID_MATTER = REGISTRY.register("void_matter", VoidMatterItem::new);
	public static final DeferredHolder<Item, Item> BONE_CAVE_AIR = block(TheDeepVoidModBlocks.BONE_CAVE_AIR);
	public static final DeferredHolder<Item, Item> HANGING_MARROW = block(TheDeepVoidModBlocks.HANGING_MARROW);
	public static final DeferredHolder<Item, Item> FLESH_BLOCK = block(TheDeepVoidModBlocks.FLESH_BLOCK);
	public static final DeferredHolder<Item, Item> PUSTULENT_FLESH_BLOCK = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BLOCK);
	public static final DeferredHolder<Item, Item> PUS_FLOWER = block(TheDeepVoidModBlocks.PUS_FLOWER);
	public static final DeferredHolder<Item, Item> TENDRILS = block(TheDeepVoidModBlocks.TENDRILS);
	public static final DeferredHolder<Item, Item> TEETH = block(TheDeepVoidModBlocks.TEETH);
	public static final DeferredHolder<Item, Item> FLESH_CAVE_AIR = block(TheDeepVoidModBlocks.FLESH_CAVE_AIR);
	public static final DeferredHolder<Item, Item> EYE_VINE_STEM = block(TheDeepVoidModBlocks.EYE_VINE_STEM);
	public static final DeferredHolder<Item, Item> EYE_VINE = block(TheDeepVoidModBlocks.EYE_VINE);
	public static final DeferredHolder<Item, Item> PUS_SACK = block(TheDeepVoidModBlocks.PUS_SACK);
	public static final DeferredHolder<Item, Item> GREEN_EYE_VINE = block(TheDeepVoidModBlocks.GREEN_EYE_VINE);
	public static final DeferredHolder<Item, Item> RED_EYE_VINE = block(TheDeepVoidModBlocks.RED_EYE_VINE);
	public static final DeferredHolder<Item, Item> YELLOW_EYE_VINE = block(TheDeepVoidModBlocks.YELLOW_EYE_VINE);
	public static final DeferredHolder<Item, Item> PUS_BALL = REGISTRY.register("pus_ball", PusBallItem::new);
	public static final DeferredHolder<Item, Item> DESOLATE_SOIL = block(TheDeepVoidModBlocks.DESOLATE_SOIL);
	public static final DeferredHolder<Item, Item> DESOLATE_GROWTH = block(TheDeepVoidModBlocks.DESOLATE_GROWTH);
	public static final DeferredHolder<Item, Item> DESOLATE_STEM = block(TheDeepVoidModBlocks.DESOLATE_STEM);
	public static final DeferredHolder<Item, Item> VOIDLIGHT = block(TheDeepVoidModBlocks.VOIDLIGHT);
	public static final DeferredHolder<Item, Item> DESOLATE_CAVE_AIR = block(TheDeepVoidModBlocks.DESOLATE_CAVE_AIR);
	public static final DeferredHolder<Item, Item> DESOLATE_LICHEN = block(TheDeepVoidModBlocks.DESOLATE_LICHEN);
	public static final DeferredHolder<Item, Item> VOID_LENS = REGISTRY.register("void_lens", VoidLensItem::new);
	public static final DeferredHolder<Item, Item> SPYGLASS_DUMMY = REGISTRY.register("spyglass_dummy", SpyglassDummyItem::new);
	public static final DeferredHolder<Item, Item> GRIM_SHARD = REGISTRY.register("grim_shard", GrimShardItem::new);
	public static final DeferredHolder<Item, Item> GRIM_GEM = REGISTRY.register("grim_gem", GrimGemItem::new);
	public static final DeferredHolder<Item, Item> GRIM_ROTTEN_BONE_HELMET = REGISTRY.register("grim_rotten_bone_helmet", GrimRottenBoneItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GRIM_ROTTEN_BONE_CHESTPLATE = REGISTRY.register("grim_rotten_bone_chestplate", GrimRottenBoneItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GRIM_ROTTEN_BONE_LEGGINGS = REGISTRY.register("grim_rotten_bone_leggings", GrimRottenBoneItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GRIM_ROTTEN_BONE_BOOTS = REGISTRY.register("grim_rotten_bone_boots", GrimRottenBoneItem.Boots::new);
	public static final DeferredHolder<Item, Item> SMITHING_TEMPLATE_GRIM = REGISTRY.register("smithing_template_grim", SmithingTemplateGrimItem::new);
	public static final DeferredHolder<Item, Item> GRIM_SCYTHE = REGISTRY.register("grim_scythe", GrimScytheItem::new);
	public static final DeferredHolder<Item, Item> EYE_SHIELD = REGISTRY.register("eye_shield", EyeShieldItem::new);
	public static final DeferredHolder<Item, Item> REINFORCED_PICKAXE = REGISTRY.register("reinforced_pickaxe", ReinforcedPickaxeItem::new);
	public static final DeferredHolder<Item, Item> CRACKED_BEDROCK = block(TheDeepVoidModBlocks.CRACKED_BEDROCK);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SERRATED_STALAGMITE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SERRATED_STALAGMITE_BASE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_BASE);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SERRATED_STALAGMITE_MIDDLE = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_MIDDLE);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SERRATED_STALAGMITE_FRUSTUM = block(TheDeepVoidModBlocks.DEEPSLATE_SERRATED_STALAGMITE_FRUSTUM);
	public static final DeferredHolder<Item, Item> BLACK_MOSS = REGISTRY.register("black_moss", BlackMossItem::new);
	public static final DeferredHolder<Item, Item> LIQUID_VOID_BUCKET = REGISTRY.register("liquid_void_bucket", LiquidVoidItem::new);
	public static final DeferredHolder<Item, Item> VOID_FILLED_SPONGE = block(TheDeepVoidModBlocks.VOID_FILLED_SPONGE);
	public static final DeferredHolder<Item, Item> ONYX_FLARE_GUN = REGISTRY.register("onyx_flare_gun", OnyxFlareGunItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ARMOR_HELMET = REGISTRY.register("lavendite_armor_helmet", LavenditeArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ARMOR_CHESTPLATE = REGISTRY.register("lavendite_armor_chestplate", LavenditeArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ARMOR_LEGGINGS = REGISTRY.register("lavendite_armor_leggings", LavenditeArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ARMOR_BOOTS = REGISTRY.register("lavendite_armor_boots", LavenditeArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_SHARD = REGISTRY.register("lavendite_shard", LavenditeShardItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_SWORD = REGISTRY.register("lavendite_sword", LavenditeSwordItem::new);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SARCOPHAGUS = block(TheDeepVoidModBlocks.DEEPSLATE_SARCOPHAGUS);
	public static final DeferredHolder<Item, Item> LURKING_MUSIC_DISC = REGISTRY.register("lurking_music_disc", LurkingMusicDiscItem::new);
	public static final DeferredHolder<Item, Item> SCARE_ARMOR_TRIM = REGISTRY.register("scare_armor_trim", ScareArmorTrimItem::new);
	public static final DeferredHolder<Item, Item> SCAVENGER_ARMOR_TRIM = REGISTRY.register("scavenger_armor_trim", ScavengerArmorTrimItem::new);
	public static final DeferredHolder<Item, Item> DEVOURER_TENDRIL = REGISTRY.register("devourer_tendril", DevourerTendrilItem::new);
	public static final DeferredHolder<Item, Item> DEVOURER_SHIELD = REGISTRY.register("devourer_shield", DevourerShieldItem::new);
	public static final DeferredHolder<Item, Item> DEVOURER_HOOK = REGISTRY.register("devourer_hook", DevourerHookItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_DEVOURER_HOOK = REGISTRY.register("lavendite_devourer_hook", LavenditeDevourerHookItem::new);
	public static final DeferredHolder<Item, Item> CHASMS_MUSIC_DISC = REGISTRY.register("chasms_music_disc", ChasmsMusicDiscItem::new);
	public static final DeferredHolder<Item, Item> AMALGAM_SPAWN_EGG = REGISTRY.register("amalgam_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.AMALGAM, -13234674, -5396066, new Item.Properties()));
	public static final DeferredHolder<Item, Item> VOID_CAVE_AIR = block(TheDeepVoidModBlocks.VOID_CAVE_AIR);
	public static final DeferredHolder<Item, Item> VOID_ROOTS = block(TheDeepVoidModBlocks.VOID_ROOTS);
	public static final DeferredHolder<Item, Item> VOID_ROSE = block(TheDeepVoidModBlocks.VOID_ROSE);
	public static final DeferredHolder<Item, Item> VOID_FERN = block(TheDeepVoidModBlocks.VOID_FERN);
	public static final DeferredHolder<Item, Item> FORBIDDEN_TOME = REGISTRY.register("forbidden_tome", ForbiddenTomeItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_PLANKS = block(TheDeepVoidModBlocks.ROTTEN_PLANKS);
	public static final DeferredHolder<Item, Item> ROTTEN_STAIRS = block(TheDeepVoidModBlocks.ROTTEN_STAIRS);
	public static final DeferredHolder<Item, Item> ROTTEN_SLAB = block(TheDeepVoidModBlocks.ROTTEN_SLAB);
	public static final DeferredHolder<Item, Item> FLESH_BRICKS = block(TheDeepVoidModBlocks.FLESH_BRICKS);
	public static final DeferredHolder<Item, Item> FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.FLESH_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.FLESH_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> PUSTULENT_FLESH_BRICKS = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICKS);
	public static final DeferredHolder<Item, Item> ROTTEN_DOOR = doubleBlock(TheDeepVoidModBlocks.ROTTEN_DOOR);
	public static final DeferredHolder<Item, Item> ROTTEN_TRAPDOOR = block(TheDeepVoidModBlocks.ROTTEN_TRAPDOOR);
	public static final DeferredHolder<Item, Item> WALL_CORPSE = block(TheDeepVoidModBlocks.WALL_CORPSE);
	public static final DeferredHolder<Item, Item> CANOPY_ROTTEN_GRASS = doubleBlock(TheDeepVoidModBlocks.CANOPY_ROTTEN_GRASS);
	public static final DeferredHolder<Item, Item> CANOPY_BONE_MARROW = block(TheDeepVoidModBlocks.CANOPY_BONE_MARROW);
	public static final DeferredHolder<Item, Item> ASH_PILE = block(TheDeepVoidModBlocks.ASH_PILE);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_BRICKS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICKS);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_BRICK_STAIRS = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_BRICK_SLAB = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_WALL = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_WALL);
	public static final DeferredHolder<Item, Item> ANCIENT_DEEPSLATE_BRICK_WALL = block(TheDeepVoidModBlocks.ANCIENT_DEEPSLATE_BRICK_WALL);
	public static final DeferredHolder<Item, Item> COBBLED_ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.COBBLED_ANCIENT_DEEPSLATE);
	public static final DeferredHolder<Item, Item> SMOOTH_ANCIENT_DEEPSLATE = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE);
	public static final DeferredHolder<Item, Item> SMOOTH_ANCIENT_DEEPSLATE_SLAB = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE_SLAB);
	public static final DeferredHolder<Item, Item> PUSTULENT_FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> PUSTULENT_FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.PUSTULENT_FLESH_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> DESOLATE_BRICKS = block(TheDeepVoidModBlocks.DESOLATE_BRICKS);
	public static final DeferredHolder<Item, Item> DESOLATE_BRICK_STAIRS = block(TheDeepVoidModBlocks.DESOLATE_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> DESOLATE_BRICK_SLAB = block(TheDeepVoidModBlocks.DESOLATE_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> FLESH_BRICK_WALL = block(TheDeepVoidModBlocks.FLESH_BRICK_WALL);
	public static final DeferredHolder<Item, Item> DESOLATE_BRICK_WALL = block(TheDeepVoidModBlocks.DESOLATE_BRICK_WALL);
	public static final DeferredHolder<Item, Item> BISMUTH = REGISTRY.register("bismuth", BismuthItem::new);
	public static final DeferredHolder<Item, Item> REFINED_BISMUTH = REGISTRY.register("refined_bismuth", RefinedBismuthItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_ORE = block(TheDeepVoidModBlocks.BISMUTH_ORE);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_HELMET = REGISTRY.register("bismuth_netherite_helmet", BismuthNetheriteItem.Helmet::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_CHESTPLATE = REGISTRY.register("bismuth_netherite_chestplate", BismuthNetheriteItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_LEGGINGS = REGISTRY.register("bismuth_netherite_leggings", BismuthNetheriteItem.Leggings::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_BOOTS = REGISTRY.register("bismuth_netherite_boots", BismuthNetheriteItem.Boots::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_SWORD = REGISTRY.register("bismuth_netherite_sword", BismuthNetheriteSwordItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_PICKAXE = REGISTRY.register("bismuth_netherite_pickaxe", BismuthNetheritePickaxeItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_AXE = REGISTRY.register("bismuth_netherite_axe", BismuthNetheriteAxeItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_SHOVEL = REGISTRY.register("bismuth_netherite_shovel", BismuthNetheriteShovelItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_NETHERITE_HOE = REGISTRY.register("bismuth_netherite_hoe", BismuthNetheriteHoeItem::new);
	public static final DeferredHolder<Item, Item> TEETH_TRAP = block(TheDeepVoidModBlocks.TEETH_TRAP);
	public static final DeferredHolder<Item, Item> TEETH_BLOCK = block(TheDeepVoidModBlocks.TEETH_BLOCK);
	public static final DeferredHolder<Item, Item> ASH_BLOCK = block(TheDeepVoidModBlocks.ASH_BLOCK);
	public static final DeferredHolder<Item, Item> CORPSE_SPAWN_GRAVEYARD = block(TheDeepVoidModBlocks.CORPSE_SPAWN_GRAVEYARD);
	public static final DeferredHolder<Item, Item> EYE_LANTERN = block(TheDeepVoidModBlocks.EYE_LANTERN);
	public static final DeferredHolder<Item, Item> EYE_LANTERN_HANGED = block(TheDeepVoidModBlocks.EYE_LANTERN_HANGED);
	public static final DeferredHolder<Item, Item> BLOCK_OF_BISMUTH = block(TheDeepVoidModBlocks.BLOCK_OF_BISMUTH);
	public static final DeferredHolder<Item, Item> BLOCK_OF_REFINED_BISMUTH = block(TheDeepVoidModBlocks.BLOCK_OF_REFINED_BISMUTH);
	public static final DeferredHolder<Item, Item> ROTTEN_SICKLE = REGISTRY.register("rotten_sickle", ReapingHookItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_FOSSIL = block(TheDeepVoidModBlocks.ROTTEN_FOSSIL);
	public static final DeferredHolder<Item, Item> SMOKE_VENT = block(TheDeepVoidModBlocks.SMOKE_VENT);
	public static final DeferredHolder<Item, Item> BISMUTH_LANTERN = block(TheDeepVoidModBlocks.BISMUTH_LANTERN);
	public static final DeferredHolder<Item, Item> BISMUTH_LANTERN_HANGED = block(TheDeepVoidModBlocks.BISMUTH_LANTERN_HANGED);
	public static final DeferredHolder<Item, Item> ROTTEN_MOSS = block(TheDeepVoidModBlocks.ROTTEN_MOSS);
	public static final DeferredHolder<Item, Item> BISMUTH_GLASS = block(TheDeepVoidModBlocks.BISMUTH_GLASS);
	public static final DeferredHolder<Item, Item> CONNECTED_MARROW = block(TheDeepVoidModBlocks.CONNECTED_MARROW);
	public static final DeferredHolder<Item, Item> SULFUR = REGISTRY.register("sulfur", SulfurItem::new);
	public static final DeferredHolder<Item, Item> SULFUR_ORE = block(TheDeepVoidModBlocks.SULFUR_ORE);
	public static final DeferredHolder<Item, Item> SULFUR_TNT = block(TheDeepVoidModBlocks.SULFUR_TNT);
	public static final DeferredHolder<Item, Item> SULFUR_POWDER = block(TheDeepVoidModBlocks.SULFUR_POWDER);
	public static final DeferredHolder<Item, Item> BLOCK_OF_SULFUR = block(TheDeepVoidModBlocks.BLOCK_OF_SULFUR);
	public static final DeferredHolder<Item, Item> BLUE_FIRE = block(TheDeepVoidModBlocks.BLUE_FIRE);
	public static final DeferredHolder<Item, Item> BLOCK_OF_RAW_SULFUR = block(TheDeepVoidModBlocks.BLOCK_OF_RAW_SULFUR);
	public static final DeferredHolder<Item, Item> SULFUR_GLASS = block(TheDeepVoidModBlocks.SULFUR_GLASS);
	public static final DeferredHolder<Item, Item> SULFUR_LANTERN = block(TheDeepVoidModBlocks.SULFUR_LANTERN);
	public static final DeferredHolder<Item, Item> SULFUR_LANTERN_HANGING = block(TheDeepVoidModBlocks.SULFUR_LANTERN_HANGING);
	public static final DeferredHolder<Item, Item> INFESTED_ROTTEN_LOG = block(TheDeepVoidModBlocks.INFESTED_ROTTEN_LOG);
	public static final DeferredHolder<Item, Item> WATCHING_WILLOW_SAPLING = block(TheDeepVoidModBlocks.WATCHING_WILLOW_SAPLING);
	public static final DeferredHolder<Item, Item> VOIDRIUM_ORE = block(TheDeepVoidModBlocks.VOIDRIUM_ORE);
	public static final DeferredHolder<Item, Item> VOIDRIUM_GEM = REGISTRY.register("voidrium_gem", UmbriumGemItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_VOIDRIUM = block(TheDeepVoidModBlocks.BLOCK_OF_VOIDRIUM);
	public static final DeferredHolder<Item, Item> VOIDRIUM_HELMET = REGISTRY.register("voidrium_helmet", VoidriumItem.Helmet::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_CHESTPLATE = REGISTRY.register("voidrium_chestplate", VoidriumItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_LEGGINGS = REGISTRY.register("voidrium_leggings", VoidriumItem.Leggings::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_BOOTS = REGISTRY.register("voidrium_boots", VoidriumItem.Boots::new);
	public static final DeferredHolder<Item, Item> GRIM_BLOCK = block(TheDeepVoidModBlocks.GRIM_BLOCK);
	public static final DeferredHolder<Item, Item> VOIDRIUM_SWORD = REGISTRY.register("voidrium_sword", VoidriumSwordItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_VOIDRIUM_SWORD = REGISTRY.register("lavendite_voidrium_sword", LavenditeVoidriumSwordItem::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_PICKAXE = REGISTRY.register("voidrium_pickaxe", VoidriumPickaxeItem::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_AXE = REGISTRY.register("voidrium_axe", VoidriumAxeItem::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_SHOVEL = REGISTRY.register("voidrium_shovel", VoidriumShovelItem::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_HOE = REGISTRY.register("voidrium_hoe", VoidriumHoeItem::new);
	public static final DeferredHolder<Item, Item> BIG_TEETH = block(TheDeepVoidModBlocks.BIG_TEETH);
	public static final DeferredHolder<Item, Item> TEETH_TRAP_BLOCK = block(TheDeepVoidModBlocks.TEETH_TRAP_BLOCK);
	public static final DeferredHolder<Item, Item> PEEPING_ROOTS = block(TheDeepVoidModBlocks.PEEPING_ROOTS);
	public static final DeferredHolder<Item, Item> INACTIVE_PEEPING_ROOTS = block(TheDeepVoidModBlocks.INACTIVE_PEEPING_ROOTS);
	public static final DeferredHolder<Item, Item> PILE_OF_BONES_BLOCK = block(TheDeepVoidModBlocks.PILE_OF_BONES_BLOCK);
	public static final DeferredHolder<Item, Item> FLESHY_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> HARD_FLESH_BLOCK = block(TheDeepVoidModBlocks.HARD_FLESH_BLOCK);
	public static final DeferredHolder<Item, Item> HARD_FLESH_STAIRS = block(TheDeepVoidModBlocks.HARD_FLESH_STAIRS);
	public static final DeferredHolder<Item, Item> HARD_FLESH_SLAB = block(TheDeepVoidModBlocks.HARD_FLESH_SLAB);
	public static final DeferredHolder<Item, Item> CRACKED_BEDROCK_STAIRS = block(TheDeepVoidModBlocks.CRACKED_BEDROCK_STAIRS);
	public static final DeferredHolder<Item, Item> CRACKED_BEDROCK_SLAB = block(TheDeepVoidModBlocks.CRACKED_BEDROCK_SLAB);
	public static final DeferredHolder<Item, Item> FAKE_BEDROCK = block(TheDeepVoidModBlocks.FAKE_BEDROCK);
	public static final DeferredHolder<Item, Item> FAKE_BEDROCK_STAIRS = block(TheDeepVoidModBlocks.FAKE_BEDROCK_STAIRS);
	public static final DeferredHolder<Item, Item> FAKE_BEDROCK_SLAB = block(TheDeepVoidModBlocks.FAKE_BEDROCK_SLAB);
	public static final DeferredHolder<Item, Item> GORE_STEMS = block(TheDeepVoidModBlocks.GORE_STEMS);
	public static final DeferredHolder<Item, Item> GROUND_BONES = block(TheDeepVoidModBlocks.GROUND_BONES);
	public static final DeferredHolder<Item, Item> GROUND_BONES_PLANT = block(TheDeepVoidModBlocks.GROUND_BONES_PLANT);
	public static final DeferredHolder<Item, Item> FOSSILIZED_FLESH = block(TheDeepVoidModBlocks.FOSSILIZED_FLESH);
	public static final DeferredHolder<Item, Item> FLESH_CHUNK = REGISTRY.register("flesh_chunk", FleshChunkItem::new);
	public static final DeferredHolder<Item, Item> FLESH_ARMOR_HELMET = REGISTRY.register("flesh_armor_helmet", FleshArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> FLESH_ARMOR_CHESTPLATE = REGISTRY.register("flesh_armor_chestplate", FleshArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> FLESH_ARMOR_LEGGINGS = REGISTRY.register("flesh_armor_leggings", FleshArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> FLESH_ARMOR_BOOTS = REGISTRY.register("flesh_armor_boots", FleshArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> HARD_FLESH_INGOT = REGISTRY.register("hard_flesh_ingot", HardFleshIngotItem::new);
	public static final DeferredHolder<Item, Item> GRAVEDIGGER_SHOVEL = REGISTRY.register("gravedigger_shovel", GravediggerShovelItem::new);
	public static final DeferredHolder<Item, Item> HARD_FLESH_SWORD = REGISTRY.register("hard_flesh_sword", HardFleshSwordItem::new);
	public static final DeferredHolder<Item, Item> BONE_PILE_BRICKS = block(TheDeepVoidModBlocks.BONE_PILE_BRICKS);
	public static final DeferredHolder<Item, Item> BONE_PILE_BRICK_STAIRS = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> BONE_PILE_BRICK_SLAB = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> BONE_PILE_BRICK_WALL = block(TheDeepVoidModBlocks.BONE_PILE_BRICK_WALL);
	public static final DeferredHolder<Item, Item> COMPACT_BONE_PILE = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE);
	public static final DeferredHolder<Item, Item> COMPACT_BONE_PILE_STAIRS = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE_STAIRS);
	public static final DeferredHolder<Item, Item> COMPACT_BONE_PILE_SLAB = block(TheDeepVoidModBlocks.COMPACT_BONE_PILE_SLAB);
	public static final DeferredHolder<Item, Item> AMBROSIA = REGISTRY.register("ambrosia", AmbrosiaItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_GLASS_PANE = block(TheDeepVoidModBlocks.BISMUTH_GLASS_PANE);
	public static final DeferredHolder<Item, Item> SULFUR_GLASS_PANE = block(TheDeepVoidModBlocks.SULFUR_GLASS_PANE);
	public static final DeferredHolder<Item, Item> ASHEN_VOID_FERN = block(TheDeepVoidModBlocks.ASHEN_VOID_FERN);
	public static final DeferredHolder<Item, Item> DEEPSLATE_SARCOPHAGUS_BLOCK = block(TheDeepVoidModBlocks.DEEPSLATE_SARCOPHAGUS_BLOCK);
	public static final DeferredHolder<Item, Item> SMOOTH_ANCIENT_DEEPSLATE_STAIRS = block(TheDeepVoidModBlocks.SMOOTH_ANCIENT_DEEPSLATE_STAIRS);
	public static final DeferredHolder<Item, Item> ASH_BRICKS = block(TheDeepVoidModBlocks.ASH_BRICKS);
	public static final DeferredHolder<Item, Item> ASH_BRICK_STAIRS = block(TheDeepVoidModBlocks.ASH_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> ASH_BRICK_SLAB = block(TheDeepVoidModBlocks.ASH_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> ASH_BRICK_WALL = block(TheDeepVoidModBlocks.ASH_BRICK_WALL);
	public static final DeferredHolder<Item, Item> DEEPSLATE_LAVA_GEYSER = block(TheDeepVoidModBlocks.DEEPSLATE_LAVA_GEYSER);
	public static final DeferredHolder<Item, Item> ASHEN_CAVE_AIR = block(TheDeepVoidModBlocks.ASHEN_CAVE_AIR);
	public static final DeferredHolder<Item, Item> SORROW_ARMOR_TRIM = REGISTRY.register("sorrow_armor_trim", SorrowArmorTrimItem::new);
	public static final DeferredHolder<Item, Item> MONOLITHIC_STONE = block(TheDeepVoidModBlocks.MONOLITHIC_STONE);
	public static final DeferredHolder<Item, Item> SEER = block(TheDeepVoidModBlocks.SEER);
	public static final DeferredHolder<Item, Item> CINNABAR = REGISTRY.register("cinnabar", CinnabarItem::new);
	public static final DeferredHolder<Item, Item> REFINED_CINNABAR = REGISTRY.register("refined_cinnabar", RefinedCinnabarItem::new);
	public static final DeferredHolder<Item, Item> OVERSEER_PILLAR_SPAWN_EGG = REGISTRY.register("overseer_pillar_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.OVERSEER_PILLAR, -15460839, -14216943, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CINNABAR_ORE = block(TheDeepVoidModBlocks.CINNABAR_ORE);
	public static final DeferredHolder<Item, Item> MONOLITHIC_STONE_STAIRS = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_STAIRS);
	public static final DeferredHolder<Item, Item> MONOLITHIC_STONE_SLAB = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_SLAB);
	public static final DeferredHolder<Item, Item> MONOLITHIC_STONE_WALL = block(TheDeepVoidModBlocks.MONOLITHIC_STONE_WALL);
	public static final DeferredHolder<Item, Item> BLOCK_OF_CINNABAR = block(TheDeepVoidModBlocks.BLOCK_OF_CINNABAR);
	public static final DeferredHolder<Item, Item> MONOLITHIC_BRICKS = block(TheDeepVoidModBlocks.MONOLITHIC_BRICKS);
	public static final DeferredHolder<Item, Item> MONOLITHIC_BRICK_STAIRS = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> MONOLITHIC_BRICK_SLAB = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> MONOLITHIC_BRICK_WALL = block(TheDeepVoidModBlocks.MONOLITHIC_BRICK_WALL);
	public static final DeferredHolder<Item, Item> CINNABAR_ROLL = REGISTRY.register("cinnabar_roll", CinnabarRollItem::new);
	public static final DeferredHolder<Item, Item> EYEBALL = REGISTRY.register("eyeball", EyeballItem::new);
	public static final DeferredHolder<Item, Item> BLOSSOMING_DESOLATE_LICHEN = block(TheDeepVoidModBlocks.BLOSSOMING_DESOLATE_LICHEN);
	public static final DeferredHolder<Item, Item> GRIMBERRY = REGISTRY.register("grimberry", GrimberryItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_PICKAXE = REGISTRY.register("all_seeing_pickaxe", AllSeeingPickaxeItem::new);
	public static final DeferredHolder<Item, Item> EYEBALL_SOUP = REGISTRY.register("eyeball_soup", EyeballSoupItem::new);
	public static final DeferredHolder<Item, Item> GRIMBERRY_JUICE = REGISTRY.register("grimberry_juice", GrimberryJuiceItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_AXE = REGISTRY.register("all_seeing_axe", AllSeeingAxeItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_SHOVEL = REGISTRY.register("all_seeing_shovel", AllSeeingShovelItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_HOE = REGISTRY.register("all_seeing_hoe", AllSeeingHoeItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_SWORD = REGISTRY.register("all_seeing_sword", AllSeeingSwordItem::new);
	public static final DeferredHolder<Item, Item> GRIMBERRY_PIE = REGISTRY.register("grimberry_pie", GrimberryPieItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_ALL_SEEING_SWORD = REGISTRY.register("lavendite_all_seeing_sword", LavenditeAllSeeingSwordItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_ALL_SEEING_SWORD = REGISTRY.register("rotten_all_seeing_sword", RottenAllSeeingSwordItem::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_HELMET = REGISTRY.register("all_seeing_helmet", AllSeeingItem.Helmet::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_CHESTPLATE = REGISTRY.register("all_seeing_chestplate", AllSeeingItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_LEGGINGS = REGISTRY.register("all_seeing_leggings", AllSeeingItem.Leggings::new);
	public static final DeferredHolder<Item, Item> ALL_SEEING_BOOTS = REGISTRY.register("all_seeing_boots", AllSeeingItem.Boots::new);
	public static final DeferredHolder<Item, Item> SMOOTH_MONOLITHIC_STONE = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE);
	public static final DeferredHolder<Item, Item> SMOOTH_MONOLITHIC_STONE_STAIRS = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE_STAIRS);
	public static final DeferredHolder<Item, Item> SMOOTH_MONOLITHIC_STONE_SLAB = block(TheDeepVoidModBlocks.SMOOTH_MONOLITHIC_STONE_SLAB);
	public static final DeferredHolder<Item, Item> TRANSFORMED_SEER = block(TheDeepVoidModBlocks.TRANSFORMED_SEER);
	public static final DeferredHolder<Item, Item> MADNESS_LANTERN = block(TheDeepVoidModBlocks.MADNESS_LANTERN);
	public static final DeferredHolder<Item, Item> MADNESS_LANTERN_HANGED = block(TheDeepVoidModBlocks.MADNESS_LANTERN_HANGED);
	public static final DeferredHolder<Item, Item> ROTTEN_FENCE = block(TheDeepVoidModBlocks.ROTTEN_FENCE);
	public static final DeferredHolder<Item, Item> ROTTEN_FENCE_GATE = block(TheDeepVoidModBlocks.ROTTEN_FENCE_GATE);
	public static final DeferredHolder<Item, Item> ROTTEN_PRESSURE_PLATE = block(TheDeepVoidModBlocks.ROTTEN_PRESSURE_PLATE);
	public static final DeferredHolder<Item, Item> ROTTEN_BUTTON = block(TheDeepVoidModBlocks.ROTTEN_BUTTON);
	public static final DeferredHolder<Item, Item> BLOCK_OF_ANCIENT_FLESH = block(TheDeepVoidModBlocks.BLOCK_OF_ANCIENT_FLESH);
	public static final DeferredHolder<Item, Item> CINNABAR_MONOLITH_STONE = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE);
	public static final DeferredHolder<Item, Item> CINNABAR_MONOLITH_STONE_STAIRS = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_STAIRS);
	public static final DeferredHolder<Item, Item> CINNABAR_MONOLITH_STONE_SLAB = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_SLAB);
	public static final DeferredHolder<Item, Item> CINNABAR_MONOLITH_STONE_WALL = block(TheDeepVoidModBlocks.CINNABAR_MONOLITH_STONE_WALL);
	public static final DeferredHolder<Item, Item> ATTRACTOR = block(TheDeepVoidModBlocks.ATTRACTOR);
	public static final DeferredHolder<Item, Item> ATTRACTOR_ON = block(TheDeepVoidModBlocks.ATTRACTOR_ON);
	public static final DeferredHolder<Item, Item> EYE_FLESH_BLOCK = block(TheDeepVoidModBlocks.EYE_FLESH_BLOCK);
	public static final DeferredHolder<Item, Item> ROUGH_VOIDRIUM = REGISTRY.register("rough_voidrium", RoughVoidriumItem::new);
	public static final DeferredHolder<Item, Item> EYE_FLESH_BRICKS = block(TheDeepVoidModBlocks.EYE_FLESH_BRICKS);
	public static final DeferredHolder<Item, Item> EYE_FLESH_BRICK_STAIRS = block(TheDeepVoidModBlocks.EYE_FLESH_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> EYE_FLESH_BRICK_SLAB = block(TheDeepVoidModBlocks.EYE_FLESH_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> PRIMORDIAL_STONE = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE);
	public static final DeferredHolder<Item, Item> PRIMORDIAL_STONE_REPLICA = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_REPLICA);
	public static final DeferredHolder<Item, Item> PRIMORDIAL_STONE_STAIRS = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_STAIRS);
	public static final DeferredHolder<Item, Item> PRIMORDIAL_STONE_SLAB = block(TheDeepVoidModBlocks.PRIMORDIAL_STONE_SLAB);
	public static final DeferredHolder<Item, Item> DISTURBING_ROOT = REGISTRY.register("disturbing_root", DisturbingRootItem::new);
	public static final DeferredHolder<Item, Item> ROOTER = block(TheDeepVoidModBlocks.ROOTER);
	public static final DeferredHolder<Item, Item> ROOTER_ON = block(TheDeepVoidModBlocks.ROOTER_ON);
	public static final DeferredHolder<Item, Item> SHORT_CIRCUIT_ROOTER = block(TheDeepVoidModBlocks.SHORT_CIRCUIT_ROOTER);
	public static final DeferredHolder<Item, Item> INFESTED_ROTTEN_ROOTS = block(TheDeepVoidModBlocks.INFESTED_ROTTEN_ROOTS);
	public static final DeferredHolder<Item, Item> INACTIVE_INFESTED_ROTTEN_ROOTS = block(TheDeepVoidModBlocks.INACTIVE_INFESTED_ROTTEN_ROOTS);
	public static final DeferredHolder<Item, Item> CHISELED_ANCIENT_DEEPSLATE_BRICKS = block(TheDeepVoidModBlocks.CHISELED_ANCIENT_DEEPSLATE_BRICKS);
	public static final DeferredHolder<Item, Item> CHISELED_DESOLATE_BRICKS = block(TheDeepVoidModBlocks.CHISELED_DESOLATE_BRICKS);
	public static final DeferredHolder<Item, Item> ROTTEN_ROOTS = block(TheDeepVoidModBlocks.ROTTEN_ROOTS);
	public static final DeferredHolder<Item, Item> POWERED_LAVA_GEYSER = block(TheDeepVoidModBlocks.POWERED_LAVA_GEYSER);
	public static final DeferredHolder<Item, Item> POWERED_LAVA_GEYSER_ON = block(TheDeepVoidModBlocks.POWERED_LAVA_GEYSER_ON);
	public static final DeferredHolder<Item, Item> CRUMBLING_DEEPSLATE = block(TheDeepVoidModBlocks.CRUMBLING_DEEPSLATE);
	public static final DeferredHolder<Item, Item> CRUMBLING_BEDROCK = block(TheDeepVoidModBlocks.CRUMBLING_BEDROCK);
	public static final DeferredHolder<Item, Item> COVERED_CORPSE = block(TheDeepVoidModBlocks.COVERED_CORPSE);
	public static final DeferredHolder<Item, Item> COVERED_CORPSE_SPAWN = block(TheDeepVoidModBlocks.COVERED_CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> CORPSE_CHANDELIER = block(TheDeepVoidModBlocks.CORPSE_CHANDELIER);
	public static final DeferredHolder<Item, Item> JACK_O_CORPSE = block(TheDeepVoidModBlocks.JACK_O_CORPSE);
	public static final DeferredHolder<Item, Item> JACK_O_COVERED_CORPSE = block(TheDeepVoidModBlocks.JACK_O_COVERED_CORPSE);
	public static final DeferredHolder<Item, Item> JACK_O_WALL_CORPSE = block(TheDeepVoidModBlocks.JACK_O_WALL_CORPSE);
	public static final DeferredHolder<Item, Item> ROOTING_TOME = REGISTRY.register("rooting_tome", RootingTomeItem::new);
	public static final DeferredHolder<Item, Item> GRIM_SICKLE = REGISTRY.register("grim_sickle", GrimSickleItem::new);
	public static final DeferredHolder<Item, Item> LURKER_HEAD = block(TheDeepVoidModBlocks.LURKER_HEAD);
	public static final DeferredHolder<Item, Item> VOIDLIGHT_BRICKS = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICKS);
	public static final DeferredHolder<Item, Item> VOIDLIGHT_BRICK_STAIRS = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> VOIDLIGHT_BRICK_SLAB = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> VOIDLIGHT_BRICK_WALL = block(TheDeepVoidModBlocks.VOIDLIGHT_BRICK_WALL);
	public static final DeferredHolder<Item, Item> CHISELED_VOIDLIGHT = block(TheDeepVoidModBlocks.CHISELED_VOIDLIGHT);
	public static final DeferredHolder<Item, Item> DEAD_FERRYMAN = block(TheDeepVoidModBlocks.DEAD_FERRYMAN);
	public static final DeferredHolder<Item, Item> HANGED_LURKER_HEAD = block(TheDeepVoidModBlocks.HANGED_LURKER_HEAD);
	public static final DeferredHolder<Item, Item> GOLDEN_EYEBALL = REGISTRY.register("golden_eyeball", GoldenEyeballItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_SKULL_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_SKULL_PILE);
	public static final DeferredHolder<Item, Item> GRIM_SOIL = block(TheDeepVoidModBlocks.GRIM_SOIL);
	public static final DeferredHolder<Item, Item> COVERED_SKULL_PILE = block(TheDeepVoidModBlocks.COVERED_SKULL_PILE);
	public static final DeferredHolder<Item, Item> COVERED_BONE_PILE = block(TheDeepVoidModBlocks.COVERED_BONE_PILE);
	public static final DeferredHolder<Item, Item> HANGING_GOO = block(TheDeepVoidModBlocks.HANGING_GOO);
	public static final DeferredHolder<Item, Item> GOO_COVER = block(TheDeepVoidModBlocks.GOO_COVER);
	public static final DeferredHolder<Item, Item> GOO_COVER_BLOCK = block(TheDeepVoidModBlocks.GOO_COVER_BLOCK);
	public static final DeferredHolder<Item, Item> CONNECTED_HANGING_GOO = block(TheDeepVoidModBlocks.CONNECTED_HANGING_GOO);
	public static final DeferredHolder<Item, Item> BLOCK_OF_GOO = block(TheDeepVoidModBlocks.BLOCK_OF_GOO);
	public static final DeferredHolder<Item, Item> BONE_CRAWLER_EGG = block(TheDeepVoidModBlocks.BONE_CRAWLER_EGG);
	public static final DeferredHolder<Item, Item> BONE_CRAWLER_EGG_GENERATE = block(TheDeepVoidModBlocks.BONE_CRAWLER_EGG_GENERATE);
	public static final DeferredHolder<Item, Item> REGURGITATED_MATTER = block(TheDeepVoidModBlocks.REGURGITATED_MATTER);
	public static final DeferredHolder<Item, Item> GOO_GROWTH = doubleBlock(TheDeepVoidModBlocks.GOO_GROWTH);
	public static final DeferredHolder<Item, Item> GOO_BALL = REGISTRY.register("goo_ball", GooBallItem::new);
	public static final DeferredHolder<Item, Item> GOO_BRICKS = block(TheDeepVoidModBlocks.GOO_BRICKS);
	public static final DeferredHolder<Item, Item> GOO_BRICK_STAIRS = block(TheDeepVoidModBlocks.GOO_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> GOO_BRICK_SLAB = block(TheDeepVoidModBlocks.GOO_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> GOO_BRICK_WALL = block(TheDeepVoidModBlocks.GOO_BRICK_WALL);
	public static final DeferredHolder<Item, Item> GOO_WEB = block(TheDeepVoidModBlocks.GOO_WEB);
	public static final DeferredHolder<Item, Item> ROTTEN_FLESH_CHUNK = block(TheDeepVoidModBlocks.ROTTEN_FLESH_CHUNK);
	public static final DeferredHolder<Item, Item> HANGING_ROTTEN_FLESH = block(TheDeepVoidModBlocks.HANGING_ROTTEN_FLESH);
	public static final DeferredHolder<Item, Item> ROTTEN_FLESH_STAIRS = block(TheDeepVoidModBlocks.ROTTEN_FLESH_STAIRS);
	public static final DeferredHolder<Item, Item> ROTTEN_FLESH_SLAB = block(TheDeepVoidModBlocks.ROTTEN_FLESH_SLAB);
	public static final DeferredHolder<Item, Item> MELTED_GOO = block(TheDeepVoidModBlocks.MELTED_GOO);
	public static final DeferredHolder<Item, Item> MELTED_GOO_STAIRS = block(TheDeepVoidModBlocks.MELTED_GOO_STAIRS);
	public static final DeferredHolder<Item, Item> MELTED_GOO_SLAB = block(TheDeepVoidModBlocks.MELTED_GOO_SLAB);
	public static final DeferredHolder<Item, Item> ROTTING_CORPSE = block(TheDeepVoidModBlocks.ROTTING_CORPSE);
	public static final DeferredHolder<Item, Item> ROTTING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> ROTTING_COVERED_CORPSE = block(TheDeepVoidModBlocks.ROTTING_COVERED_CORPSE);
	public static final DeferredHolder<Item, Item> ROTTING_COVERED_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_COVERED_CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> ROTTING_LAYING_CORPSE = block(TheDeepVoidModBlocks.ROTTING_LAYING_CORPSE);
	public static final DeferredHolder<Item, Item> ROTTING_LAYING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.ROTTING_LAYING_CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> ROTTING_WALL_CORPSE = block(TheDeepVoidModBlocks.ROTTING_WALL_CORPSE);
	public static final DeferredHolder<Item, Item> TRANSLUCENT_GOO = block(TheDeepVoidModBlocks.TRANSLUCENT_GOO);
	public static final DeferredHolder<Item, Item> COOKED_CRAWLER_EGG = REGISTRY.register("cooked_crawler_egg", CookedCrawlerEggItem::new);
	public static final DeferredHolder<Item, Item> CRAWLER_OMELETTE = REGISTRY.register("crawler_omelette", CrawlerOmeletteItem::new);
	public static final DeferredHolder<Item, Item> BIG_BLUE_EYE = block(TheDeepVoidModBlocks.BIG_BLUE_EYE);
	public static final DeferredHolder<Item, Item> BIG_GREEN_EYE = block(TheDeepVoidModBlocks.BIG_GREEN_EYE);
	public static final DeferredHolder<Item, Item> BIG_RED_EYE = block(TheDeepVoidModBlocks.BIG_RED_EYE);
	public static final DeferredHolder<Item, Item> BIG_YELLOW_EYE = block(TheDeepVoidModBlocks.BIG_YELLOW_EYE);
	public static final DeferredHolder<Item, Item> HUGE_EYE_VINE_STEM = block(TheDeepVoidModBlocks.HUGE_EYE_VINE_STEM);
	public static final DeferredHolder<Item, Item> POROUS_FLESH = block(TheDeepVoidModBlocks.POROUS_FLESH);
	public static final DeferredHolder<Item, Item> VEINY_FLESH = block(TheDeepVoidModBlocks.VEINY_FLESH);
	public static final DeferredHolder<Item, Item> GAPING_POROUS_FLESH = block(TheDeepVoidModBlocks.GAPING_POROUS_FLESH);
	public static final DeferredHolder<Item, Item> CARRION = block(TheDeepVoidModBlocks.CARRION);
	public static final DeferredHolder<Item, Item> MESSY_FLESH = block(TheDeepVoidModBlocks.MESSY_FLESH);
	public static final DeferredHolder<Item, Item> HATCHING_ENZYME = REGISTRY.register("hatching_enzyme", HatchingEnzymeItem::new);
	public static final DeferredHolder<Item, Item> VULTURE_MUZZLE = REGISTRY.register("vulture_muzzle", VultureMuzzleItem::new);
	public static final DeferredHolder<Item, Item> RIDING_CROP = REGISTRY.register("riding_crop", RidingCropItem::new);
	public static final DeferredHolder<Item, Item> BONE_CRAWLER_CHITIN = REGISTRY.register("bone_crawler_chitin", BoneCrawlerChitinItem::new);
	public static final DeferredHolder<Item, Item> CRAWLER_HELMET = REGISTRY.register("crawler_helmet", CrawlerItem.Helmet::new);
	public static final DeferredHolder<Item, Item> CRAWLER_CHESTPLATE = REGISTRY.register("crawler_chestplate", CrawlerItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> CRAWLER_LEGGINGS = REGISTRY.register("crawler_leggings", CrawlerItem.Leggings::new);
	public static final DeferredHolder<Item, Item> CRAWLER_BOOTS = REGISTRY.register("crawler_boots", CrawlerItem.Boots::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_GLASS = block(TheDeepVoidModBlocks.VOIDRIUM_GLASS);
	public static final DeferredHolder<Item, Item> GRIM_CRAWLER_HELMET = REGISTRY.register("grim_crawler_helmet", GrimCrawlerItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GRIM_CRAWLER_CHESTPLATE = REGISTRY.register("grim_crawler_chestplate", GrimCrawlerItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GRIM_CRAWLER_LEGGINGS = REGISTRY.register("grim_crawler_leggings", GrimCrawlerItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GRIM_CRAWLER_BOOTS = REGISTRY.register("grim_crawler_boots", GrimCrawlerItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOO_SWORD = REGISTRY.register("goo_sword", GooSwordItem::new);
	public static final DeferredHolder<Item, Item> SULFUR_BOMB = REGISTRY.register("sulfur_bomb", SulfurBombItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_ROTTEN_BONE_PILE = block(TheDeepVoidModBlocks.BLOCK_OF_ROTTEN_BONE_PILE);
	public static final DeferredHolder<Item, Item> CULT_HELMET = REGISTRY.register("cult_helmet", CultItem.Helmet::new);
	public static final DeferredHolder<Item, Item> CULT_CHESTPLATE = REGISTRY.register("cult_chestplate", CultItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> CULT_LEGGINGS = REGISTRY.register("cult_leggings", CultItem.Leggings::new);
	public static final DeferredHolder<Item, Item> CULT_BOOTS = REGISTRY.register("cult_boots", CultItem.Boots::new);
	public static final DeferredHolder<Item, Item> CINNABAR_CHAIN = block(TheDeepVoidModBlocks.CINNABAR_CHAIN);
	public static final DeferredHolder<Item, Item> WEAVER_MASK_HELMET = REGISTRY.register("weaver_mask_helmet", WeaverMaskItem.Helmet::new);
	public static final DeferredHolder<Item, Item> LAYING_CORPSE = block(TheDeepVoidModBlocks.LAYING_CORPSE);
	public static final DeferredHolder<Item, Item> JACK_O_LAYING_CORPSE = block(TheDeepVoidModBlocks.JACK_O_LAYING_CORPSE);
	public static final DeferredHolder<Item, Item> LAYING_CORPSE_SPAWN = block(TheDeepVoidModBlocks.LAYING_CORPSE_SPAWN);
	public static final DeferredHolder<Item, Item> SINS_AND_SINNERS = REGISTRY.register("sins_and_sinners", SinsAndSinnersItem::new);
	public static final DeferredHolder<Item, Item> WEAVER_ROBE_CHESTPLATE = REGISTRY.register("weaver_robe_chestplate", WeaverRobeItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> SACRED_CINNABAR = REGISTRY.register("sacred_cinnabar", SacredCinnabarItem::new);
	public static final DeferredHolder<Item, Item> SACRED_VOIDRIUM_HELMET = REGISTRY.register("sacred_voidrium_helmet", SacredVoidriumItem.Helmet::new);
	public static final DeferredHolder<Item, Item> SACRED_VOIDRIUM_CHESTPLATE = REGISTRY.register("sacred_voidrium_chestplate", SacredVoidriumItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> SACRED_VOIDRIUM_LEGGINGS = REGISTRY.register("sacred_voidrium_leggings", SacredVoidriumItem.Leggings::new);
	public static final DeferredHolder<Item, Item> SACRED_VOIDRIUM_BOOTS = REGISTRY.register("sacred_voidrium_boots", SacredVoidriumItem.Boots::new);
	public static final DeferredHolder<Item, Item> GRIM_LAVENDITE_HELMET = REGISTRY.register("grim_lavendite_helmet", GrimLavenditeItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GRIM_LAVENDITE_CHESTPLATE = REGISTRY.register("grim_lavendite_chestplate", GrimLavenditeItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GRIM_LAVENDITE_LEGGINGS = REGISTRY.register("grim_lavendite_leggings", GrimLavenditeItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GRIM_LAVENDITE_BOOTS = REGISTRY.register("grim_lavendite_boots", GrimLavenditeItem.Boots::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_RAW_CINNABAR = block(TheDeepVoidModBlocks.BLOCK_OF_RAW_CINNABAR);
	public static final DeferredHolder<Item, Item> ANCIENT_ONYX = REGISTRY.register("ancient_onyx", AncientOnyxItem::new);
	public static final DeferredHolder<Item, Item> BISMUTH_BRICKS = block(TheDeepVoidModBlocks.BISMUTH_BRICKS);
	public static final DeferredHolder<Item, Item> BISMUTH_BRICK_STAIRS = block(TheDeepVoidModBlocks.BISMUTH_BRICK_STAIRS);
	public static final DeferredHolder<Item, Item> BISMUTH_BRICK_SLAB = block(TheDeepVoidModBlocks.BISMUTH_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> BLOCK_OF_REFINED_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_REFINED_ONYX);
	public static final DeferredHolder<Item, Item> BLOCK_OF_ANCIENT_ONYX = block(TheDeepVoidModBlocks.BLOCK_OF_ANCIENT_ONYX);
	public static final DeferredHolder<Item, Item> REFINED_ONYX_STAIRS = block(TheDeepVoidModBlocks.REFINED_ONYX_STAIRS);
	public static final DeferredHolder<Item, Item> REFINED_ONYX_SLAB = block(TheDeepVoidModBlocks.REFINED_ONYX_SLAB);
	public static final DeferredHolder<Item, Item> CRUEL_STILETTO = REGISTRY.register("cruel_stiletto", CruelStilettoItem::new);
	public static final DeferredHolder<Item, Item> SHADESTORM = REGISTRY.register("shadestorm", ShadestormItem::new);
	public static final DeferredHolder<Item, Item> MOURNER_SPAWN_EGG = REGISTRY.register("mourner_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.MOURNER, -16777216, -14408668, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("bone_crawler_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.BONE_CRAWLER, -14474721, -10724523, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FOOL_EATER_SPAWN_EGG = REGISTRY.register("fool_eater_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.FOOL_EATER, -15790835, -13298925, new Item.Properties()));
	public static final DeferredHolder<Item, Item> HALLUCINATION_SPAWN_EGG = REGISTRY.register("hallucination_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.HALLUCINATION, -15987700, -12632257, new Item.Properties()));
	public static final DeferredHolder<Item, Item> LURKER_SPAWN_EGG = REGISTRY.register("lurker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.LURKER, -13685463, -11712192, new Item.Properties()));
	public static final DeferredHolder<Item, Item> STALKER_SPAWN_EGG = REGISTRY.register("stalker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.STALKER, -15132648, -13752280, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ABDUCTOR_SPAWN_EGG = REGISTRY.register("abductor_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ABDUCTOR, -13882324, -15790321, new Item.Properties()));
	public static final DeferredHolder<Item, Item> VOID_DWELLER_SPAWN_EGG = REGISTRY.register("void_dweller_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.VOID_DWELLER, -15132123, -12829636, new Item.Properties()));
	public static final DeferredHolder<Item, Item> LICKER_SPAWN_EGG = REGISTRY.register("licker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.LICKER, -14934235, -12517376, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FLESH_CUBE_SPAWN_EGG = REGISTRY.register("flesh_cube_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.FLESH_CUBE, -13887207, -13096920, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SPORE_SPEWER_SPAWN_EGG = REGISTRY.register("spore_spewer_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SPORE_SPEWER, -14151407, -11450067, new Item.Properties()));
	public static final DeferredHolder<Item, Item> WANDERER_SPAWN_EGG = REGISTRY.register("wanderer_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.WANDERER, -11908798, -15395563, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GRAVEKEEPER_SPAWN_EGG = REGISTRY.register("gravekeeper_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.GRAVEKEEPER, -12303809, -14408927, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GOO_SPITTER_SPAWN_EGG = REGISTRY.register("goo_spitter_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.GOO_SPITTER, -14474721, -10724523, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ROAMER_SPAWN_EGG = REGISTRY.register("roamer_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ROAMER, -11448500, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ENDLESS_QUIVER = REGISTRY.register("endless_quiver", EndlessQuiverItem::new);
	public static final DeferredHolder<Item, Item> MOTHER_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("mother_bone_crawler_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.MOTHER_BONE_CRAWLER, -14145757, -5786461, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ALPHA_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("alpha_bone_crawler_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ALPHA_BONE_CRAWLER, -15593201, -13224397, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BABY_BONE_CRAWLER_SPAWN_EGG = REGISTRY.register("baby_bone_crawler_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.BABY_BONE_CRAWLER, -10790830, -7698308, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ROTTEN_CORPSE_SPAWN_EGG = REGISTRY.register("rotten_corpse_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ROTTEN_CORPSE, -6513508, -11711422, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ROTTEN_CULT_MEMBER_SPAWN_EGG = REGISTRY.register("rotten_cult_member_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ROTTEN_CULT_MEMBER, -6513508, -16053493, new Item.Properties()));
	public static final DeferredHolder<Item, Item> EYEKIN_SPAWN_EGG = REGISTRY.register("eyekin_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.EYEKIN, -10551296, -11099436, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SWARMER_SPAWN_EGG = REGISTRY.register("swarmer_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SWARMER, -10019812, -14271126, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DEATH_MAW_SPAWN_EGG = REGISTRY.register("death_maw_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.DEATH_MAW, -15987700, -13684945, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BEHOLDER_SPAWN_EGG = REGISTRY.register("beholder_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.BEHOLDER, -13955570, -3357500, new Item.Properties()));
	public static final DeferredHolder<Item, Item> EVERHUNGER_SPAWN_EGG = REGISTRY.register("everhunger_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.EVERHUNGER, -13890034, -6779263, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DEATH_VULTURE_SPAWN_EGG = REGISTRY.register("death_vulture_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.DEATH_VULTURE, -15329770, -4342877, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DEVOURER_SPAWN_EGG = REGISTRY.register("devourer_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.DEVOURER, -15268603, -7455170, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ROOTED_SPAWN_EGG = REGISTRY.register("rooted_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.ROOTED, -14474718, -8421505, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SCARECROW_SPAWN_EGG = REGISTRY.register("scarecrow_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SCARECROW, -13697024, -3816264, new Item.Properties()));
	public static final DeferredHolder<Item, Item> NIGHTMARE_SPAWN_EGG = REGISTRY.register("nightmare_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.NIGHTMARE, -15526884, -14013133, new Item.Properties()));
	public static final DeferredHolder<Item, Item> OVERSEER_BIG_PILLAR_SPAWN_EGG = REGISTRY.register("overseer_big_pillar_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.OVERSEER_BIG_PILLAR, -15460839, -14216943, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BONE_LOAF = REGISTRY.register("bone_loaf", BoneLoafItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_DELIGHT = REGISTRY.register("rotten_delight", RottenDelightItem::new);
	public static final DeferredHolder<Item, Item> CREEP_O_METER = REGISTRY.register("creep_o_meter", CreepOMeterItem::new);
	public static final DeferredHolder<Item, Item> CENTIGAZE_SPAWN_EGG = REGISTRY.register("centigaze_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.CENTIGAZE, -16382190, -14475466, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DESOLATE_SOIL_ACTIVE = block(TheDeepVoidModBlocks.DESOLATE_SOIL_ACTIVE);
	public static final DeferredHolder<Item, Item> STALKING_STALKER_SPAWN_EGG = REGISTRY.register("stalking_stalker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.STALKING_STALKER, -16053493, -14475232, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SHADOW_SPAWN_EGG = REGISTRY.register("shadow_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SHADOW, -16777216, -15329770, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SOUL_CLEAVER = REGISTRY.register("soul_cleaver", SoulCleaverItem::new);
	public static final DeferredHolder<Item, Item> WEAVER_LEGGINGS_LEGGINGS = REGISTRY.register("weaver_leggings_leggings", WeaverLeggingsItem.Leggings::new);
	public static final DeferredHolder<Item, Item> WEAVER_BOOTS_BOOTS = REGISTRY.register("weaver_boots_boots", WeaverBootsItem.Boots::new);
	public static final DeferredHolder<Item, Item> WATCHING_STALKER_SPAWN_EGG = REGISTRY.register("watching_stalker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.WATCHING_STALKER, -16777216, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> VOID_MIRROR = REGISTRY.register("void_mirror", VoidMirrorItem::new);
	public static final DeferredHolder<Item, Item> WEAVER_OF_SOULS_SPAWN_EGG = REGISTRY.register("weaver_of_souls_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.WEAVER_OF_SOULS, -15724528, -15786978, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DARKMARE = REGISTRY.register("darkmare", DarkmareItem::new);
	public static final DeferredHolder<Item, Item> HAND_SPAWN_SPAWN_EGG = REGISTRY.register("hand_spawn_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.HAND_SPAWN, -16760499, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DAMNED_SPAWN_EGG = REGISTRY.register("damned_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.DAMNED, -15396334, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SOUL_ORB_PILLAR = block(TheDeepVoidModBlocks.SOUL_ORB_PILLAR);
	public static final DeferredHolder<Item, Item> SOUL_ORB_SPAWN_EGG = REGISTRY.register("soul_orb_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SOUL_ORB, -16743782, -12590593, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SOUL_CONTAINER = block(TheDeepVoidModBlocks.SOUL_CONTAINER);
	public static final DeferredHolder<Item, Item> CHAINED_WEAVER_SPAWN_EGG = REGISTRY.register("chained_weaver_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.CHAINED_WEAVER, -12036769, -15786978, new Item.Properties()));
	public static final DeferredHolder<Item, Item> HEXED_DOLL = REGISTRY.register("hexed_doll", HexedDollItem::new);
	public static final DeferredHolder<Item, Item> WEAVER_OF_SOULS_TREASURE_BAG = REGISTRY.register("weaver_of_souls_treasure_bag", WeaverOfSoulsTreasureBagItem::new);
	public static final DeferredHolder<Item, Item> VOODOO_DOLL = REGISTRY.register("voodoo_doll", VoodooDollItem::new);
	public static final DeferredHolder<Item, Item> SOUL_SHARD = REGISTRY.register("soul_shard", SoulShardItem::new);
	public static final DeferredHolder<Item, Item> THE_HARVEST = REGISTRY.register("the_harvest", TheHarvestItem::new);
	public static final DeferredHolder<Item, Item> HARVESTER_MASK_HELMET = REGISTRY.register("harvester_mask_helmet", HarvesterMaskItem.Helmet::new);
	public static final DeferredHolder<Item, Item> TOMBSTONE = REGISTRY.register("tombstone", TombstoneItem::new);
	public static final DeferredHolder<Item, Item> VOID_EFFIGY = block(TheDeepVoidModBlocks.VOID_EFFIGY);
	public static final DeferredHolder<Item, Item> VOID_EFFIGY_OPEN = block(TheDeepVoidModBlocks.VOID_EFFIGY_OPEN);
	public static final DeferredHolder<Item, Item> CINNABAR_GLASS = block(TheDeepVoidModBlocks.CINNABAR_GLASS);
	public static final DeferredHolder<Item, Item> CINNABAR_GLASS_PANE = block(TheDeepVoidModBlocks.CINNABAR_GLASS_PANE);
	public static final DeferredHolder<Item, Item> FLESH_GLOVE = REGISTRY.register("flesh_glove", FleshGloveItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_PICKAXE = REGISTRY.register("lavendite_pickaxe", LavenditePickaxeItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_AXE = REGISTRY.register("lavendite_axe", LavenditeAxeItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_SHOVEL = REGISTRY.register("lavendite_shovel", LavenditeShovelItem::new);
	public static final DeferredHolder<Item, Item> LAVENDITE_HOE = REGISTRY.register("lavendite_hoe", LavenditeHoeItem::new);
	public static final DeferredHolder<Item, Item> BONE_NEEDLE = REGISTRY.register("bone_needle", BoneNeedleItem::new);
	public static final DeferredHolder<Item, Item> REGENERATION_NEEDLE = REGISTRY.register("regeneration_needle", RegenerationNeedleItem::new);
	public static final DeferredHolder<Item, Item> ABSORPTION_NEEDLE = REGISTRY.register("absorption_needle", AbsorptionNeedleItem::new);
	public static final DeferredHolder<Item, Item> RESISTANCE_NEEDLE = REGISTRY.register("resistance_needle", ResistanceNeedleItem::new);
	public static final DeferredHolder<Item, Item> GLOWING_NEEDLE = REGISTRY.register("glowing_needle", GlowingNeedleItem::new);
	public static final DeferredHolder<Item, Item> ROT_NEEDLE = REGISTRY.register("rot_needle", RotNeedleItem::new);
	public static final DeferredHolder<Item, Item> JUMP_BOOST_NEEDLE = REGISTRY.register("jump_boost_needle", JumpBoostNeedleItem::new);
	public static final DeferredHolder<Item, Item> HEXED_NEEDLE = REGISTRY.register("hexed_needle", HexedNeedleItem::new);
	public static final DeferredHolder<Item, Item> FIRE_RESISTANCE_NEEDLE = REGISTRY.register("fire_resistance_needle", FireResistanceNeedleItem::new);
	public static final DeferredHolder<Item, Item> POISON_NEEDLE = REGISTRY.register("poison_needle", PoisonNeedleItem::new);
	public static final DeferredHolder<Item, Item> SPEED_NEEDLE = REGISTRY.register("speed_needle", SpeedNeedleItem::new);
	public static final DeferredHolder<Item, Item> HEALTH_BOOST_NEEDLE = REGISTRY.register("health_boost_needle", HealthBoostNeedleItem::new);
	public static final DeferredHolder<Item, Item> WITHER_NEEDLE = REGISTRY.register("wither_needle", WitherNeedleItem::new);
	public static final DeferredHolder<Item, Item> SATURATION_NEEDLE = REGISTRY.register("saturation_needle", SaturationNeedleItem::new);
	public static final DeferredHolder<Item, Item> JUDGEMENT = REGISTRY.register("judgement", JudgementItem::new);
	public static final DeferredHolder<Item, Item> FORSAKEN_SPAWN_EGG = REGISTRY.register("forsaken_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.FORSAKEN, -14014174, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ELYTRA_PIECE = REGISTRY.register("elytra_piece", ElytraPieceItem::new);
	public static final DeferredHolder<Item, Item> VOIDRIUM_BULWARK = REGISTRY.register("voidrium_bulwark", VoidriumBulwarkItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_MOSS_ACTIVE = block(TheDeepVoidModBlocks.ROTTEN_MOSS_ACTIVE);
	public static final DeferredHolder<Item, Item> BIG_SMOKE_VENT = block(TheDeepVoidModBlocks.BIG_SMOKE_VENT);
	public static final DeferredHolder<Item, Item> BIG_SMOKE_VENT_CORNER = block(TheDeepVoidModBlocks.BIG_SMOKE_VENT_CORNER);
	public static final DeferredHolder<Item, Item> VENT_STONE = block(TheDeepVoidModBlocks.VENT_STONE);
	public static final DeferredHolder<Item, Item> CORPSE_PILE = block(TheDeepVoidModBlocks.CORPSE_PILE);
	public static final DeferredHolder<Item, Item> SEEKER_SPAWN_EGG = REGISTRY.register("seeker_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.SEEKER, -16777216, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BIG_TOOTH = block(TheDeepVoidModBlocks.BIG_TOOTH);
	public static final DeferredHolder<Item, Item> SOUL_FORGE = block(TheDeepVoidModBlocks.SOUL_FORGE);
	public static final DeferredHolder<Item, Item> SOUL_FUSED_INGOT = REGISTRY.register("soul_fused_ingot", SoulFusedIngotItem::new);
	public static final DeferredHolder<Item, Item> APOSTLE_OF_CATASTROPHE_SPAWN_EGG = REGISTRY.register("apostle_of_catastrophe_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.APOSTLE_OF_CATASTROPHE, -13762560, -11776, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CHAINSAW = REGISTRY.register("chainsaw", ChainsawItem::new);
	public static final DeferredHolder<Item, Item> APOSTLE_OF_CATASTROPHE_TREASURE_BAG = REGISTRY.register("apostle_of_catastrophe_treasure_bag", ApostleOfCatastropheTreasureBagItem::new);
	public static final DeferredHolder<Item, Item> RED_GATE = block(TheDeepVoidModBlocks.RED_GATE);
	public static final DeferredHolder<Item, Item> RED_GATE_NON_SOLID = block(TheDeepVoidModBlocks.RED_GATE_NON_SOLID);
	public static final DeferredHolder<Item, Item> IDLING_APOSTLE_SPAWN_EGG = REGISTRY.register("idling_apostle_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.IDLING_APOSTLE, -15597568, -8427264, new Item.Properties()));
	public static final DeferredHolder<Item, Item> KNIFE_GLOVE = REGISTRY.register("knife_glove", KnifeGloveItem::new);
	public static final DeferredHolder<Item, Item> BLOCK_OF_SOUL_FUSED_INGOTS = block(TheDeepVoidModBlocks.BLOCK_OF_SOUL_FUSED_INGOTS);
	public static final DeferredHolder<Item, Item> VOID_GROWTH = block(TheDeepVoidModBlocks.VOID_GROWTH);
	public static final DeferredHolder<Item, Item> HERESY = REGISTRY.register("heresy", HeresyItem::new);
	public static final DeferredHolder<Item, Item> FLESH_STAIRS = block(TheDeepVoidModBlocks.FLESH_STAIRS);
	public static final DeferredHolder<Item, Item> FLESH_SLAB = block(TheDeepVoidModBlocks.FLESH_SLAB);
	public static final DeferredHolder<Item, Item> TENDONS = block(TheDeepVoidModBlocks.TENDONS);
	public static final DeferredHolder<Item, Item> OLD_CORPSE_PILE = block(TheDeepVoidModBlocks.OLD_CORPSE_PILE);
	public static final DeferredHolder<Item, Item> OLD_CORPSE = block(TheDeepVoidModBlocks.OLD_CORPSE);
	public static final DeferredHolder<Item, Item> OLD_WALL_CORPSE = block(TheDeepVoidModBlocks.OLD_WALL_CORPSE);
	public static final DeferredHolder<Item, Item> OLD_COVERED_CORPSE = block(TheDeepVoidModBlocks.OLD_COVERED_CORPSE);
	public static final DeferredHolder<Item, Item> OLD_LAYING_CORPSE = block(TheDeepVoidModBlocks.OLD_LAYING_CORPSE);
	public static final DeferredHolder<Item, Item> OLD_BONE_BLOCK = block(TheDeepVoidModBlocks.OLD_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> FLESHY_ROTTEN_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_ROTTEN_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> FLESHY_OLD_BONE_BLOCK = block(TheDeepVoidModBlocks.FLESHY_OLD_BONE_BLOCK);
	public static final DeferredHolder<Item, Item> EYE_TENDONS = block(TheDeepVoidModBlocks.EYE_TENDONS);
	public static final DeferredHolder<Item, Item> MISANTHROPIC_HIVEMIND_SPAWN_EGG = REGISTRY.register("misanthropic_hivemind_spawn_egg",
			() -> new DeferredSpawnEggItem(TheDeepVoidModEntities.MISANTHROPIC_HIVEMIND, -14613243, -9614774, new Item.Properties()));
	public static final DeferredHolder<Item, Item> PITCH_BLACK = REGISTRY.register("pitch_black", PitchBlackItem::new);
	public static final DeferredHolder<Item, Item> MISANTHROPIC_HIVEMIND_TREASURE_BAG = REGISTRY.register("misanthropic_hivemind_treasure_bag", MisanthropicHivemindTreasureBagItem::new);
	public static final DeferredHolder<Item, Item> FLESH_FANGS_SPAWN_EGG = REGISTRY.register("flesh_fangs_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.FLESH_FANGS, -15073280, -11185078, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GORE_EXPECTORATOR_SPAWN_EGG = REGISTRY.register("gore_expectorator_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.GORE_EXPECTORATOR, -12514806, -6119536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> HIVE_BRAIN_SPAWN_EGG = REGISTRY.register("hive_brain_spawn_egg", () -> new DeferredSpawnEggItem(TheDeepVoidModEntities.HIVE_BRAIN, -13301238, -8894889, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FLESH_BONE = REGISTRY.register("flesh_bone", FleshBoneItem::new);
	public static final DeferredHolder<Item, Item> ANIMOSITY = REGISTRY.register("animosity", AnimosityItem::new);
	public static final DeferredHolder<Item, Item> ANIMOSITY_HIDDEN = REGISTRY.register("animosity_hidden", AnimosityHiddenItem::new);
	public static final DeferredHolder<Item, Item> BLOODY_RIB_CAGE_CHESTPLATE = REGISTRY.register("bloody_rib_cage_chestplate", BloodyRibCageItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> EYEKIN_SADDLE = REGISTRY.register("eyekin_saddle", EyekinSaddleItem::new);
	public static final DeferredHolder<Item, Item> PEEPING_STEM = block(TheDeepVoidModBlocks.PEEPING_STEM);
	public static final DeferredHolder<Item, Item> ACTIVE_FLESH_BLOCK = block(TheDeepVoidModBlocks.ACTIVE_FLESH_BLOCK);
	public static final DeferredHolder<Item, Item> BROWN_EYE_VINE = block(TheDeepVoidModBlocks.BROWN_EYE_VINE);
	public static final DeferredHolder<Item, Item> PURPLE_EYE_VINE = block(TheDeepVoidModBlocks.PURPLE_EYE_VINE);
	public static final DeferredHolder<Item, Item> BIG_BROWN_EYE = block(TheDeepVoidModBlocks.BIG_BROWN_EYE);
	public static final DeferredHolder<Item, Item> BIG_PURPLE_EYE = block(TheDeepVoidModBlocks.BIG_PURPLE_EYE);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredHolder<Item, Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(LAVENDITE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), new ResourceLocation("blocking")));
				ItemProperties.register(EYE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), new ResourceLocation("blocking")));
				ItemProperties.register(DEVOURER_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), new ResourceLocation("blocking")));
				ItemProperties.register(VOIDRIUM_BULWARK.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), new ResourceLocation("blocking")));
			});
		}
	}
}
