
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedeepvoid.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.sounds.SoundEvent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.Registries;

import net.mcreator.thedeepvoid.TheDeepVoidMod;

public class TheDeepVoidModSounds {
	public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(Registries.SOUND_EVENT, TheDeepVoidMod.MODID);
	public static final DeferredHolder<SoundEvent, SoundEvent> STALKER_AMBIENT = REGISTRY.register("stalker_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stalker_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DISTANT_GROWL = REGISTRY.register("distant_growl", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "distant_growl")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MOURNER_AMBIENT = REGISTRY.register("mourner_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "mourner_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HALLUCINATION_AMBIENT = REGISTRY.register("hallucination_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hallucination_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HALLUCINATION_SCREAM = REGISTRY.register("hallucination_scream", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hallucination_scream")));
	public static final DeferredHolder<SoundEvent, SoundEvent> VOID_CAVE_AMBIENT = REGISTRY.register("void_cave_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "void_cave_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LURKER_AMBIENT = REGISTRY.register("lurker_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "lurker_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LURKER_HURT = REGISTRY.register("lurker_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "lurker_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LURKER_DEATH = REGISTRY.register("lurker_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "lurker_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> BONE_CRACK = REGISTRY.register("bone_crack", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "bone_crack")));
	public static final DeferredHolder<SoundEvent, SoundEvent> NIGHTMARE_AMBIENT = REGISTRY.register("nightmare_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "nightmare_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> NIGHTMARE_APPEAR = REGISTRY.register("nightmare_appear", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "nightmare_appear")));
	public static final DeferredHolder<SoundEvent, SoundEvent> NIGHTMARE_WHISPERS = REGISTRY.register("nightmare_whispers", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "nightmare_whispers")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STAB = REGISTRY.register("stab", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stab")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FLESH_BLOCK_STEP = REGISTRY.register("flesh_block_step", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "flesh_block_step")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEEP_RUMBLE = REGISTRY.register("deep_rumble", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "deep_rumble")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FALLING_ROCKS = REGISTRY.register("falling_rocks", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "falling_rocks")));
	public static final DeferredHolder<SoundEvent, SoundEvent> LURKING_MONST3R_MUSIC = REGISTRY.register("lurking_monst3r_music", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "lurking_monst3r_music")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEVOURER_AMBIENT = REGISTRY.register("devourer_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "devourer_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CHASMS_MONST3R_MUSIC = REGISTRY.register("chasms_monst3r_music", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "chasms_monst3r_music")));
	public static final DeferredHolder<SoundEvent, SoundEvent> AMALGAM_STEP = REGISTRY.register("amalgam_step", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "amalgam_step")));
	public static final DeferredHolder<SoundEvent, SoundEvent> AMALGAM_AMBIENT = REGISTRY.register("amalgam_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "amalgam_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DISTANT_STALKER = REGISTRY.register("distant_stalker", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "distant_stalker")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DISTANT_STALKER2 = REGISTRY.register("distant_stalker2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "distant_stalker2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STALKER_HURT = REGISTRY.register("stalker_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stalker_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STALKER_EMERGES_NEW = REGISTRY.register("stalker_emerges_new", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stalker_emerges_new")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GRAVEKEEPER_AMBIENT = REGISTRY.register("gravekeeper_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "gravekeeper_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GRAVEKEEPER_HURT = REGISTRY.register("gravekeeper_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "gravekeeper_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GRAVEKEEPER_DEATH = REGISTRY.register("gravekeeper_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "gravekeeper_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ROAMER_AMBIENT = REGISTRY.register("roamer_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "roamer_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ROAMER_HURT = REGISTRY.register("roamer_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "roamer_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ROAMER_DEATH = REGISTRY.register("roamer_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "roamer_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HEARTBEAT_AMBIENT = REGISTRY.register("heartbeat_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "heartbeat_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DISTANT_MONSTER = REGISTRY.register("distant_monster", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "distant_monster")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EVERHUNGER_AMBIENT = REGISTRY.register("everhunger_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "everhunger_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EVERHUNGER_SCREAM = REGISTRY.register("everhunger_scream", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "everhunger_scream")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EVERHUNGER_HURT = REGISTRY.register("everhunger_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "everhunger_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CLAW_SCRAPES_STONE = REGISTRY.register("claw_scrapes_stone", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "claw_scrapes_stone")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HALLUCINATION_ATTACK = REGISTRY.register("hallucination_attack", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hallucination_attack")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MONOLITH_AMBIENT = REGISTRY.register("monolith_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "monolith_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MONOLITH_AMBIENT_NEW = REGISTRY.register("monolith_ambient_new", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "monolith_ambient_new")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STONE_DRAGGING = REGISTRY.register("stone_dragging", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stone_dragging")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STONE_IMPACT = REGISTRY.register("stone_impact", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stone_impact")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ONLOOKER_HALLUCINATION_SPAWN = REGISTRY.register("onlooker_hallucination_spawn",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "onlooker_hallucination_spawn")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ONLOOKER_AMBIENT = REGISTRY.register("onlooker_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "onlooker_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ONLOOKER_HURT = REGISTRY.register("onlooker_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "onlooker_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> UNDERGROWTH_CREAK = REGISTRY.register("undergrowth_creak", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "undergrowth_creak")));
	public static final DeferredHolder<SoundEvent, SoundEvent> KNOCKING = REGISTRY.register("knocking", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "knocking")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INTENSE_KNOCKING = REGISTRY.register("intense_knocking", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "intense_knocking")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSISTENT_KNOCKING = REGISTRY.register("insistent_knocking", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insistent_knocking")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HUNTER_AMBIENT = REGISTRY.register("hunter_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hunter_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HUNTER_HURT = REGISTRY.register("hunter_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hunter_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EVERHUNGER_CHASE = REGISTRY.register("everhunger_chase", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "everhunger_chase")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_MAW_HIDING = REGISTRY.register("death_maw_hiding", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_maw_hiding")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_MAW_HURT = REGISTRY.register("death_maw_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_maw_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_MAW_BITE = REGISTRY.register("death_maw_bite", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_maw_bite")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_MAW_CHASE = REGISTRY.register("death_maw_chase", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_maw_chase")));
	public static final DeferredHolder<SoundEvent, SoundEvent> VOID_CAVE_AMBIENT_2 = REGISTRY.register("void_cave_ambient_2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "void_cave_ambient_2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> VOID_CAVE_AMBIENT_3 = REGISTRY.register("void_cave_ambient_3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "void_cave_ambient_3")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FOOL_EATER_HURT = REGISTRY.register("fool_eater_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "fool_eater_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FOOL_EATER_AMBIENT = REGISTRY.register("fool_eater_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "fool_eater_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FOOL_EATER_TARGETS = REGISTRY.register("fool_eater_targets", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "fool_eater_targets")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CLAWS_SLASH = REGISTRY.register("claws_slash", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "claws_slash")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SLOW_WHISPERS = REGISTRY.register("slow_whispers", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "slow_whispers")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SLOW_WHISPERS_2 = REGISTRY.register("slow_whispers_2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "slow_whispers_2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECTS_CRAWLING = REGISTRY.register("insects_crawling", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insects_crawling")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECT_CRY_1 = REGISTRY.register("insect_cry_1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insect_cry_1")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECT_CRY_2 = REGISTRY.register("insect_cry_2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insect_cry_2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECTS_CRAWLING_LOUD = REGISTRY.register("insects_crawling_loud", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insects_crawling_loud")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECT_CRY_1_LOUD = REGISTRY.register("insect_cry_1_loud", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insect_cry_1_loud")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECT_CRY_2_LOUD = REGISTRY.register("insect_cry_2_loud", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insect_cry_2_loud")));
	public static final DeferredHolder<SoundEvent, SoundEvent> INSECT_FLY = REGISTRY.register("insect_fly", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "insect_fly")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MOTHER_CRAWLER_AMBIENT = REGISTRY.register("mother_crawler_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "mother_crawler_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MOTHER_CRAWLER_HURT = REGISTRY.register("mother_crawler_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "mother_crawler_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> MOTHER_CRAWLER_DEATH = REGISTRY.register("mother_crawler_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "mother_crawler_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GIANT_CREATURE_BREATHING = REGISTRY.register("giant_creature_breathing", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "giant_creature_breathing")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GIANT_CREATURE_ANGRY = REGISTRY.register("giant_creature_angry", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "giant_creature_angry")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_VULTURE_AMBIENT = REGISTRY.register("death_vulture_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_vulture_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DEATH_VULTURE_HURT = REGISTRY.register("death_vulture_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "death_vulture_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> RIDING_CROP_HIT = REGISTRY.register("riding_crop_hit", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "riding_crop_hit")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CROW_CALL = REGISTRY.register("crow_call", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "crow_call")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SOUL_SEEKER_SLASH = REGISTRY.register("soul_seeker_slash", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "soul_seeker_slash")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SINS_AND_SINNERS = REGISTRY.register("sins_and_sinners", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "sins_and_sinners")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FORSAKEN_BARRENS_AMBIENT = REGISTRY.register("forsaken_barrens_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "forsaken_barrens_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> STALKER_DEATH = REGISTRY.register("stalker_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "stalker_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EYEKIN_AMBIENT = REGISTRY.register("eyekin_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "eyekin_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EYEKIN_HURT = REGISTRY.register("eyekin_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "eyekin_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EYEKIN_DEATH = REGISTRY.register("eyekin_death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "eyekin_death")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EYEKIN_FLY = REGISTRY.register("eyekin_fly", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "eyekin_fly")));
	public static final DeferredHolder<SoundEvent, SoundEvent> ABDUCTOR_AMBIENT = REGISTRY.register("abductor_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "abductor_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CENTIGAZE_AMBIENT = REGISTRY.register("centigaze_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "centigaze_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CENTIGAZE_HIDDEN = REGISTRY.register("centigaze_hidden", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "centigaze_hidden")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WEAVER_AMBIENT = REGISTRY.register("weaver_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "weaver_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WEAVER_HURT = REGISTRY.register("weaver_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "weaver_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> OMINOUS_MURMURS = REGISTRY.register("ominous_murmurs", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "ominous_murmurs")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DARKMARE = REGISTRY.register("darkmare", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "darkmare")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WEAVER_SCREAM = REGISTRY.register("weaver_scream", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "weaver_scream")));
	public static final DeferredHolder<SoundEvent, SoundEvent> WEAVER_SCREAM_LOUD = REGISTRY.register("weaver_scream_loud", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "weaver_scream_loud")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_HIT1 = REGISTRY.register("tombstone_hit1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_hit1")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_HIT2 = REGISTRY.register("tombstone_hit2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_hit2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_HIT3 = REGISTRY.register("tombstone_hit3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_hit3")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_MOBHIT1 = REGISTRY.register("tombstone_mobhit1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_mobhit1")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_MOBHIT2 = REGISTRY.register("tombstone_mobhit2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_mobhit2")));
	public static final DeferredHolder<SoundEvent, SoundEvent> TOMBSTONE_MOBHIT3 = REGISTRY.register("tombstone_mobhit3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "tombstone_mobhit3")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FROM_WITHIN_MONST3R_MUSIC = REGISTRY.register("from_within_monst3r_music", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "from_within_monst3r_music")));
	public static final DeferredHolder<SoundEvent, SoundEvent> GATHERING_GROUNDS_LOOP = REGISTRY.register("gathering_grounds_loop", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "gathering_grounds_loop")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SOUL_PASSING_BY = REGISTRY.register("soul_passing_by", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "soul_passing_by")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FORSAKEN_AMBIENT = REGISTRY.register("forsaken_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "forsaken_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FORSAKEN_HURT = REGISTRY.register("forsaken_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "forsaken_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> SEEKER_SPAWN = REGISTRY.register("seeker_spawn", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "seeker_spawn")));
	public static final DeferredHolder<SoundEvent, SoundEvent> CHAINSAW = REGISTRY.register("chainsaw", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "chainsaw")));
	public static final DeferredHolder<SoundEvent, SoundEvent> APOSTLE_LAUGH = REGISTRY.register("apostle_laugh", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "apostle_laugh")));
	public static final DeferredHolder<SoundEvent, SoundEvent> APOSTLE_HYSTERICAL_LAUGH = REGISTRY.register("apostle_hysterical_laugh", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "apostle_hysterical_laugh")));
	public static final DeferredHolder<SoundEvent, SoundEvent> DECAPITATE = REGISTRY.register("decapitate", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "decapitate")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FOG_APPEAR = REGISTRY.register("fog_appear", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "fog_appear")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HERESY_SHOOT = REGISTRY.register("heresy_shoot", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "heresy_shoot")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HERESY_LEVER = REGISTRY.register("heresy_lever", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "heresy_lever")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HERESY_SHELL_FALL = REGISTRY.register("heresy_shell_fall", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "heresy_shell_fall")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FLESH = REGISTRY.register("flesh", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "flesh")));
	public static final DeferredHolder<SoundEvent, SoundEvent> FLESH_BLOCK_PLACE = REGISTRY.register("flesh_block_place", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "flesh_block_place")));
	public static final DeferredHolder<SoundEvent, SoundEvent> PITCH_BLACK = REGISTRY.register("pitch_black", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "pitch_black")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HIVEMIND_AMBIENT = REGISTRY.register("hivemind_ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hivemind_ambient")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HIVEMIND_HURT = REGISTRY.register("hivemind_hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hivemind_hurt")));
	public static final DeferredHolder<SoundEvent, SoundEvent> HIVEMIND_SCREAM = REGISTRY.register("hivemind_scream", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "hivemind_scream")));
	public static final DeferredHolder<SoundEvent, SoundEvent> EYEKIN_WING_FLAP = REGISTRY.register("eyekin_wing_flap", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("the_deep_void", "eyekin_wing_flap")));
}
